// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package init

import (
	"context"

	"github.com/kaweezle/iknite/pkg/apis/iknite"
	"github.com/kaweezle/iknite/pkg/apis/iknite/v1alpha1"
	"github.com/kaweezle/iknite/pkg/host"
	mock "github.com/stretchr/testify/mock"
)

// NewMockDaemonizeData creates a new instance of MockDaemonizeData. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDaemonizeData(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDaemonizeData {
	mock := &MockDaemonizeData{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDaemonizeData is an autogenerated mock type for the daemonizeData type
type MockDaemonizeData struct {
	mock.Mock
}

type MockDaemonizeData_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDaemonizeData) EXPECT() *MockDaemonizeData_Expecter {
	return &MockDaemonizeData_Expecter{mock: &_m.Mock}
}

// CloseMDnsConn provides a mock function for the type MockDaemonizeData
func (_mock *MockDaemonizeData) CloseMDnsConn() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for CloseMDnsConn")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDaemonizeData_CloseMDnsConn_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CloseMDnsConn'
type MockDaemonizeData_CloseMDnsConn_Call struct {
	*mock.Call
}

// CloseMDnsConn is a helper method to define mock.On call
func (_e *MockDaemonizeData_Expecter) CloseMDnsConn() *MockDaemonizeData_CloseMDnsConn_Call {
	return &MockDaemonizeData_CloseMDnsConn_Call{Call: _e.mock.On("CloseMDnsConn")}
}

func (_c *MockDaemonizeData_CloseMDnsConn_Call) Run(run func()) *MockDaemonizeData_CloseMDnsConn_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDaemonizeData_CloseMDnsConn_Call) Return(err error) *MockDaemonizeData_CloseMDnsConn_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDaemonizeData_CloseMDnsConn_Call) RunAndReturn(run func() error) *MockDaemonizeData_CloseMDnsConn_Call {
	_c.Call.Return(run)
	return _c
}

// Context provides a mock function for the type MockDaemonizeData
func (_mock *MockDaemonizeData) Context() context.Context {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Context")
	}

	var r0 context.Context
	if returnFunc, ok := ret.Get(0).(func() context.Context); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(context.Context)
		}
	}
	return r0
}

// MockDaemonizeData_Context_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Context'
type MockDaemonizeData_Context_Call struct {
	*mock.Call
}

// Context is a helper method to define mock.On call
func (_e *MockDaemonizeData_Expecter) Context() *MockDaemonizeData_Context_Call {
	return &MockDaemonizeData_Context_Call{Call: _e.mock.On("Context")}
}

func (_c *MockDaemonizeData_Context_Call) Run(run func()) *MockDaemonizeData_Context_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDaemonizeData_Context_Call) Return(context1 context.Context) *MockDaemonizeData_Context_Call {
	_c.Call.Return(context1)
	return _c
}

func (_c *MockDaemonizeData_Context_Call) RunAndReturn(run func() context.Context) *MockDaemonizeData_Context_Call {
	_c.Call.Return(run)
	return _c
}

// Host provides a mock function for the type MockDaemonizeData
func (_mock *MockDaemonizeData) Host() host.Host {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Host")
	}

	var r0 host.Host
	if returnFunc, ok := ret.Get(0).(func() host.Host); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(host.Host)
		}
	}
	return r0
}

// MockDaemonizeData_Host_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Host'
type MockDaemonizeData_Host_Call struct {
	*mock.Call
}

// Host is a helper method to define mock.On call
func (_e *MockDaemonizeData_Expecter) Host() *MockDaemonizeData_Host_Call {
	return &MockDaemonizeData_Host_Call{Call: _e.mock.On("Host")}
}

func (_c *MockDaemonizeData_Host_Call) Run(run func()) *MockDaemonizeData_Host_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDaemonizeData_Host_Call) Return(host1 host.Host) *MockDaemonizeData_Host_Call {
	_c.Call.Return(host1)
	return _c
}

func (_c *MockDaemonizeData_Host_Call) RunAndReturn(run func() host.Host) *MockDaemonizeData_Host_Call {
	_c.Call.Return(run)
	return _c
}

// IkniteCluster provides a mock function for the type MockDaemonizeData
func (_mock *MockDaemonizeData) IkniteCluster() *v1alpha1.IkniteCluster {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for IkniteCluster")
	}

	var r0 *v1alpha1.IkniteCluster
	if returnFunc, ok := ret.Get(0).(func() *v1alpha1.IkniteCluster); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1alpha1.IkniteCluster)
		}
	}
	return r0
}

// MockDaemonizeData_IkniteCluster_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IkniteCluster'
type MockDaemonizeData_IkniteCluster_Call struct {
	*mock.Call
}

// IkniteCluster is a helper method to define mock.On call
func (_e *MockDaemonizeData_Expecter) IkniteCluster() *MockDaemonizeData_IkniteCluster_Call {
	return &MockDaemonizeData_IkniteCluster_Call{Call: _e.mock.On("IkniteCluster")}
}

func (_c *MockDaemonizeData_IkniteCluster_Call) Run(run func()) *MockDaemonizeData_IkniteCluster_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDaemonizeData_IkniteCluster_Call) Return(ikniteCluster *v1alpha1.IkniteCluster) *MockDaemonizeData_IkniteCluster_Call {
	_c.Call.Return(ikniteCluster)
	return _c
}

func (_c *MockDaemonizeData_IkniteCluster_Call) RunAndReturn(run func() *v1alpha1.IkniteCluster) *MockDaemonizeData_IkniteCluster_Call {
	_c.Call.Return(run)
	return _c
}

// KubeletProcess provides a mock function for the type MockDaemonizeData
func (_mock *MockDaemonizeData) KubeletProcess() host.Process {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for KubeletProcess")
	}

	var r0 host.Process
	if returnFunc, ok := ret.Get(0).(func() host.Process); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(host.Process)
		}
	}
	return r0
}

// MockDaemonizeData_KubeletProcess_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'KubeletProcess'
type MockDaemonizeData_KubeletProcess_Call struct {
	*mock.Call
}

// KubeletProcess is a helper method to define mock.On call
func (_e *MockDaemonizeData_Expecter) KubeletProcess() *MockDaemonizeData_KubeletProcess_Call {
	return &MockDaemonizeData_KubeletProcess_Call{Call: _e.mock.On("KubeletProcess")}
}

func (_c *MockDaemonizeData_KubeletProcess_Call) Run(run func()) *MockDaemonizeData_KubeletProcess_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDaemonizeData_KubeletProcess_Call) Return(process host.Process) *MockDaemonizeData_KubeletProcess_Call {
	_c.Call.Return(process)
	return _c
}

func (_c *MockDaemonizeData_KubeletProcess_Call) RunAndReturn(run func() host.Process) *MockDaemonizeData_KubeletProcess_Call {
	_c.Call.Return(run)
	return _c
}

// SetKubeletProcess provides a mock function for the type MockDaemonizeData
func (_mock *MockDaemonizeData) SetKubeletProcess(process host.Process) {
	_mock.Called(process)
	return
}

// MockDaemonizeData_SetKubeletProcess_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetKubeletProcess'
type MockDaemonizeData_SetKubeletProcess_Call struct {
	*mock.Call
}

// SetKubeletProcess is a helper method to define mock.On call
//   - process host.Process
func (_e *MockDaemonizeData_Expecter) SetKubeletProcess(process interface{}) *MockDaemonizeData_SetKubeletProcess_Call {
	return &MockDaemonizeData_SetKubeletProcess_Call{Call: _e.mock.On("SetKubeletProcess", process)}
}

func (_c *MockDaemonizeData_SetKubeletProcess_Call) Run(run func(process host.Process)) *MockDaemonizeData_SetKubeletProcess_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 host.Process
		if args[0] != nil {
			arg0 = args[0].(host.Process)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockDaemonizeData_SetKubeletProcess_Call) Return() *MockDaemonizeData_SetKubeletProcess_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockDaemonizeData_SetKubeletProcess_Call) RunAndReturn(run func(process host.Process)) *MockDaemonizeData_SetKubeletProcess_Call {
	_c.Run(run)
	return _c
}

// StopStatusServer provides a mock function for the type MockDaemonizeData
func (_mock *MockDaemonizeData) StopStatusServer() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for StopStatusServer")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDaemonizeData_StopStatusServer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StopStatusServer'
type MockDaemonizeData_StopStatusServer_Call struct {
	*mock.Call
}

// StopStatusServer is a helper method to define mock.On call
func (_e *MockDaemonizeData_Expecter) StopStatusServer() *MockDaemonizeData_StopStatusServer_Call {
	return &MockDaemonizeData_StopStatusServer_Call{Call: _e.mock.On("StopStatusServer")}
}

func (_c *MockDaemonizeData_StopStatusServer_Call) Run(run func()) *MockDaemonizeData_StopStatusServer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDaemonizeData_StopStatusServer_Call) Return(err error) *MockDaemonizeData_StopStatusServer_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDaemonizeData_StopStatusServer_Call) RunAndReturn(run func() error) *MockDaemonizeData_StopStatusServer_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateIkniteCluster provides a mock function for the type MockDaemonizeData
func (_mock *MockDaemonizeData) UpdateIkniteCluster(state iknite.ClusterState, phase string, ready []*v1alpha1.WorkloadState, unready []*v1alpha1.WorkloadState) {
	_mock.Called(state, phase, ready, unready)
	return
}

// MockDaemonizeData_UpdateIkniteCluster_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateIkniteCluster'
type MockDaemonizeData_UpdateIkniteCluster_Call struct {
	*mock.Call
}

// UpdateIkniteCluster is a helper method to define mock.On call
//   - state iknite.ClusterState
//   - phase string
//   - ready []*v1alpha1.WorkloadState
//   - unready []*v1alpha1.WorkloadState
func (_e *MockDaemonizeData_Expecter) UpdateIkniteCluster(state interface{}, phase interface{}, ready interface{}, unready interface{}) *MockDaemonizeData_UpdateIkniteCluster_Call {
	return &MockDaemonizeData_UpdateIkniteCluster_Call{Call: _e.mock.On("UpdateIkniteCluster", state, phase, ready, unready)}
}

func (_c *MockDaemonizeData_UpdateIkniteCluster_Call) Run(run func(state iknite.ClusterState, phase string, ready []*v1alpha1.WorkloadState, unready []*v1alpha1.WorkloadState)) *MockDaemonizeData_UpdateIkniteCluster_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 iknite.ClusterState
		if args[0] != nil {
			arg0 = args[0].(iknite.ClusterState)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []*v1alpha1.WorkloadState
		if args[2] != nil {
			arg2 = args[2].([]*v1alpha1.WorkloadState)
		}
		var arg3 []*v1alpha1.WorkloadState
		if args[3] != nil {
			arg3 = args[3].([]*v1alpha1.WorkloadState)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockDaemonizeData_UpdateIkniteCluster_Call) Return() *MockDaemonizeData_UpdateIkniteCluster_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockDaemonizeData_UpdateIkniteCluster_Call) RunAndReturn(run func(state iknite.ClusterState, phase string, ready []*v1alpha1.WorkloadState, unready []*v1alpha1.WorkloadState)) *MockDaemonizeData_UpdateIkniteCluster_Call {
	_c.Run(run)
	return _c
}
