// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package init

import (
	"context"
	"io"

	"github.com/kaweezle/iknite/pkg/apis/iknite"
	"github.com/kaweezle/iknite/pkg/apis/iknite/v1alpha1"
	"github.com/kaweezle/iknite/pkg/host"
	"github.com/kaweezle/iknite/pkg/server"
	"github.com/kaweezle/iknite/pkg/utils"
	"github.com/pion/mdns"
	mock "github.com/stretchr/testify/mock"
	"k8s.io/apimachinery/pkg/util/sets"
	"k8s.io/cli-runtime/pkg/genericclioptions"
	"k8s.io/client-go/kubernetes"
	"k8s.io/client-go/tools/clientcmd/api"
	"k8s.io/kubernetes/cmd/kubeadm/app/apis/kubeadm"
)

// NewMockIkniteInitData creates a new instance of MockIkniteInitData. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIkniteInitData(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIkniteInitData {
	mock := &MockIkniteInitData{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIkniteInitData is an autogenerated mock type for the IkniteInitData type
type MockIkniteInitData struct {
	mock.Mock
}

type MockIkniteInitData_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIkniteInitData) EXPECT() *MockIkniteInitData_Expecter {
	return &MockIkniteInitData_Expecter{mock: &_m.Mock}
}

// CertificateDir provides a mock function for the type MockIkniteInitData
func (_mock *MockIkniteInitData) CertificateDir() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for CertificateDir")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockIkniteInitData_CertificateDir_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CertificateDir'
type MockIkniteInitData_CertificateDir_Call struct {
	*mock.Call
}

// CertificateDir is a helper method to define mock.On call
func (_e *MockIkniteInitData_Expecter) CertificateDir() *MockIkniteInitData_CertificateDir_Call {
	return &MockIkniteInitData_CertificateDir_Call{Call: _e.mock.On("CertificateDir")}
}

func (_c *MockIkniteInitData_CertificateDir_Call) Run(run func()) *MockIkniteInitData_CertificateDir_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIkniteInitData_CertificateDir_Call) Return(s string) *MockIkniteInitData_CertificateDir_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockIkniteInitData_CertificateDir_Call) RunAndReturn(run func() string) *MockIkniteInitData_CertificateDir_Call {
	_c.Call.Return(run)
	return _c
}

// CertificateKey provides a mock function for the type MockIkniteInitData
func (_mock *MockIkniteInitData) CertificateKey() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for CertificateKey")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockIkniteInitData_CertificateKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CertificateKey'
type MockIkniteInitData_CertificateKey_Call struct {
	*mock.Call
}

// CertificateKey is a helper method to define mock.On call
func (_e *MockIkniteInitData_Expecter) CertificateKey() *MockIkniteInitData_CertificateKey_Call {
	return &MockIkniteInitData_CertificateKey_Call{Call: _e.mock.On("CertificateKey")}
}

func (_c *MockIkniteInitData_CertificateKey_Call) Run(run func()) *MockIkniteInitData_CertificateKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIkniteInitData_CertificateKey_Call) Return(s string) *MockIkniteInitData_CertificateKey_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockIkniteInitData_CertificateKey_Call) RunAndReturn(run func() string) *MockIkniteInitData_CertificateKey_Call {
	_c.Call.Return(run)
	return _c
}

// CertificateWriteDir provides a mock function for the type MockIkniteInitData
func (_mock *MockIkniteInitData) CertificateWriteDir() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for CertificateWriteDir")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockIkniteInitData_CertificateWriteDir_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CertificateWriteDir'
type MockIkniteInitData_CertificateWriteDir_Call struct {
	*mock.Call
}

// CertificateWriteDir is a helper method to define mock.On call
func (_e *MockIkniteInitData_Expecter) CertificateWriteDir() *MockIkniteInitData_CertificateWriteDir_Call {
	return &MockIkniteInitData_CertificateWriteDir_Call{Call: _e.mock.On("CertificateWriteDir")}
}

func (_c *MockIkniteInitData_CertificateWriteDir_Call) Run(run func()) *MockIkniteInitData_CertificateWriteDir_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIkniteInitData_CertificateWriteDir_Call) Return(s string) *MockIkniteInitData_CertificateWriteDir_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockIkniteInitData_CertificateWriteDir_Call) RunAndReturn(run func() string) *MockIkniteInitData_CertificateWriteDir_Call {
	_c.Call.Return(run)
	return _c
}

// Cfg provides a mock function for the type MockIkniteInitData
func (_mock *MockIkniteInitData) Cfg() *kubeadm.InitConfiguration {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Cfg")
	}

	var r0 *kubeadm.InitConfiguration
	if returnFunc, ok := ret.Get(0).(func() *kubeadm.InitConfiguration); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*kubeadm.InitConfiguration)
		}
	}
	return r0
}

// MockIkniteInitData_Cfg_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Cfg'
type MockIkniteInitData_Cfg_Call struct {
	*mock.Call
}

// Cfg is a helper method to define mock.On call
func (_e *MockIkniteInitData_Expecter) Cfg() *MockIkniteInitData_Cfg_Call {
	return &MockIkniteInitData_Cfg_Call{Call: _e.mock.On("Cfg")}
}

func (_c *MockIkniteInitData_Cfg_Call) Run(run func()) *MockIkniteInitData_Cfg_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIkniteInitData_Cfg_Call) Return(initConfiguration *kubeadm.InitConfiguration) *MockIkniteInitData_Cfg_Call {
	_c.Call.Return(initConfiguration)
	return _c
}

func (_c *MockIkniteInitData_Cfg_Call) RunAndReturn(run func() *kubeadm.InitConfiguration) *MockIkniteInitData_Cfg_Call {
	_c.Call.Return(run)
	return _c
}

// Client provides a mock function for the type MockIkniteInitData
func (_mock *MockIkniteInitData) Client() (kubernetes.Interface, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Client")
	}

	var r0 kubernetes.Interface
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (kubernetes.Interface, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() kubernetes.Interface); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(kubernetes.Interface)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIkniteInitData_Client_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Client'
type MockIkniteInitData_Client_Call struct {
	*mock.Call
}

// Client is a helper method to define mock.On call
func (_e *MockIkniteInitData_Expecter) Client() *MockIkniteInitData_Client_Call {
	return &MockIkniteInitData_Client_Call{Call: _e.mock.On("Client")}
}

func (_c *MockIkniteInitData_Client_Call) Run(run func()) *MockIkniteInitData_Client_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIkniteInitData_Client_Call) Return(interfaceParam kubernetes.Interface, err error) *MockIkniteInitData_Client_Call {
	_c.Call.Return(interfaceParam, err)
	return _c
}

func (_c *MockIkniteInitData_Client_Call) RunAndReturn(run func() (kubernetes.Interface, error)) *MockIkniteInitData_Client_Call {
	_c.Call.Return(run)
	return _c
}

// CloseMDnsConn provides a mock function for the type MockIkniteInitData
func (_mock *MockIkniteInitData) CloseMDnsConn() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for CloseMDnsConn")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIkniteInitData_CloseMDnsConn_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CloseMDnsConn'
type MockIkniteInitData_CloseMDnsConn_Call struct {
	*mock.Call
}

// CloseMDnsConn is a helper method to define mock.On call
func (_e *MockIkniteInitData_Expecter) CloseMDnsConn() *MockIkniteInitData_CloseMDnsConn_Call {
	return &MockIkniteInitData_CloseMDnsConn_Call{Call: _e.mock.On("CloseMDnsConn")}
}

func (_c *MockIkniteInitData_CloseMDnsConn_Call) Run(run func()) *MockIkniteInitData_CloseMDnsConn_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIkniteInitData_CloseMDnsConn_Call) Return(err error) *MockIkniteInitData_CloseMDnsConn_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIkniteInitData_CloseMDnsConn_Call) RunAndReturn(run func() error) *MockIkniteInitData_CloseMDnsConn_Call {
	_c.Call.Return(run)
	return _c
}

// Context provides a mock function for the type MockIkniteInitData
func (_mock *MockIkniteInitData) Context() context.Context {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Context")
	}

	var r0 context.Context
	if returnFunc, ok := ret.Get(0).(func() context.Context); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(context.Context)
		}
	}
	return r0
}

// MockIkniteInitData_Context_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Context'
type MockIkniteInitData_Context_Call struct {
	*mock.Call
}

// Context is a helper method to define mock.On call
func (_e *MockIkniteInitData_Expecter) Context() *MockIkniteInitData_Context_Call {
	return &MockIkniteInitData_Context_Call{Call: _e.mock.On("Context")}
}

func (_c *MockIkniteInitData_Context_Call) Run(run func()) *MockIkniteInitData_Context_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIkniteInitData_Context_Call) Return(context1 context.Context) *MockIkniteInitData_Context_Call {
	_c.Call.Return(context1)
	return _c
}

func (_c *MockIkniteInitData_Context_Call) RunAndReturn(run func() context.Context) *MockIkniteInitData_Context_Call {
	_c.Call.Return(run)
	return _c
}

// DryRun provides a mock function for the type MockIkniteInitData
func (_mock *MockIkniteInitData) DryRun() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for DryRun")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockIkniteInitData_DryRun_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DryRun'
type MockIkniteInitData_DryRun_Call struct {
	*mock.Call
}

// DryRun is a helper method to define mock.On call
func (_e *MockIkniteInitData_Expecter) DryRun() *MockIkniteInitData_DryRun_Call {
	return &MockIkniteInitData_DryRun_Call{Call: _e.mock.On("DryRun")}
}

func (_c *MockIkniteInitData_DryRun_Call) Run(run func()) *MockIkniteInitData_DryRun_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIkniteInitData_DryRun_Call) Return(b bool) *MockIkniteInitData_DryRun_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockIkniteInitData_DryRun_Call) RunAndReturn(run func() bool) *MockIkniteInitData_DryRun_Call {
	_c.Call.Return(run)
	return _c
}

// ExternalCA provides a mock function for the type MockIkniteInitData
func (_mock *MockIkniteInitData) ExternalCA() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ExternalCA")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockIkniteInitData_ExternalCA_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExternalCA'
type MockIkniteInitData_ExternalCA_Call struct {
	*mock.Call
}

// ExternalCA is a helper method to define mock.On call
func (_e *MockIkniteInitData_Expecter) ExternalCA() *MockIkniteInitData_ExternalCA_Call {
	return &MockIkniteInitData_ExternalCA_Call{Call: _e.mock.On("ExternalCA")}
}

func (_c *MockIkniteInitData_ExternalCA_Call) Run(run func()) *MockIkniteInitData_ExternalCA_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIkniteInitData_ExternalCA_Call) Return(b bool) *MockIkniteInitData_ExternalCA_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockIkniteInitData_ExternalCA_Call) RunAndReturn(run func() bool) *MockIkniteInitData_ExternalCA_Call {
	_c.Call.Return(run)
	return _c
}

// Host provides a mock function for the type MockIkniteInitData
func (_mock *MockIkniteInitData) Host() host.Host {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Host")
	}

	var r0 host.Host
	if returnFunc, ok := ret.Get(0).(func() host.Host); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(host.Host)
		}
	}
	return r0
}

// MockIkniteInitData_Host_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Host'
type MockIkniteInitData_Host_Call struct {
	*mock.Call
}

// Host is a helper method to define mock.On call
func (_e *MockIkniteInitData_Expecter) Host() *MockIkniteInitData_Host_Call {
	return &MockIkniteInitData_Host_Call{Call: _e.mock.On("Host")}
}

func (_c *MockIkniteInitData_Host_Call) Run(run func()) *MockIkniteInitData_Host_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIkniteInitData_Host_Call) Return(host1 host.Host) *MockIkniteInitData_Host_Call {
	_c.Call.Return(host1)
	return _c
}

func (_c *MockIkniteInitData_Host_Call) RunAndReturn(run func() host.Host) *MockIkniteInitData_Host_Call {
	_c.Call.Return(run)
	return _c
}

// IgnorePreflightErrors provides a mock function for the type MockIkniteInitData
func (_mock *MockIkniteInitData) IgnorePreflightErrors() sets.Set[string] {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for IgnorePreflightErrors")
	}

	var r0 sets.Set[string]
	if returnFunc, ok := ret.Get(0).(func() sets.Set[string]); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(sets.Set[string])
		}
	}
	return r0
}

// MockIkniteInitData_IgnorePreflightErrors_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IgnorePreflightErrors'
type MockIkniteInitData_IgnorePreflightErrors_Call struct {
	*mock.Call
}

// IgnorePreflightErrors is a helper method to define mock.On call
func (_e *MockIkniteInitData_Expecter) IgnorePreflightErrors() *MockIkniteInitData_IgnorePreflightErrors_Call {
	return &MockIkniteInitData_IgnorePreflightErrors_Call{Call: _e.mock.On("IgnorePreflightErrors")}
}

func (_c *MockIkniteInitData_IgnorePreflightErrors_Call) Run(run func()) *MockIkniteInitData_IgnorePreflightErrors_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIkniteInitData_IgnorePreflightErrors_Call) Return(set sets.Set[string]) *MockIkniteInitData_IgnorePreflightErrors_Call {
	_c.Call.Return(set)
	return _c
}

func (_c *MockIkniteInitData_IgnorePreflightErrors_Call) RunAndReturn(run func() sets.Set[string]) *MockIkniteInitData_IgnorePreflightErrors_Call {
	_c.Call.Return(run)
	return _c
}

// IkniteCluster provides a mock function for the type MockIkniteInitData
func (_mock *MockIkniteInitData) IkniteCluster() *v1alpha1.IkniteCluster {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for IkniteCluster")
	}

	var r0 *v1alpha1.IkniteCluster
	if returnFunc, ok := ret.Get(0).(func() *v1alpha1.IkniteCluster); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1alpha1.IkniteCluster)
		}
	}
	return r0
}

// MockIkniteInitData_IkniteCluster_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IkniteCluster'
type MockIkniteInitData_IkniteCluster_Call struct {
	*mock.Call
}

// IkniteCluster is a helper method to define mock.On call
func (_e *MockIkniteInitData_Expecter) IkniteCluster() *MockIkniteInitData_IkniteCluster_Call {
	return &MockIkniteInitData_IkniteCluster_Call{Call: _e.mock.On("IkniteCluster")}
}

func (_c *MockIkniteInitData_IkniteCluster_Call) Run(run func()) *MockIkniteInitData_IkniteCluster_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIkniteInitData_IkniteCluster_Call) Return(ikniteCluster *v1alpha1.IkniteCluster) *MockIkniteInitData_IkniteCluster_Call {
	_c.Call.Return(ikniteCluster)
	return _c
}

func (_c *MockIkniteInitData_IkniteCluster_Call) RunAndReturn(run func() *v1alpha1.IkniteCluster) *MockIkniteInitData_IkniteCluster_Call {
	_c.Call.Return(run)
	return _c
}

// KubeConfig provides a mock function for the type MockIkniteInitData
func (_mock *MockIkniteInitData) KubeConfig() (*api.Config, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for KubeConfig")
	}

	var r0 *api.Config
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (*api.Config, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() *api.Config); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*api.Config)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIkniteInitData_KubeConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'KubeConfig'
type MockIkniteInitData_KubeConfig_Call struct {
	*mock.Call
}

// KubeConfig is a helper method to define mock.On call
func (_e *MockIkniteInitData_Expecter) KubeConfig() *MockIkniteInitData_KubeConfig_Call {
	return &MockIkniteInitData_KubeConfig_Call{Call: _e.mock.On("KubeConfig")}
}

func (_c *MockIkniteInitData_KubeConfig_Call) Run(run func()) *MockIkniteInitData_KubeConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIkniteInitData_KubeConfig_Call) Return(config *api.Config, err error) *MockIkniteInitData_KubeConfig_Call {
	_c.Call.Return(config, err)
	return _c
}

func (_c *MockIkniteInitData_KubeConfig_Call) RunAndReturn(run func() (*api.Config, error)) *MockIkniteInitData_KubeConfig_Call {
	_c.Call.Return(run)
	return _c
}

// KubeConfigDir provides a mock function for the type MockIkniteInitData
func (_mock *MockIkniteInitData) KubeConfigDir() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for KubeConfigDir")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockIkniteInitData_KubeConfigDir_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'KubeConfigDir'
type MockIkniteInitData_KubeConfigDir_Call struct {
	*mock.Call
}

// KubeConfigDir is a helper method to define mock.On call
func (_e *MockIkniteInitData_Expecter) KubeConfigDir() *MockIkniteInitData_KubeConfigDir_Call {
	return &MockIkniteInitData_KubeConfigDir_Call{Call: _e.mock.On("KubeConfigDir")}
}

func (_c *MockIkniteInitData_KubeConfigDir_Call) Run(run func()) *MockIkniteInitData_KubeConfigDir_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIkniteInitData_KubeConfigDir_Call) Return(s string) *MockIkniteInitData_KubeConfigDir_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockIkniteInitData_KubeConfigDir_Call) RunAndReturn(run func() string) *MockIkniteInitData_KubeConfigDir_Call {
	_c.Call.Return(run)
	return _c
}

// KubeConfigPath provides a mock function for the type MockIkniteInitData
func (_mock *MockIkniteInitData) KubeConfigPath() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for KubeConfigPath")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockIkniteInitData_KubeConfigPath_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'KubeConfigPath'
type MockIkniteInitData_KubeConfigPath_Call struct {
	*mock.Call
}

// KubeConfigPath is a helper method to define mock.On call
func (_e *MockIkniteInitData_Expecter) KubeConfigPath() *MockIkniteInitData_KubeConfigPath_Call {
	return &MockIkniteInitData_KubeConfigPath_Call{Call: _e.mock.On("KubeConfigPath")}
}

func (_c *MockIkniteInitData_KubeConfigPath_Call) Run(run func()) *MockIkniteInitData_KubeConfigPath_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIkniteInitData_KubeConfigPath_Call) Return(s string) *MockIkniteInitData_KubeConfigPath_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockIkniteInitData_KubeConfigPath_Call) RunAndReturn(run func() string) *MockIkniteInitData_KubeConfigPath_Call {
	_c.Call.Return(run)
	return _c
}

// KubeletDir provides a mock function for the type MockIkniteInitData
func (_mock *MockIkniteInitData) KubeletDir() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for KubeletDir")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockIkniteInitData_KubeletDir_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'KubeletDir'
type MockIkniteInitData_KubeletDir_Call struct {
	*mock.Call
}

// KubeletDir is a helper method to define mock.On call
func (_e *MockIkniteInitData_Expecter) KubeletDir() *MockIkniteInitData_KubeletDir_Call {
	return &MockIkniteInitData_KubeletDir_Call{Call: _e.mock.On("KubeletDir")}
}

func (_c *MockIkniteInitData_KubeletDir_Call) Run(run func()) *MockIkniteInitData_KubeletDir_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIkniteInitData_KubeletDir_Call) Return(s string) *MockIkniteInitData_KubeletDir_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockIkniteInitData_KubeletDir_Call) RunAndReturn(run func() string) *MockIkniteInitData_KubeletDir_Call {
	_c.Call.Return(run)
	return _c
}

// KubeletProcess provides a mock function for the type MockIkniteInitData
func (_mock *MockIkniteInitData) KubeletProcess() host.Process {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for KubeletProcess")
	}

	var r0 host.Process
	if returnFunc, ok := ret.Get(0).(func() host.Process); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(host.Process)
		}
	}
	return r0
}

// MockIkniteInitData_KubeletProcess_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'KubeletProcess'
type MockIkniteInitData_KubeletProcess_Call struct {
	*mock.Call
}

// KubeletProcess is a helper method to define mock.On call
func (_e *MockIkniteInitData_Expecter) KubeletProcess() *MockIkniteInitData_KubeletProcess_Call {
	return &MockIkniteInitData_KubeletProcess_Call{Call: _e.mock.On("KubeletProcess")}
}

func (_c *MockIkniteInitData_KubeletProcess_Call) Run(run func()) *MockIkniteInitData_KubeletProcess_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIkniteInitData_KubeletProcess_Call) Return(process host.Process) *MockIkniteInitData_KubeletProcess_Call {
	_c.Call.Return(process)
	return _c
}

func (_c *MockIkniteInitData_KubeletProcess_Call) RunAndReturn(run func() host.Process) *MockIkniteInitData_KubeletProcess_Call {
	_c.Call.Return(run)
	return _c
}

// KustomizeOptions provides a mock function for the type MockIkniteInitData
func (_mock *MockIkniteInitData) KustomizeOptions() *utils.KustomizeOptions {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for KustomizeOptions")
	}

	var r0 *utils.KustomizeOptions
	if returnFunc, ok := ret.Get(0).(func() *utils.KustomizeOptions); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*utils.KustomizeOptions)
		}
	}
	return r0
}

// MockIkniteInitData_KustomizeOptions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'KustomizeOptions'
type MockIkniteInitData_KustomizeOptions_Call struct {
	*mock.Call
}

// KustomizeOptions is a helper method to define mock.On call
func (_e *MockIkniteInitData_Expecter) KustomizeOptions() *MockIkniteInitData_KustomizeOptions_Call {
	return &MockIkniteInitData_KustomizeOptions_Call{Call: _e.mock.On("KustomizeOptions")}
}

func (_c *MockIkniteInitData_KustomizeOptions_Call) Run(run func()) *MockIkniteInitData_KustomizeOptions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIkniteInitData_KustomizeOptions_Call) Return(kustomizeOptions *utils.KustomizeOptions) *MockIkniteInitData_KustomizeOptions_Call {
	_c.Call.Return(kustomizeOptions)
	return _c
}

func (_c *MockIkniteInitData_KustomizeOptions_Call) RunAndReturn(run func() *utils.KustomizeOptions) *MockIkniteInitData_KustomizeOptions_Call {
	_c.Call.Return(run)
	return _c
}

// ManifestDir provides a mock function for the type MockIkniteInitData
func (_mock *MockIkniteInitData) ManifestDir() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ManifestDir")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockIkniteInitData_ManifestDir_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ManifestDir'
type MockIkniteInitData_ManifestDir_Call struct {
	*mock.Call
}

// ManifestDir is a helper method to define mock.On call
func (_e *MockIkniteInitData_Expecter) ManifestDir() *MockIkniteInitData_ManifestDir_Call {
	return &MockIkniteInitData_ManifestDir_Call{Call: _e.mock.On("ManifestDir")}
}

func (_c *MockIkniteInitData_ManifestDir_Call) Run(run func()) *MockIkniteInitData_ManifestDir_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIkniteInitData_ManifestDir_Call) Return(s string) *MockIkniteInitData_ManifestDir_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockIkniteInitData_ManifestDir_Call) RunAndReturn(run func() string) *MockIkniteInitData_ManifestDir_Call {
	_c.Call.Return(run)
	return _c
}

// OutputWriter provides a mock function for the type MockIkniteInitData
func (_mock *MockIkniteInitData) OutputWriter() io.Writer {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for OutputWriter")
	}

	var r0 io.Writer
	if returnFunc, ok := ret.Get(0).(func() io.Writer); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.Writer)
		}
	}
	return r0
}

// MockIkniteInitData_OutputWriter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OutputWriter'
type MockIkniteInitData_OutputWriter_Call struct {
	*mock.Call
}

// OutputWriter is a helper method to define mock.On call
func (_e *MockIkniteInitData_Expecter) OutputWriter() *MockIkniteInitData_OutputWriter_Call {
	return &MockIkniteInitData_OutputWriter_Call{Call: _e.mock.On("OutputWriter")}
}

func (_c *MockIkniteInitData_OutputWriter_Call) Run(run func()) *MockIkniteInitData_OutputWriter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIkniteInitData_OutputWriter_Call) Return(writer io.Writer) *MockIkniteInitData_OutputWriter_Call {
	_c.Call.Return(writer)
	return _c
}

func (_c *MockIkniteInitData_OutputWriter_Call) RunAndReturn(run func() io.Writer) *MockIkniteInitData_OutputWriter_Call {
	_c.Call.Return(run)
	return _c
}

// PatchesDir provides a mock function for the type MockIkniteInitData
func (_mock *MockIkniteInitData) PatchesDir() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for PatchesDir")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockIkniteInitData_PatchesDir_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PatchesDir'
type MockIkniteInitData_PatchesDir_Call struct {
	*mock.Call
}

// PatchesDir is a helper method to define mock.On call
func (_e *MockIkniteInitData_Expecter) PatchesDir() *MockIkniteInitData_PatchesDir_Call {
	return &MockIkniteInitData_PatchesDir_Call{Call: _e.mock.On("PatchesDir")}
}

func (_c *MockIkniteInitData_PatchesDir_Call) Run(run func()) *MockIkniteInitData_PatchesDir_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIkniteInitData_PatchesDir_Call) Return(s string) *MockIkniteInitData_PatchesDir_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockIkniteInitData_PatchesDir_Call) RunAndReturn(run func() string) *MockIkniteInitData_PatchesDir_Call {
	_c.Call.Return(run)
	return _c
}

// RESTClientGetter provides a mock function for the type MockIkniteInitData
func (_mock *MockIkniteInitData) RESTClientGetter() (genericclioptions.RESTClientGetter, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for RESTClientGetter")
	}

	var r0 genericclioptions.RESTClientGetter
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (genericclioptions.RESTClientGetter, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() genericclioptions.RESTClientGetter); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(genericclioptions.RESTClientGetter)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIkniteInitData_RESTClientGetter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RESTClientGetter'
type MockIkniteInitData_RESTClientGetter_Call struct {
	*mock.Call
}

// RESTClientGetter is a helper method to define mock.On call
func (_e *MockIkniteInitData_Expecter) RESTClientGetter() *MockIkniteInitData_RESTClientGetter_Call {
	return &MockIkniteInitData_RESTClientGetter_Call{Call: _e.mock.On("RESTClientGetter")}
}

func (_c *MockIkniteInitData_RESTClientGetter_Call) Run(run func()) *MockIkniteInitData_RESTClientGetter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIkniteInitData_RESTClientGetter_Call) Return(rESTClientGetter genericclioptions.RESTClientGetter, err error) *MockIkniteInitData_RESTClientGetter_Call {
	_c.Call.Return(rESTClientGetter, err)
	return _c
}

func (_c *MockIkniteInitData_RESTClientGetter_Call) RunAndReturn(run func() (genericclioptions.RESTClientGetter, error)) *MockIkniteInitData_RESTClientGetter_Call {
	_c.Call.Return(run)
	return _c
}

// SetCertificateKey provides a mock function for the type MockIkniteInitData
func (_mock *MockIkniteInitData) SetCertificateKey(key string) {
	_mock.Called(key)
	return
}

// MockIkniteInitData_SetCertificateKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetCertificateKey'
type MockIkniteInitData_SetCertificateKey_Call struct {
	*mock.Call
}

// SetCertificateKey is a helper method to define mock.On call
//   - key string
func (_e *MockIkniteInitData_Expecter) SetCertificateKey(key interface{}) *MockIkniteInitData_SetCertificateKey_Call {
	return &MockIkniteInitData_SetCertificateKey_Call{Call: _e.mock.On("SetCertificateKey", key)}
}

func (_c *MockIkniteInitData_SetCertificateKey_Call) Run(run func(key string)) *MockIkniteInitData_SetCertificateKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIkniteInitData_SetCertificateKey_Call) Return() *MockIkniteInitData_SetCertificateKey_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockIkniteInitData_SetCertificateKey_Call) RunAndReturn(run func(key string)) *MockIkniteInitData_SetCertificateKey_Call {
	_c.Run(run)
	return _c
}

// SetKubeletProcess provides a mock function for the type MockIkniteInitData
func (_mock *MockIkniteInitData) SetKubeletProcess(process host.Process) {
	_mock.Called(process)
	return
}

// MockIkniteInitData_SetKubeletProcess_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetKubeletProcess'
type MockIkniteInitData_SetKubeletProcess_Call struct {
	*mock.Call
}

// SetKubeletProcess is a helper method to define mock.On call
//   - process host.Process
func (_e *MockIkniteInitData_Expecter) SetKubeletProcess(process interface{}) *MockIkniteInitData_SetKubeletProcess_Call {
	return &MockIkniteInitData_SetKubeletProcess_Call{Call: _e.mock.On("SetKubeletProcess", process)}
}

func (_c *MockIkniteInitData_SetKubeletProcess_Call) Run(run func(process host.Process)) *MockIkniteInitData_SetKubeletProcess_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 host.Process
		if args[0] != nil {
			arg0 = args[0].(host.Process)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIkniteInitData_SetKubeletProcess_Call) Return() *MockIkniteInitData_SetKubeletProcess_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockIkniteInitData_SetKubeletProcess_Call) RunAndReturn(run func(process host.Process)) *MockIkniteInitData_SetKubeletProcess_Call {
	_c.Run(run)
	return _c
}

// SetMDnsConn provides a mock function for the type MockIkniteInitData
func (_mock *MockIkniteInitData) SetMDnsConn(conn *mdns.Conn) {
	_mock.Called(conn)
	return
}

// MockIkniteInitData_SetMDnsConn_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetMDnsConn'
type MockIkniteInitData_SetMDnsConn_Call struct {
	*mock.Call
}

// SetMDnsConn is a helper method to define mock.On call
//   - conn *mdns.Conn
func (_e *MockIkniteInitData_Expecter) SetMDnsConn(conn interface{}) *MockIkniteInitData_SetMDnsConn_Call {
	return &MockIkniteInitData_SetMDnsConn_Call{Call: _e.mock.On("SetMDnsConn", conn)}
}

func (_c *MockIkniteInitData_SetMDnsConn_Call) Run(run func(conn *mdns.Conn)) *MockIkniteInitData_SetMDnsConn_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *mdns.Conn
		if args[0] != nil {
			arg0 = args[0].(*mdns.Conn)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIkniteInitData_SetMDnsConn_Call) Return() *MockIkniteInitData_SetMDnsConn_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockIkniteInitData_SetMDnsConn_Call) RunAndReturn(run func(conn *mdns.Conn)) *MockIkniteInitData_SetMDnsConn_Call {
	_c.Run(run)
	return _c
}

// SetStatusServer provides a mock function for the type MockIkniteInitData
func (_mock *MockIkniteInitData) SetStatusServer(srv *server.IkniteServer) {
	_mock.Called(srv)
	return
}

// MockIkniteInitData_SetStatusServer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetStatusServer'
type MockIkniteInitData_SetStatusServer_Call struct {
	*mock.Call
}

// SetStatusServer is a helper method to define mock.On call
//   - srv *server.IkniteServer
func (_e *MockIkniteInitData_Expecter) SetStatusServer(srv interface{}) *MockIkniteInitData_SetStatusServer_Call {
	return &MockIkniteInitData_SetStatusServer_Call{Call: _e.mock.On("SetStatusServer", srv)}
}

func (_c *MockIkniteInitData_SetStatusServer_Call) Run(run func(srv *server.IkniteServer)) *MockIkniteInitData_SetStatusServer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *server.IkniteServer
		if args[0] != nil {
			arg0 = args[0].(*server.IkniteServer)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIkniteInitData_SetStatusServer_Call) Return() *MockIkniteInitData_SetStatusServer_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockIkniteInitData_SetStatusServer_Call) RunAndReturn(run func(srv *server.IkniteServer)) *MockIkniteInitData_SetStatusServer_Call {
	_c.Run(run)
	return _c
}

// SkipCertificateKeyPrint provides a mock function for the type MockIkniteInitData
func (_mock *MockIkniteInitData) SkipCertificateKeyPrint() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for SkipCertificateKeyPrint")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockIkniteInitData_SkipCertificateKeyPrint_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SkipCertificateKeyPrint'
type MockIkniteInitData_SkipCertificateKeyPrint_Call struct {
	*mock.Call
}

// SkipCertificateKeyPrint is a helper method to define mock.On call
func (_e *MockIkniteInitData_Expecter) SkipCertificateKeyPrint() *MockIkniteInitData_SkipCertificateKeyPrint_Call {
	return &MockIkniteInitData_SkipCertificateKeyPrint_Call{Call: _e.mock.On("SkipCertificateKeyPrint")}
}

func (_c *MockIkniteInitData_SkipCertificateKeyPrint_Call) Run(run func()) *MockIkniteInitData_SkipCertificateKeyPrint_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIkniteInitData_SkipCertificateKeyPrint_Call) Return(b bool) *MockIkniteInitData_SkipCertificateKeyPrint_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockIkniteInitData_SkipCertificateKeyPrint_Call) RunAndReturn(run func() bool) *MockIkniteInitData_SkipCertificateKeyPrint_Call {
	_c.Call.Return(run)
	return _c
}

// SkipTokenPrint provides a mock function for the type MockIkniteInitData
func (_mock *MockIkniteInitData) SkipTokenPrint() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for SkipTokenPrint")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockIkniteInitData_SkipTokenPrint_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SkipTokenPrint'
type MockIkniteInitData_SkipTokenPrint_Call struct {
	*mock.Call
}

// SkipTokenPrint is a helper method to define mock.On call
func (_e *MockIkniteInitData_Expecter) SkipTokenPrint() *MockIkniteInitData_SkipTokenPrint_Call {
	return &MockIkniteInitData_SkipTokenPrint_Call{Call: _e.mock.On("SkipTokenPrint")}
}

func (_c *MockIkniteInitData_SkipTokenPrint_Call) Run(run func()) *MockIkniteInitData_SkipTokenPrint_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIkniteInitData_SkipTokenPrint_Call) Return(b bool) *MockIkniteInitData_SkipTokenPrint_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockIkniteInitData_SkipTokenPrint_Call) RunAndReturn(run func() bool) *MockIkniteInitData_SkipTokenPrint_Call {
	_c.Call.Return(run)
	return _c
}

// StopStatusServer provides a mock function for the type MockIkniteInitData
func (_mock *MockIkniteInitData) StopStatusServer() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for StopStatusServer")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIkniteInitData_StopStatusServer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StopStatusServer'
type MockIkniteInitData_StopStatusServer_Call struct {
	*mock.Call
}

// StopStatusServer is a helper method to define mock.On call
func (_e *MockIkniteInitData_Expecter) StopStatusServer() *MockIkniteInitData_StopStatusServer_Call {
	return &MockIkniteInitData_StopStatusServer_Call{Call: _e.mock.On("StopStatusServer")}
}

func (_c *MockIkniteInitData_StopStatusServer_Call) Run(run func()) *MockIkniteInitData_StopStatusServer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIkniteInitData_StopStatusServer_Call) Return(err error) *MockIkniteInitData_StopStatusServer_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIkniteInitData_StopStatusServer_Call) RunAndReturn(run func() error) *MockIkniteInitData_StopStatusServer_Call {
	_c.Call.Return(run)
	return _c
}

// Tokens provides a mock function for the type MockIkniteInitData
func (_mock *MockIkniteInitData) Tokens() []string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Tokens")
	}

	var r0 []string
	if returnFunc, ok := ret.Get(0).(func() []string); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	return r0
}

// MockIkniteInitData_Tokens_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Tokens'
type MockIkniteInitData_Tokens_Call struct {
	*mock.Call
}

// Tokens is a helper method to define mock.On call
func (_e *MockIkniteInitData_Expecter) Tokens() *MockIkniteInitData_Tokens_Call {
	return &MockIkniteInitData_Tokens_Call{Call: _e.mock.On("Tokens")}
}

func (_c *MockIkniteInitData_Tokens_Call) Run(run func()) *MockIkniteInitData_Tokens_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIkniteInitData_Tokens_Call) Return(strings []string) *MockIkniteInitData_Tokens_Call {
	_c.Call.Return(strings)
	return _c
}

func (_c *MockIkniteInitData_Tokens_Call) RunAndReturn(run func() []string) *MockIkniteInitData_Tokens_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateIkniteCluster provides a mock function for the type MockIkniteInitData
func (_mock *MockIkniteInitData) UpdateIkniteCluster(state iknite.ClusterState, phase string, ready []*v1alpha1.WorkloadState, unready []*v1alpha1.WorkloadState) {
	_mock.Called(state, phase, ready, unready)
	return
}

// MockIkniteInitData_UpdateIkniteCluster_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateIkniteCluster'
type MockIkniteInitData_UpdateIkniteCluster_Call struct {
	*mock.Call
}

// UpdateIkniteCluster is a helper method to define mock.On call
//   - state iknite.ClusterState
//   - phase string
//   - ready []*v1alpha1.WorkloadState
//   - unready []*v1alpha1.WorkloadState
func (_e *MockIkniteInitData_Expecter) UpdateIkniteCluster(state interface{}, phase interface{}, ready interface{}, unready interface{}) *MockIkniteInitData_UpdateIkniteCluster_Call {
	return &MockIkniteInitData_UpdateIkniteCluster_Call{Call: _e.mock.On("UpdateIkniteCluster", state, phase, ready, unready)}
}

func (_c *MockIkniteInitData_UpdateIkniteCluster_Call) Run(run func(state iknite.ClusterState, phase string, ready []*v1alpha1.WorkloadState, unready []*v1alpha1.WorkloadState)) *MockIkniteInitData_UpdateIkniteCluster_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 iknite.ClusterState
		if args[0] != nil {
			arg0 = args[0].(iknite.ClusterState)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []*v1alpha1.WorkloadState
		if args[2] != nil {
			arg2 = args[2].([]*v1alpha1.WorkloadState)
		}
		var arg3 []*v1alpha1.WorkloadState
		if args[3] != nil {
			arg3 = args[3].([]*v1alpha1.WorkloadState)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockIkniteInitData_UpdateIkniteCluster_Call) Return() *MockIkniteInitData_UpdateIkniteCluster_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockIkniteInitData_UpdateIkniteCluster_Call) RunAndReturn(run func(state iknite.ClusterState, phase string, ready []*v1alpha1.WorkloadState, unready []*v1alpha1.WorkloadState)) *MockIkniteInitData_UpdateIkniteCluster_Call {
	_c.Run(run)
	return _c
}

// UploadCerts provides a mock function for the type MockIkniteInitData
func (_mock *MockIkniteInitData) UploadCerts() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for UploadCerts")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockIkniteInitData_UploadCerts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UploadCerts'
type MockIkniteInitData_UploadCerts_Call struct {
	*mock.Call
}

// UploadCerts is a helper method to define mock.On call
func (_e *MockIkniteInitData_Expecter) UploadCerts() *MockIkniteInitData_UploadCerts_Call {
	return &MockIkniteInitData_UploadCerts_Call{Call: _e.mock.On("UploadCerts")}
}

func (_c *MockIkniteInitData_UploadCerts_Call) Run(run func()) *MockIkniteInitData_UploadCerts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIkniteInitData_UploadCerts_Call) Return(b bool) *MockIkniteInitData_UploadCerts_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockIkniteInitData_UploadCerts_Call) RunAndReturn(run func() bool) *MockIkniteInitData_UploadCerts_Call {
	_c.Call.Return(run)
	return _c
}

// WaitControlPlaneClient provides a mock function for the type MockIkniteInitData
func (_mock *MockIkniteInitData) WaitControlPlaneClient() (kubernetes.Interface, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for WaitControlPlaneClient")
	}

	var r0 kubernetes.Interface
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (kubernetes.Interface, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() kubernetes.Interface); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(kubernetes.Interface)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIkniteInitData_WaitControlPlaneClient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WaitControlPlaneClient'
type MockIkniteInitData_WaitControlPlaneClient_Call struct {
	*mock.Call
}

// WaitControlPlaneClient is a helper method to define mock.On call
func (_e *MockIkniteInitData_Expecter) WaitControlPlaneClient() *MockIkniteInitData_WaitControlPlaneClient_Call {
	return &MockIkniteInitData_WaitControlPlaneClient_Call{Call: _e.mock.On("WaitControlPlaneClient")}
}

func (_c *MockIkniteInitData_WaitControlPlaneClient_Call) Run(run func()) *MockIkniteInitData_WaitControlPlaneClient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIkniteInitData_WaitControlPlaneClient_Call) Return(interfaceParam kubernetes.Interface, err error) *MockIkniteInitData_WaitControlPlaneClient_Call {
	_c.Call.Return(interfaceParam, err)
	return _c
}

func (_c *MockIkniteInitData_WaitControlPlaneClient_Call) RunAndReturn(run func() (kubernetes.Interface, error)) *MockIkniteInitData_WaitControlPlaneClient_Call {
	_c.Call.Return(run)
	return _c
}
