// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package init

import (
	"context"

	"github.com/kaweezle/iknite/pkg/apis/iknite/v1alpha1"
	"github.com/kaweezle/iknite/pkg/host"
	"github.com/kaweezle/iknite/pkg/server"
	mock "github.com/stretchr/testify/mock"
)

// newMockmonitorData creates a new instance of mockmonitorData. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockmonitorData(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockmonitorData {
	mock := &mockmonitorData{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockmonitorData is an autogenerated mock type for the monitorData type
type mockmonitorData struct {
	mock.Mock
}

type mockmonitorData_Expecter struct {
	mock *mock.Mock
}

func (_m *mockmonitorData) EXPECT() *mockmonitorData_Expecter {
	return &mockmonitorData_Expecter{mock: &_m.Mock}
}

// Context provides a mock function for the type mockmonitorData
func (_mock *mockmonitorData) Context() context.Context {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Context")
	}

	var r0 context.Context
	if returnFunc, ok := ret.Get(0).(func() context.Context); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(context.Context)
		}
	}
	return r0
}

// mockmonitorData_Context_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Context'
type mockmonitorData_Context_Call struct {
	*mock.Call
}

// Context is a helper method to define mock.On call
func (_e *mockmonitorData_Expecter) Context() *mockmonitorData_Context_Call {
	return &mockmonitorData_Context_Call{Call: _e.mock.On("Context")}
}

func (_c *mockmonitorData_Context_Call) Run(run func()) *mockmonitorData_Context_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockmonitorData_Context_Call) Return(context1 context.Context) *mockmonitorData_Context_Call {
	_c.Call.Return(context1)
	return _c
}

func (_c *mockmonitorData_Context_Call) RunAndReturn(run func() context.Context) *mockmonitorData_Context_Call {
	_c.Call.Return(run)
	return _c
}

// Host provides a mock function for the type mockmonitorData
func (_mock *mockmonitorData) Host() host.Host {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Host")
	}

	var r0 host.Host
	if returnFunc, ok := ret.Get(0).(func() host.Host); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(host.Host)
		}
	}
	return r0
}

// mockmonitorData_Host_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Host'
type mockmonitorData_Host_Call struct {
	*mock.Call
}

// Host is a helper method to define mock.On call
func (_e *mockmonitorData_Expecter) Host() *mockmonitorData_Host_Call {
	return &mockmonitorData_Host_Call{Call: _e.mock.On("Host")}
}

func (_c *mockmonitorData_Host_Call) Run(run func()) *mockmonitorData_Host_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockmonitorData_Host_Call) Return(host1 host.Host) *mockmonitorData_Host_Call {
	_c.Call.Return(host1)
	return _c
}

func (_c *mockmonitorData_Host_Call) RunAndReturn(run func() host.Host) *mockmonitorData_Host_Call {
	_c.Call.Return(run)
	return _c
}

// IkniteCluster provides a mock function for the type mockmonitorData
func (_mock *mockmonitorData) IkniteCluster() *v1alpha1.IkniteCluster {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for IkniteCluster")
	}

	var r0 *v1alpha1.IkniteCluster
	if returnFunc, ok := ret.Get(0).(func() *v1alpha1.IkniteCluster); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1alpha1.IkniteCluster)
		}
	}
	return r0
}

// mockmonitorData_IkniteCluster_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IkniteCluster'
type mockmonitorData_IkniteCluster_Call struct {
	*mock.Call
}

// IkniteCluster is a helper method to define mock.On call
func (_e *mockmonitorData_Expecter) IkniteCluster() *mockmonitorData_IkniteCluster_Call {
	return &mockmonitorData_IkniteCluster_Call{Call: _e.mock.On("IkniteCluster")}
}

func (_c *mockmonitorData_IkniteCluster_Call) Run(run func()) *mockmonitorData_IkniteCluster_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockmonitorData_IkniteCluster_Call) Return(ikniteCluster *v1alpha1.IkniteCluster) *mockmonitorData_IkniteCluster_Call {
	_c.Call.Return(ikniteCluster)
	return _c
}

func (_c *mockmonitorData_IkniteCluster_Call) RunAndReturn(run func() *v1alpha1.IkniteCluster) *mockmonitorData_IkniteCluster_Call {
	_c.Call.Return(run)
	return _c
}

// StatusServer provides a mock function for the type mockmonitorData
func (_mock *mockmonitorData) StatusServer() *server.IkniteServer {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for StatusServer")
	}

	var r0 *server.IkniteServer
	if returnFunc, ok := ret.Get(0).(func() *server.IkniteServer); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*server.IkniteServer)
		}
	}
	return r0
}

// mockmonitorData_StatusServer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StatusServer'
type mockmonitorData_StatusServer_Call struct {
	*mock.Call
}

// StatusServer is a helper method to define mock.On call
func (_e *mockmonitorData_Expecter) StatusServer() *mockmonitorData_StatusServer_Call {
	return &mockmonitorData_StatusServer_Call{Call: _e.mock.On("StatusServer")}
}

func (_c *mockmonitorData_StatusServer_Call) Run(run func()) *mockmonitorData_StatusServer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockmonitorData_StatusServer_Call) Return(ikniteServer *server.IkniteServer) *mockmonitorData_StatusServer_Call {
	_c.Call.Return(ikniteServer)
	return _c
}

func (_c *mockmonitorData_StatusServer_Call) RunAndReturn(run func() *server.IkniteServer) *mockmonitorData_StatusServer_Call {
	_c.Call.Return(run)
	return _c
}
