// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package init

import (
	"context"

	"github.com/kaweezle/iknite/pkg/apis/iknite/v1alpha1"
	"github.com/kaweezle/iknite/pkg/host"
	mock "github.com/stretchr/testify/mock"
)

// newMockprepareHostData creates a new instance of mockprepareHostData. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockprepareHostData(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockprepareHostData {
	mock := &mockprepareHostData{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockprepareHostData is an autogenerated mock type for the prepareHostData type
type mockprepareHostData struct {
	mock.Mock
}

type mockprepareHostData_Expecter struct {
	mock *mock.Mock
}

func (_m *mockprepareHostData) EXPECT() *mockprepareHostData_Expecter {
	return &mockprepareHostData_Expecter{mock: &_m.Mock}
}

// Context provides a mock function for the type mockprepareHostData
func (_mock *mockprepareHostData) Context() context.Context {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Context")
	}

	var r0 context.Context
	if returnFunc, ok := ret.Get(0).(func() context.Context); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(context.Context)
		}
	}
	return r0
}

// mockprepareHostData_Context_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Context'
type mockprepareHostData_Context_Call struct {
	*mock.Call
}

// Context is a helper method to define mock.On call
func (_e *mockprepareHostData_Expecter) Context() *mockprepareHostData_Context_Call {
	return &mockprepareHostData_Context_Call{Call: _e.mock.On("Context")}
}

func (_c *mockprepareHostData_Context_Call) Run(run func()) *mockprepareHostData_Context_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockprepareHostData_Context_Call) Return(context1 context.Context) *mockprepareHostData_Context_Call {
	_c.Call.Return(context1)
	return _c
}

func (_c *mockprepareHostData_Context_Call) RunAndReturn(run func() context.Context) *mockprepareHostData_Context_Call {
	_c.Call.Return(run)
	return _c
}

// Host provides a mock function for the type mockprepareHostData
func (_mock *mockprepareHostData) Host() host.Host {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Host")
	}

	var r0 host.Host
	if returnFunc, ok := ret.Get(0).(func() host.Host); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(host.Host)
		}
	}
	return r0
}

// mockprepareHostData_Host_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Host'
type mockprepareHostData_Host_Call struct {
	*mock.Call
}

// Host is a helper method to define mock.On call
func (_e *mockprepareHostData_Expecter) Host() *mockprepareHostData_Host_Call {
	return &mockprepareHostData_Host_Call{Call: _e.mock.On("Host")}
}

func (_c *mockprepareHostData_Host_Call) Run(run func()) *mockprepareHostData_Host_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockprepareHostData_Host_Call) Return(host1 host.Host) *mockprepareHostData_Host_Call {
	_c.Call.Return(host1)
	return _c
}

func (_c *mockprepareHostData_Host_Call) RunAndReturn(run func() host.Host) *mockprepareHostData_Host_Call {
	_c.Call.Return(run)
	return _c
}

// IkniteCluster provides a mock function for the type mockprepareHostData
func (_mock *mockprepareHostData) IkniteCluster() *v1alpha1.IkniteCluster {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for IkniteCluster")
	}

	var r0 *v1alpha1.IkniteCluster
	if returnFunc, ok := ret.Get(0).(func() *v1alpha1.IkniteCluster); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1alpha1.IkniteCluster)
		}
	}
	return r0
}

// mockprepareHostData_IkniteCluster_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IkniteCluster'
type mockprepareHostData_IkniteCluster_Call struct {
	*mock.Call
}

// IkniteCluster is a helper method to define mock.On call
func (_e *mockprepareHostData_Expecter) IkniteCluster() *mockprepareHostData_IkniteCluster_Call {
	return &mockprepareHostData_IkniteCluster_Call{Call: _e.mock.On("IkniteCluster")}
}

func (_c *mockprepareHostData_IkniteCluster_Call) Run(run func()) *mockprepareHostData_IkniteCluster_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockprepareHostData_IkniteCluster_Call) Return(ikniteCluster *v1alpha1.IkniteCluster) *mockprepareHostData_IkniteCluster_Call {
	_c.Call.Return(ikniteCluster)
	return _c
}

func (_c *mockprepareHostData_IkniteCluster_Call) RunAndReturn(run func() *v1alpha1.IkniteCluster) *mockprepareHostData_IkniteCluster_Call {
	_c.Call.Return(run)
	return _c
}
