// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package init

import (
	"github.com/kaweezle/iknite/pkg/apis/iknite/v1alpha1"
	"github.com/kaweezle/iknite/pkg/host"
	"github.com/kaweezle/iknite/pkg/server"
	mock "github.com/stretchr/testify/mock"
)

// NewMockServerData creates a new instance of MockServerData. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockServerData(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockServerData {
	mock := &MockServerData{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockServerData is an autogenerated mock type for the serverData type
type MockServerData struct {
	mock.Mock
}

type MockServerData_Expecter struct {
	mock *mock.Mock
}

func (_m *MockServerData) EXPECT() *MockServerData_Expecter {
	return &MockServerData_Expecter{mock: &_m.Mock}
}

// Host provides a mock function for the type MockServerData
func (_mock *MockServerData) Host() host.Host {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Host")
	}

	var r0 host.Host
	if returnFunc, ok := ret.Get(0).(func() host.Host); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(host.Host)
		}
	}
	return r0
}

// MockServerData_Host_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Host'
type MockServerData_Host_Call struct {
	*mock.Call
}

// Host is a helper method to define mock.On call
func (_e *MockServerData_Expecter) Host() *MockServerData_Host_Call {
	return &MockServerData_Host_Call{Call: _e.mock.On("Host")}
}

func (_c *MockServerData_Host_Call) Run(run func()) *MockServerData_Host_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockServerData_Host_Call) Return(host1 host.Host) *MockServerData_Host_Call {
	_c.Call.Return(host1)
	return _c
}

func (_c *MockServerData_Host_Call) RunAndReturn(run func() host.Host) *MockServerData_Host_Call {
	_c.Call.Return(run)
	return _c
}

// IkniteCluster provides a mock function for the type MockServerData
func (_mock *MockServerData) IkniteCluster() *v1alpha1.IkniteCluster {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for IkniteCluster")
	}

	var r0 *v1alpha1.IkniteCluster
	if returnFunc, ok := ret.Get(0).(func() *v1alpha1.IkniteCluster); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1alpha1.IkniteCluster)
		}
	}
	return r0
}

// MockServerData_IkniteCluster_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IkniteCluster'
type MockServerData_IkniteCluster_Call struct {
	*mock.Call
}

// IkniteCluster is a helper method to define mock.On call
func (_e *MockServerData_Expecter) IkniteCluster() *MockServerData_IkniteCluster_Call {
	return &MockServerData_IkniteCluster_Call{Call: _e.mock.On("IkniteCluster")}
}

func (_c *MockServerData_IkniteCluster_Call) Run(run func()) *MockServerData_IkniteCluster_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockServerData_IkniteCluster_Call) Return(ikniteCluster *v1alpha1.IkniteCluster) *MockServerData_IkniteCluster_Call {
	_c.Call.Return(ikniteCluster)
	return _c
}

func (_c *MockServerData_IkniteCluster_Call) RunAndReturn(run func() *v1alpha1.IkniteCluster) *MockServerData_IkniteCluster_Call {
	_c.Call.Return(run)
	return _c
}

// SetStatusServer provides a mock function for the type MockServerData
func (_mock *MockServerData) SetStatusServer(srv *server.IkniteServer) {
	_mock.Called(srv)
	return
}

// MockServerData_SetStatusServer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetStatusServer'
type MockServerData_SetStatusServer_Call struct {
	*mock.Call
}

// SetStatusServer is a helper method to define mock.On call
//   - srv *server.IkniteServer
func (_e *MockServerData_Expecter) SetStatusServer(srv interface{}) *MockServerData_SetStatusServer_Call {
	return &MockServerData_SetStatusServer_Call{Call: _e.mock.On("SetStatusServer", srv)}
}

func (_c *MockServerData_SetStatusServer_Call) Run(run func(srv *server.IkniteServer)) *MockServerData_SetStatusServer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *server.IkniteServer
		if args[0] != nil {
			arg0 = args[0].(*server.IkniteServer)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockServerData_SetStatusServer_Call) Return() *MockServerData_SetStatusServer_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockServerData_SetStatusServer_Call) RunAndReturn(run func(srv *server.IkniteServer)) *MockServerData_SetStatusServer_Call {
	_c.Run(run)
	return _c
}
