// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package host

import (
	"os"
	"path/filepath"

	"github.com/bitfield/script"
	"github.com/spf13/afero"
	mock "github.com/stretchr/testify/mock"
)

// NewMockFileEnvironment creates a new instance of MockFileEnvironment. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFileEnvironment(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFileEnvironment {
	mock := &MockFileEnvironment{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockFileEnvironment is an autogenerated mock type for the FileEnvironment type
type MockFileEnvironment struct {
	mock.Mock
}

type MockFileEnvironment_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFileEnvironment) EXPECT() *MockFileEnvironment_Expecter {
	return &MockFileEnvironment_Expecter{mock: &_m.Mock}
}

// Abs provides a mock function for the type MockFileEnvironment
func (_mock *MockFileEnvironment) Abs(path string) (string, error) {
	ret := _mock.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for Abs")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (string, error)); ok {
		return returnFunc(path)
	}
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(path)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(path)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFileEnvironment_Abs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Abs'
type MockFileEnvironment_Abs_Call struct {
	*mock.Call
}

// Abs is a helper method to define mock.On call
//   - path string
func (_e *MockFileEnvironment_Expecter) Abs(path interface{}) *MockFileEnvironment_Abs_Call {
	return &MockFileEnvironment_Abs_Call{Call: _e.mock.On("Abs", path)}
}

func (_c *MockFileEnvironment_Abs_Call) Run(run func(path string)) *MockFileEnvironment_Abs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockFileEnvironment_Abs_Call) Return(s string, err error) *MockFileEnvironment_Abs_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockFileEnvironment_Abs_Call) RunAndReturn(run func(path string) (string, error)) *MockFileEnvironment_Abs_Call {
	_c.Call.Return(run)
	return _c
}

// Chmod provides a mock function for the type MockFileEnvironment
func (_mock *MockFileEnvironment) Chmod(path string, mode os.FileMode) error {
	ret := _mock.Called(path, mode)

	if len(ret) == 0 {
		panic("no return value specified for Chmod")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, os.FileMode) error); ok {
		r0 = returnFunc(path, mode)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockFileEnvironment_Chmod_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Chmod'
type MockFileEnvironment_Chmod_Call struct {
	*mock.Call
}

// Chmod is a helper method to define mock.On call
//   - path string
//   - mode os.FileMode
func (_e *MockFileEnvironment_Expecter) Chmod(path interface{}, mode interface{}) *MockFileEnvironment_Chmod_Call {
	return &MockFileEnvironment_Chmod_Call{Call: _e.mock.On("Chmod", path, mode)}
}

func (_c *MockFileEnvironment_Chmod_Call) Run(run func(path string, mode os.FileMode)) *MockFileEnvironment_Chmod_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 os.FileMode
		if args[1] != nil {
			arg1 = args[1].(os.FileMode)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFileEnvironment_Chmod_Call) Return(err error) *MockFileEnvironment_Chmod_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockFileEnvironment_Chmod_Call) RunAndReturn(run func(path string, mode os.FileMode) error) *MockFileEnvironment_Chmod_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type MockFileEnvironment
func (_mock *MockFileEnvironment) Create(path string) (afero.File, error) {
	ret := _mock.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 afero.File
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (afero.File, error)); ok {
		return returnFunc(path)
	}
	if returnFunc, ok := ret.Get(0).(func(string) afero.File); ok {
		r0 = returnFunc(path)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(afero.File)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(path)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFileEnvironment_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockFileEnvironment_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - path string
func (_e *MockFileEnvironment_Expecter) Create(path interface{}) *MockFileEnvironment_Create_Call {
	return &MockFileEnvironment_Create_Call{Call: _e.mock.On("Create", path)}
}

func (_c *MockFileEnvironment_Create_Call) Run(run func(path string)) *MockFileEnvironment_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockFileEnvironment_Create_Call) Return(file afero.File, err error) *MockFileEnvironment_Create_Call {
	_c.Call.Return(file, err)
	return _c
}

func (_c *MockFileEnvironment_Create_Call) RunAndReturn(run func(path string) (afero.File, error)) *MockFileEnvironment_Create_Call {
	_c.Call.Return(run)
	return _c
}

// DirExists provides a mock function for the type MockFileEnvironment
func (_mock *MockFileEnvironment) DirExists(path string) (bool, error) {
	ret := _mock.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for DirExists")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (bool, error)); ok {
		return returnFunc(path)
	}
	if returnFunc, ok := ret.Get(0).(func(string) bool); ok {
		r0 = returnFunc(path)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(path)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFileEnvironment_DirExists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DirExists'
type MockFileEnvironment_DirExists_Call struct {
	*mock.Call
}

// DirExists is a helper method to define mock.On call
//   - path string
func (_e *MockFileEnvironment_Expecter) DirExists(path interface{}) *MockFileEnvironment_DirExists_Call {
	return &MockFileEnvironment_DirExists_Call{Call: _e.mock.On("DirExists", path)}
}

func (_c *MockFileEnvironment_DirExists_Call) Run(run func(path string)) *MockFileEnvironment_DirExists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockFileEnvironment_DirExists_Call) Return(b bool, err error) *MockFileEnvironment_DirExists_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockFileEnvironment_DirExists_Call) RunAndReturn(run func(path string) (bool, error)) *MockFileEnvironment_DirExists_Call {
	_c.Call.Return(run)
	return _c
}

// EvalSymlinks provides a mock function for the type MockFileEnvironment
func (_mock *MockFileEnvironment) EvalSymlinks(path string) (string, error) {
	ret := _mock.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for EvalSymlinks")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (string, error)); ok {
		return returnFunc(path)
	}
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(path)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(path)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFileEnvironment_EvalSymlinks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EvalSymlinks'
type MockFileEnvironment_EvalSymlinks_Call struct {
	*mock.Call
}

// EvalSymlinks is a helper method to define mock.On call
//   - path string
func (_e *MockFileEnvironment_Expecter) EvalSymlinks(path interface{}) *MockFileEnvironment_EvalSymlinks_Call {
	return &MockFileEnvironment_EvalSymlinks_Call{Call: _e.mock.On("EvalSymlinks", path)}
}

func (_c *MockFileEnvironment_EvalSymlinks_Call) Run(run func(path string)) *MockFileEnvironment_EvalSymlinks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockFileEnvironment_EvalSymlinks_Call) Return(s string, err error) *MockFileEnvironment_EvalSymlinks_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockFileEnvironment_EvalSymlinks_Call) RunAndReturn(run func(path string) (string, error)) *MockFileEnvironment_EvalSymlinks_Call {
	_c.Call.Return(run)
	return _c
}

// Exists provides a mock function for the type MockFileEnvironment
func (_mock *MockFileEnvironment) Exists(path string) (bool, error) {
	ret := _mock.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for Exists")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (bool, error)); ok {
		return returnFunc(path)
	}
	if returnFunc, ok := ret.Get(0).(func(string) bool); ok {
		r0 = returnFunc(path)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(path)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFileEnvironment_Exists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exists'
type MockFileEnvironment_Exists_Call struct {
	*mock.Call
}

// Exists is a helper method to define mock.On call
//   - path string
func (_e *MockFileEnvironment_Expecter) Exists(path interface{}) *MockFileEnvironment_Exists_Call {
	return &MockFileEnvironment_Exists_Call{Call: _e.mock.On("Exists", path)}
}

func (_c *MockFileEnvironment_Exists_Call) Run(run func(path string)) *MockFileEnvironment_Exists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockFileEnvironment_Exists_Call) Return(b bool, err error) *MockFileEnvironment_Exists_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockFileEnvironment_Exists_Call) RunAndReturn(run func(path string) (bool, error)) *MockFileEnvironment_Exists_Call {
	_c.Call.Return(run)
	return _c
}

// GOOS provides a mock function for the type MockFileEnvironment
func (_mock *MockFileEnvironment) GOOS() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GOOS")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockFileEnvironment_GOOS_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GOOS'
type MockFileEnvironment_GOOS_Call struct {
	*mock.Call
}

// GOOS is a helper method to define mock.On call
func (_e *MockFileEnvironment_Expecter) GOOS() *MockFileEnvironment_GOOS_Call {
	return &MockFileEnvironment_GOOS_Call{Call: _e.mock.On("GOOS")}
}

func (_c *MockFileEnvironment_GOOS_Call) Run(run func()) *MockFileEnvironment_GOOS_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockFileEnvironment_GOOS_Call) Return(s string) *MockFileEnvironment_GOOS_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockFileEnvironment_GOOS_Call) RunAndReturn(run func() string) *MockFileEnvironment_GOOS_Call {
	_c.Call.Return(run)
	return _c
}

// Getenv provides a mock function for the type MockFileEnvironment
func (_mock *MockFileEnvironment) Getenv(key string) string {
	ret := _mock.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for Getenv")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(key)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockFileEnvironment_Getenv_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Getenv'
type MockFileEnvironment_Getenv_Call struct {
	*mock.Call
}

// Getenv is a helper method to define mock.On call
//   - key string
func (_e *MockFileEnvironment_Expecter) Getenv(key interface{}) *MockFileEnvironment_Getenv_Call {
	return &MockFileEnvironment_Getenv_Call{Call: _e.mock.On("Getenv", key)}
}

func (_c *MockFileEnvironment_Getenv_Call) Run(run func(key string)) *MockFileEnvironment_Getenv_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockFileEnvironment_Getenv_Call) Return(s string) *MockFileEnvironment_Getenv_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockFileEnvironment_Getenv_Call) RunAndReturn(run func(key string) string) *MockFileEnvironment_Getenv_Call {
	_c.Call.Return(run)
	return _c
}

// Glob provides a mock function for the type MockFileEnvironment
func (_mock *MockFileEnvironment) Glob(pattern string) ([]string, error) {
	ret := _mock.Called(pattern)

	if len(ret) == 0 {
		panic("no return value specified for Glob")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) ([]string, error)); ok {
		return returnFunc(pattern)
	}
	if returnFunc, ok := ret.Get(0).(func(string) []string); ok {
		r0 = returnFunc(pattern)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(pattern)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFileEnvironment_Glob_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Glob'
type MockFileEnvironment_Glob_Call struct {
	*mock.Call
}

// Glob is a helper method to define mock.On call
//   - pattern string
func (_e *MockFileEnvironment_Expecter) Glob(pattern interface{}) *MockFileEnvironment_Glob_Call {
	return &MockFileEnvironment_Glob_Call{Call: _e.mock.On("Glob", pattern)}
}

func (_c *MockFileEnvironment_Glob_Call) Run(run func(pattern string)) *MockFileEnvironment_Glob_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockFileEnvironment_Glob_Call) Return(matches []string, err error) *MockFileEnvironment_Glob_Call {
	_c.Call.Return(matches, err)
	return _c
}

func (_c *MockFileEnvironment_Glob_Call) RunAndReturn(run func(pattern string) ([]string, error)) *MockFileEnvironment_Glob_Call {
	_c.Call.Return(run)
	return _c
}

// JoinPath provides a mock function for the type MockFileEnvironment
func (_mock *MockFileEnvironment) JoinPath(elem ...string) string {
	var tmpRet mock.Arguments
	if len(elem) > 0 {
		tmpRet = _mock.Called(elem)
	} else {
		tmpRet = _mock.Called()
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for JoinPath")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func(...string) string); ok {
		r0 = returnFunc(elem...)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockFileEnvironment_JoinPath_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'JoinPath'
type MockFileEnvironment_JoinPath_Call struct {
	*mock.Call
}

// JoinPath is a helper method to define mock.On call
//   - elem ...string
func (_e *MockFileEnvironment_Expecter) JoinPath(elem ...interface{}) *MockFileEnvironment_JoinPath_Call {
	return &MockFileEnvironment_JoinPath_Call{Call: _e.mock.On("JoinPath",
		append([]interface{}{}, elem...)...)}
}

func (_c *MockFileEnvironment_JoinPath_Call) Run(run func(elem ...string)) *MockFileEnvironment_JoinPath_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []string
		var variadicArgs []string
		if len(args) > 0 {
			variadicArgs = args[0].([]string)
		}
		arg0 = variadicArgs
		run(
			arg0...,
		)
	})
	return _c
}

func (_c *MockFileEnvironment_JoinPath_Call) Return(s string) *MockFileEnvironment_JoinPath_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockFileEnvironment_JoinPath_Call) RunAndReturn(run func(elem ...string) string) *MockFileEnvironment_JoinPath_Call {
	_c.Call.Return(run)
	return _c
}

// LookupEnv provides a mock function for the type MockFileEnvironment
func (_mock *MockFileEnvironment) LookupEnv(key string) (string, bool) {
	ret := _mock.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for LookupEnv")
	}

	var r0 string
	var r1 bool
	if returnFunc, ok := ret.Get(0).(func(string) (string, bool)); ok {
		return returnFunc(key)
	}
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(key)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string) bool); ok {
		r1 = returnFunc(key)
	} else {
		r1 = ret.Get(1).(bool)
	}
	return r0, r1
}

// MockFileEnvironment_LookupEnv_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LookupEnv'
type MockFileEnvironment_LookupEnv_Call struct {
	*mock.Call
}

// LookupEnv is a helper method to define mock.On call
//   - key string
func (_e *MockFileEnvironment_Expecter) LookupEnv(key interface{}) *MockFileEnvironment_LookupEnv_Call {
	return &MockFileEnvironment_LookupEnv_Call{Call: _e.mock.On("LookupEnv", key)}
}

func (_c *MockFileEnvironment_LookupEnv_Call) Run(run func(key string)) *MockFileEnvironment_LookupEnv_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockFileEnvironment_LookupEnv_Call) Return(s string, b bool) *MockFileEnvironment_LookupEnv_Call {
	_c.Call.Return(s, b)
	return _c
}

func (_c *MockFileEnvironment_LookupEnv_Call) RunAndReturn(run func(key string) (string, bool)) *MockFileEnvironment_LookupEnv_Call {
	_c.Call.Return(run)
	return _c
}

// MkdirAll provides a mock function for the type MockFileEnvironment
func (_mock *MockFileEnvironment) MkdirAll(path string, perm os.FileMode) error {
	ret := _mock.Called(path, perm)

	if len(ret) == 0 {
		panic("no return value specified for MkdirAll")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, os.FileMode) error); ok {
		r0 = returnFunc(path, perm)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockFileEnvironment_MkdirAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MkdirAll'
type MockFileEnvironment_MkdirAll_Call struct {
	*mock.Call
}

// MkdirAll is a helper method to define mock.On call
//   - path string
//   - perm os.FileMode
func (_e *MockFileEnvironment_Expecter) MkdirAll(path interface{}, perm interface{}) *MockFileEnvironment_MkdirAll_Call {
	return &MockFileEnvironment_MkdirAll_Call{Call: _e.mock.On("MkdirAll", path, perm)}
}

func (_c *MockFileEnvironment_MkdirAll_Call) Run(run func(path string, perm os.FileMode)) *MockFileEnvironment_MkdirAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 os.FileMode
		if args[1] != nil {
			arg1 = args[1].(os.FileMode)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFileEnvironment_MkdirAll_Call) Return(err error) *MockFileEnvironment_MkdirAll_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockFileEnvironment_MkdirAll_Call) RunAndReturn(run func(path string, perm os.FileMode) error) *MockFileEnvironment_MkdirAll_Call {
	_c.Call.Return(run)
	return _c
}

// Open provides a mock function for the type MockFileEnvironment
func (_mock *MockFileEnvironment) Open(path string) (afero.File, error) {
	ret := _mock.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for Open")
	}

	var r0 afero.File
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (afero.File, error)); ok {
		return returnFunc(path)
	}
	if returnFunc, ok := ret.Get(0).(func(string) afero.File); ok {
		r0 = returnFunc(path)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(afero.File)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(path)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFileEnvironment_Open_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Open'
type MockFileEnvironment_Open_Call struct {
	*mock.Call
}

// Open is a helper method to define mock.On call
//   - path string
func (_e *MockFileEnvironment_Expecter) Open(path interface{}) *MockFileEnvironment_Open_Call {
	return &MockFileEnvironment_Open_Call{Call: _e.mock.On("Open", path)}
}

func (_c *MockFileEnvironment_Open_Call) Run(run func(path string)) *MockFileEnvironment_Open_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockFileEnvironment_Open_Call) Return(file afero.File, err error) *MockFileEnvironment_Open_Call {
	_c.Call.Return(file, err)
	return _c
}

func (_c *MockFileEnvironment_Open_Call) RunAndReturn(run func(path string) (afero.File, error)) *MockFileEnvironment_Open_Call {
	_c.Call.Return(run)
	return _c
}

// OpenFile provides a mock function for the type MockFileEnvironment
func (_mock *MockFileEnvironment) OpenFile(path string, flag int, perm os.FileMode) (afero.File, error) {
	ret := _mock.Called(path, flag, perm)

	if len(ret) == 0 {
		panic("no return value specified for OpenFile")
	}

	var r0 afero.File
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, int, os.FileMode) (afero.File, error)); ok {
		return returnFunc(path, flag, perm)
	}
	if returnFunc, ok := ret.Get(0).(func(string, int, os.FileMode) afero.File); ok {
		r0 = returnFunc(path, flag, perm)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(afero.File)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, int, os.FileMode) error); ok {
		r1 = returnFunc(path, flag, perm)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFileEnvironment_OpenFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OpenFile'
type MockFileEnvironment_OpenFile_Call struct {
	*mock.Call
}

// OpenFile is a helper method to define mock.On call
//   - path string
//   - flag int
//   - perm os.FileMode
func (_e *MockFileEnvironment_Expecter) OpenFile(path interface{}, flag interface{}, perm interface{}) *MockFileEnvironment_OpenFile_Call {
	return &MockFileEnvironment_OpenFile_Call{Call: _e.mock.On("OpenFile", path, flag, perm)}
}

func (_c *MockFileEnvironment_OpenFile_Call) Run(run func(path string, flag int, perm os.FileMode)) *MockFileEnvironment_OpenFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 os.FileMode
		if args[2] != nil {
			arg2 = args[2].(os.FileMode)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockFileEnvironment_OpenFile_Call) Return(file afero.File, err error) *MockFileEnvironment_OpenFile_Call {
	_c.Call.Return(file, err)
	return _c
}

func (_c *MockFileEnvironment_OpenFile_Call) RunAndReturn(run func(path string, flag int, perm os.FileMode) (afero.File, error)) *MockFileEnvironment_OpenFile_Call {
	_c.Call.Return(run)
	return _c
}

// Pipe provides a mock function for the type MockFileEnvironment
func (_mock *MockFileEnvironment) Pipe(path string) *script.Pipe {
	ret := _mock.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for Pipe")
	}

	var r0 *script.Pipe
	if returnFunc, ok := ret.Get(0).(func(string) *script.Pipe); ok {
		r0 = returnFunc(path)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*script.Pipe)
		}
	}
	return r0
}

// MockFileEnvironment_Pipe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Pipe'
type MockFileEnvironment_Pipe_Call struct {
	*mock.Call
}

// Pipe is a helper method to define mock.On call
//   - path string
func (_e *MockFileEnvironment_Expecter) Pipe(path interface{}) *MockFileEnvironment_Pipe_Call {
	return &MockFileEnvironment_Pipe_Call{Call: _e.mock.On("Pipe", path)}
}

func (_c *MockFileEnvironment_Pipe_Call) Run(run func(path string)) *MockFileEnvironment_Pipe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockFileEnvironment_Pipe_Call) Return(pipe *script.Pipe) *MockFileEnvironment_Pipe_Call {
	_c.Call.Return(pipe)
	return _c
}

func (_c *MockFileEnvironment_Pipe_Call) RunAndReturn(run func(path string) *script.Pipe) *MockFileEnvironment_Pipe_Call {
	_c.Call.Return(run)
	return _c
}

// ReadDir provides a mock function for the type MockFileEnvironment
func (_mock *MockFileEnvironment) ReadDir(dirname string) ([]os.FileInfo, error) {
	ret := _mock.Called(dirname)

	if len(ret) == 0 {
		panic("no return value specified for ReadDir")
	}

	var r0 []os.FileInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) ([]os.FileInfo, error)); ok {
		return returnFunc(dirname)
	}
	if returnFunc, ok := ret.Get(0).(func(string) []os.FileInfo); ok {
		r0 = returnFunc(dirname)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]os.FileInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(dirname)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFileEnvironment_ReadDir_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadDir'
type MockFileEnvironment_ReadDir_Call struct {
	*mock.Call
}

// ReadDir is a helper method to define mock.On call
//   - dirname string
func (_e *MockFileEnvironment_Expecter) ReadDir(dirname interface{}) *MockFileEnvironment_ReadDir_Call {
	return &MockFileEnvironment_ReadDir_Call{Call: _e.mock.On("ReadDir", dirname)}
}

func (_c *MockFileEnvironment_ReadDir_Call) Run(run func(dirname string)) *MockFileEnvironment_ReadDir_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockFileEnvironment_ReadDir_Call) Return(vs []os.FileInfo, err error) *MockFileEnvironment_ReadDir_Call {
	_c.Call.Return(vs, err)
	return _c
}

func (_c *MockFileEnvironment_ReadDir_Call) RunAndReturn(run func(dirname string) ([]os.FileInfo, error)) *MockFileEnvironment_ReadDir_Call {
	_c.Call.Return(run)
	return _c
}

// ReadFile provides a mock function for the type MockFileEnvironment
func (_mock *MockFileEnvironment) ReadFile(path string) ([]byte, error) {
	ret := _mock.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for ReadFile")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) ([]byte, error)); ok {
		return returnFunc(path)
	}
	if returnFunc, ok := ret.Get(0).(func(string) []byte); ok {
		r0 = returnFunc(path)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(path)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFileEnvironment_ReadFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadFile'
type MockFileEnvironment_ReadFile_Call struct {
	*mock.Call
}

// ReadFile is a helper method to define mock.On call
//   - path string
func (_e *MockFileEnvironment_Expecter) ReadFile(path interface{}) *MockFileEnvironment_ReadFile_Call {
	return &MockFileEnvironment_ReadFile_Call{Call: _e.mock.On("ReadFile", path)}
}

func (_c *MockFileEnvironment_ReadFile_Call) Run(run func(path string)) *MockFileEnvironment_ReadFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockFileEnvironment_ReadFile_Call) Return(bytes []byte, err error) *MockFileEnvironment_ReadFile_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockFileEnvironment_ReadFile_Call) RunAndReturn(run func(path string) ([]byte, error)) *MockFileEnvironment_ReadFile_Call {
	_c.Call.Return(run)
	return _c
}

// Remove provides a mock function for the type MockFileEnvironment
func (_mock *MockFileEnvironment) Remove(path string) error {
	ret := _mock.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for Remove")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(path)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockFileEnvironment_Remove_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Remove'
type MockFileEnvironment_Remove_Call struct {
	*mock.Call
}

// Remove is a helper method to define mock.On call
//   - path string
func (_e *MockFileEnvironment_Expecter) Remove(path interface{}) *MockFileEnvironment_Remove_Call {
	return &MockFileEnvironment_Remove_Call{Call: _e.mock.On("Remove", path)}
}

func (_c *MockFileEnvironment_Remove_Call) Run(run func(path string)) *MockFileEnvironment_Remove_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockFileEnvironment_Remove_Call) Return(err error) *MockFileEnvironment_Remove_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockFileEnvironment_Remove_Call) RunAndReturn(run func(path string) error) *MockFileEnvironment_Remove_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveAll provides a mock function for the type MockFileEnvironment
func (_mock *MockFileEnvironment) RemoveAll(path string) error {
	ret := _mock.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for RemoveAll")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(path)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockFileEnvironment_RemoveAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveAll'
type MockFileEnvironment_RemoveAll_Call struct {
	*mock.Call
}

// RemoveAll is a helper method to define mock.On call
//   - path string
func (_e *MockFileEnvironment_Expecter) RemoveAll(path interface{}) *MockFileEnvironment_RemoveAll_Call {
	return &MockFileEnvironment_RemoveAll_Call{Call: _e.mock.On("RemoveAll", path)}
}

func (_c *MockFileEnvironment_RemoveAll_Call) Run(run func(path string)) *MockFileEnvironment_RemoveAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockFileEnvironment_RemoveAll_Call) Return(err error) *MockFileEnvironment_RemoveAll_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockFileEnvironment_RemoveAll_Call) RunAndReturn(run func(path string) error) *MockFileEnvironment_RemoveAll_Call {
	_c.Call.Return(run)
	return _c
}

// Rename provides a mock function for the type MockFileEnvironment
func (_mock *MockFileEnvironment) Rename(oldPath string, newPath string) error {
	ret := _mock.Called(oldPath, newPath)

	if len(ret) == 0 {
		panic("no return value specified for Rename")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = returnFunc(oldPath, newPath)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockFileEnvironment_Rename_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Rename'
type MockFileEnvironment_Rename_Call struct {
	*mock.Call
}

// Rename is a helper method to define mock.On call
//   - oldPath string
//   - newPath string
func (_e *MockFileEnvironment_Expecter) Rename(oldPath interface{}, newPath interface{}) *MockFileEnvironment_Rename_Call {
	return &MockFileEnvironment_Rename_Call{Call: _e.mock.On("Rename", oldPath, newPath)}
}

func (_c *MockFileEnvironment_Rename_Call) Run(run func(oldPath string, newPath string)) *MockFileEnvironment_Rename_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFileEnvironment_Rename_Call) Return(err error) *MockFileEnvironment_Rename_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockFileEnvironment_Rename_Call) RunAndReturn(run func(oldPath string, newPath string) error) *MockFileEnvironment_Rename_Call {
	_c.Call.Return(run)
	return _c
}

// Setenv provides a mock function for the type MockFileEnvironment
func (_mock *MockFileEnvironment) Setenv(key string, value string) error {
	ret := _mock.Called(key, value)

	if len(ret) == 0 {
		panic("no return value specified for Setenv")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = returnFunc(key, value)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockFileEnvironment_Setenv_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Setenv'
type MockFileEnvironment_Setenv_Call struct {
	*mock.Call
}

// Setenv is a helper method to define mock.On call
//   - key string
//   - value string
func (_e *MockFileEnvironment_Expecter) Setenv(key interface{}, value interface{}) *MockFileEnvironment_Setenv_Call {
	return &MockFileEnvironment_Setenv_Call{Call: _e.mock.On("Setenv", key, value)}
}

func (_c *MockFileEnvironment_Setenv_Call) Run(run func(key string, value string)) *MockFileEnvironment_Setenv_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFileEnvironment_Setenv_Call) Return(err error) *MockFileEnvironment_Setenv_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockFileEnvironment_Setenv_Call) RunAndReturn(run func(key string, value string) error) *MockFileEnvironment_Setenv_Call {
	_c.Call.Return(run)
	return _c
}

// Stat provides a mock function for the type MockFileEnvironment
func (_mock *MockFileEnvironment) Stat(path string) (os.FileInfo, error) {
	ret := _mock.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for Stat")
	}

	var r0 os.FileInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (os.FileInfo, error)); ok {
		return returnFunc(path)
	}
	if returnFunc, ok := ret.Get(0).(func(string) os.FileInfo); ok {
		r0 = returnFunc(path)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(os.FileInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(path)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFileEnvironment_Stat_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stat'
type MockFileEnvironment_Stat_Call struct {
	*mock.Call
}

// Stat is a helper method to define mock.On call
//   - path string
func (_e *MockFileEnvironment_Expecter) Stat(path interface{}) *MockFileEnvironment_Stat_Call {
	return &MockFileEnvironment_Stat_Call{Call: _e.mock.On("Stat", path)}
}

func (_c *MockFileEnvironment_Stat_Call) Run(run func(path string)) *MockFileEnvironment_Stat_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockFileEnvironment_Stat_Call) Return(v os.FileInfo, err error) *MockFileEnvironment_Stat_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockFileEnvironment_Stat_Call) RunAndReturn(run func(path string) (os.FileInfo, error)) *MockFileEnvironment_Stat_Call {
	_c.Call.Return(run)
	return _c
}

// Symlink provides a mock function for the type MockFileEnvironment
func (_mock *MockFileEnvironment) Symlink(oldName string, newName string) error {
	ret := _mock.Called(oldName, newName)

	if len(ret) == 0 {
		panic("no return value specified for Symlink")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = returnFunc(oldName, newName)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockFileEnvironment_Symlink_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Symlink'
type MockFileEnvironment_Symlink_Call struct {
	*mock.Call
}

// Symlink is a helper method to define mock.On call
//   - oldName string
//   - newName string
func (_e *MockFileEnvironment_Expecter) Symlink(oldName interface{}, newName interface{}) *MockFileEnvironment_Symlink_Call {
	return &MockFileEnvironment_Symlink_Call{Call: _e.mock.On("Symlink", oldName, newName)}
}

func (_c *MockFileEnvironment_Symlink_Call) Run(run func(oldName string, newName string)) *MockFileEnvironment_Symlink_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFileEnvironment_Symlink_Call) Return(err error) *MockFileEnvironment_Symlink_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockFileEnvironment_Symlink_Call) RunAndReturn(run func(oldName string, newName string) error) *MockFileEnvironment_Symlink_Call {
	_c.Call.Return(run)
	return _c
}

// UserConfigDir provides a mock function for the type MockFileEnvironment
func (_mock *MockFileEnvironment) UserConfigDir() (string, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for UserConfigDir")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (string, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFileEnvironment_UserConfigDir_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UserConfigDir'
type MockFileEnvironment_UserConfigDir_Call struct {
	*mock.Call
}

// UserConfigDir is a helper method to define mock.On call
func (_e *MockFileEnvironment_Expecter) UserConfigDir() *MockFileEnvironment_UserConfigDir_Call {
	return &MockFileEnvironment_UserConfigDir_Call{Call: _e.mock.On("UserConfigDir")}
}

func (_c *MockFileEnvironment_UserConfigDir_Call) Run(run func()) *MockFileEnvironment_UserConfigDir_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockFileEnvironment_UserConfigDir_Call) Return(s string, err error) *MockFileEnvironment_UserConfigDir_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockFileEnvironment_UserConfigDir_Call) RunAndReturn(run func() (string, error)) *MockFileEnvironment_UserConfigDir_Call {
	_c.Call.Return(run)
	return _c
}

// UserHomeDir provides a mock function for the type MockFileEnvironment
func (_mock *MockFileEnvironment) UserHomeDir() (string, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for UserHomeDir")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (string, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFileEnvironment_UserHomeDir_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UserHomeDir'
type MockFileEnvironment_UserHomeDir_Call struct {
	*mock.Call
}

// UserHomeDir is a helper method to define mock.On call
func (_e *MockFileEnvironment_Expecter) UserHomeDir() *MockFileEnvironment_UserHomeDir_Call {
	return &MockFileEnvironment_UserHomeDir_Call{Call: _e.mock.On("UserHomeDir")}
}

func (_c *MockFileEnvironment_UserHomeDir_Call) Run(run func()) *MockFileEnvironment_UserHomeDir_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockFileEnvironment_UserHomeDir_Call) Return(s string, err error) *MockFileEnvironment_UserHomeDir_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockFileEnvironment_UserHomeDir_Call) RunAndReturn(run func() (string, error)) *MockFileEnvironment_UserHomeDir_Call {
	_c.Call.Return(run)
	return _c
}

// Walk provides a mock function for the type MockFileEnvironment
func (_mock *MockFileEnvironment) Walk(root string, walkFn filepath.WalkFunc) error {
	ret := _mock.Called(root, walkFn)

	if len(ret) == 0 {
		panic("no return value specified for Walk")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, filepath.WalkFunc) error); ok {
		r0 = returnFunc(root, walkFn)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockFileEnvironment_Walk_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Walk'
type MockFileEnvironment_Walk_Call struct {
	*mock.Call
}

// Walk is a helper method to define mock.On call
//   - root string
//   - walkFn filepath.WalkFunc
func (_e *MockFileEnvironment_Expecter) Walk(root interface{}, walkFn interface{}) *MockFileEnvironment_Walk_Call {
	return &MockFileEnvironment_Walk_Call{Call: _e.mock.On("Walk", root, walkFn)}
}

func (_c *MockFileEnvironment_Walk_Call) Run(run func(root string, walkFn filepath.WalkFunc)) *MockFileEnvironment_Walk_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 filepath.WalkFunc
		if args[1] != nil {
			arg1 = args[1].(filepath.WalkFunc)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFileEnvironment_Walk_Call) Return(err error) *MockFileEnvironment_Walk_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockFileEnvironment_Walk_Call) RunAndReturn(run func(root string, walkFn filepath.WalkFunc) error) *MockFileEnvironment_Walk_Call {
	_c.Call.Return(run)
	return _c
}

// WriteFile provides a mock function for the type MockFileEnvironment
func (_mock *MockFileEnvironment) WriteFile(path string, data []byte, perm os.FileMode) error {
	ret := _mock.Called(path, data, perm)

	if len(ret) == 0 {
		panic("no return value specified for WriteFile")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, []byte, os.FileMode) error); ok {
		r0 = returnFunc(path, data, perm)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockFileEnvironment_WriteFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WriteFile'
type MockFileEnvironment_WriteFile_Call struct {
	*mock.Call
}

// WriteFile is a helper method to define mock.On call
//   - path string
//   - data []byte
//   - perm os.FileMode
func (_e *MockFileEnvironment_Expecter) WriteFile(path interface{}, data interface{}, perm interface{}) *MockFileEnvironment_WriteFile_Call {
	return &MockFileEnvironment_WriteFile_Call{Call: _e.mock.On("WriteFile", path, data, perm)}
}

func (_c *MockFileEnvironment_WriteFile_Call) Run(run func(path string, data []byte, perm os.FileMode)) *MockFileEnvironment_WriteFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []byte
		if args[1] != nil {
			arg1 = args[1].([]byte)
		}
		var arg2 os.FileMode
		if args[2] != nil {
			arg2 = args[2].(os.FileMode)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockFileEnvironment_WriteFile_Call) Return(err error) *MockFileEnvironment_WriteFile_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockFileEnvironment_WriteFile_Call) RunAndReturn(run func(path string, data []byte, perm os.FileMode) error) *MockFileEnvironment_WriteFile_Call {
	_c.Call.Return(run)
	return _c
}

// WritePipe provides a mock function for the type MockFileEnvironment
func (_mock *MockFileEnvironment) WritePipe(path string, pipe *script.Pipe, flag int, perm os.FileMode) (int64, error) {
	ret := _mock.Called(path, pipe, flag, perm)

	if len(ret) == 0 {
		panic("no return value specified for WritePipe")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, *script.Pipe, int, os.FileMode) (int64, error)); ok {
		return returnFunc(path, pipe, flag, perm)
	}
	if returnFunc, ok := ret.Get(0).(func(string, *script.Pipe, int, os.FileMode) int64); ok {
		r0 = returnFunc(path, pipe, flag, perm)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(string, *script.Pipe, int, os.FileMode) error); ok {
		r1 = returnFunc(path, pipe, flag, perm)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFileEnvironment_WritePipe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WritePipe'
type MockFileEnvironment_WritePipe_Call struct {
	*mock.Call
}

// WritePipe is a helper method to define mock.On call
//   - path string
//   - pipe *script.Pipe
//   - flag int
//   - perm os.FileMode
func (_e *MockFileEnvironment_Expecter) WritePipe(path interface{}, pipe interface{}, flag interface{}, perm interface{}) *MockFileEnvironment_WritePipe_Call {
	return &MockFileEnvironment_WritePipe_Call{Call: _e.mock.On("WritePipe", path, pipe, flag, perm)}
}

func (_c *MockFileEnvironment_WritePipe_Call) Run(run func(path string, pipe *script.Pipe, flag int, perm os.FileMode)) *MockFileEnvironment_WritePipe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 *script.Pipe
		if args[1] != nil {
			arg1 = args[1].(*script.Pipe)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 os.FileMode
		if args[3] != nil {
			arg3 = args[3].(os.FileMode)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockFileEnvironment_WritePipe_Call) Return(n int64, err error) *MockFileEnvironment_WritePipe_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockFileEnvironment_WritePipe_Call) RunAndReturn(run func(path string, pipe *script.Pipe, flag int, perm os.FileMode) (int64, error)) *MockFileEnvironment_WritePipe_Call {
	_c.Call.Return(run)
	return _c
}
