// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package host

import (
	"context"
	"net"
	"time"

	mock "github.com/stretchr/testify/mock"
	"github.com/txn2/txeh"
)

// NewMockNetworkHost creates a new instance of MockNetworkHost. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockNetworkHost(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockNetworkHost {
	mock := &MockNetworkHost{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockNetworkHost is an autogenerated mock type for the NetworkHost type
type MockNetworkHost struct {
	mock.Mock
}

type MockNetworkHost_Expecter struct {
	mock *mock.Mock
}

func (_m *MockNetworkHost) EXPECT() *MockNetworkHost_Expecter {
	return &MockNetworkHost_Expecter{mock: &_m.Mock}
}

// CheckIpExists provides a mock function for the type MockNetworkHost
func (_mock *MockNetworkHost) CheckIpExists(ip net.IP) (bool, error) {
	ret := _mock.Called(ip)

	if len(ret) == 0 {
		panic("no return value specified for CheckIpExists")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(net.IP) (bool, error)); ok {
		return returnFunc(ip)
	}
	if returnFunc, ok := ret.Get(0).(func(net.IP) bool); ok {
		r0 = returnFunc(ip)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(net.IP) error); ok {
		r1 = returnFunc(ip)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockNetworkHost_CheckIpExists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckIpExists'
type MockNetworkHost_CheckIpExists_Call struct {
	*mock.Call
}

// CheckIpExists is a helper method to define mock.On call
//   - ip net.IP
func (_e *MockNetworkHost_Expecter) CheckIpExists(ip interface{}) *MockNetworkHost_CheckIpExists_Call {
	return &MockNetworkHost_CheckIpExists_Call{Call: _e.mock.On("CheckIpExists", ip)}
}

func (_c *MockNetworkHost_CheckIpExists_Call) Run(run func(ip net.IP)) *MockNetworkHost_CheckIpExists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 net.IP
		if args[0] != nil {
			arg0 = args[0].(net.IP)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockNetworkHost_CheckIpExists_Call) Return(b bool, err error) *MockNetworkHost_CheckIpExists_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockNetworkHost_CheckIpExists_Call) RunAndReturn(run func(ip net.IP) (bool, error)) *MockNetworkHost_CheckIpExists_Call {
	_c.Call.Return(run)
	return _c
}

// DialTimeout provides a mock function for the type MockNetworkHost
func (_mock *MockNetworkHost) DialTimeout(ctx context.Context, network string, address string, timeout time.Duration) (net.Conn, error) {
	ret := _mock.Called(ctx, network, address, timeout)

	if len(ret) == 0 {
		panic("no return value specified for DialTimeout")
	}

	var r0 net.Conn
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, time.Duration) (net.Conn, error)); ok {
		return returnFunc(ctx, network, address, timeout)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, time.Duration) net.Conn); ok {
		r0 = returnFunc(ctx, network, address, timeout)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(net.Conn)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, time.Duration) error); ok {
		r1 = returnFunc(ctx, network, address, timeout)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockNetworkHost_DialTimeout_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DialTimeout'
type MockNetworkHost_DialTimeout_Call struct {
	*mock.Call
}

// DialTimeout is a helper method to define mock.On call
//   - ctx context.Context
//   - network string
//   - address string
//   - timeout time.Duration
func (_e *MockNetworkHost_Expecter) DialTimeout(ctx interface{}, network interface{}, address interface{}, timeout interface{}) *MockNetworkHost_DialTimeout_Call {
	return &MockNetworkHost_DialTimeout_Call{Call: _e.mock.On("DialTimeout", ctx, network, address, timeout)}
}

func (_c *MockNetworkHost_DialTimeout_Call) Run(run func(ctx context.Context, network string, address string, timeout time.Duration)) *MockNetworkHost_DialTimeout_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 time.Duration
		if args[3] != nil {
			arg3 = args[3].(time.Duration)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockNetworkHost_DialTimeout_Call) Return(conn net.Conn, err error) *MockNetworkHost_DialTimeout_Call {
	_c.Call.Return(conn, err)
	return _c
}

func (_c *MockNetworkHost_DialTimeout_Call) RunAndReturn(run func(ctx context.Context, network string, address string, timeout time.Duration) (net.Conn, error)) *MockNetworkHost_DialTimeout_Call {
	_c.Call.Return(run)
	return _c
}

// GetHostsConfig provides a mock function for the type MockNetworkHost
func (_mock *MockNetworkHost) GetHostsConfig() *txeh.HostsConfig {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetHostsConfig")
	}

	var r0 *txeh.HostsConfig
	if returnFunc, ok := ret.Get(0).(func() *txeh.HostsConfig); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*txeh.HostsConfig)
		}
	}
	return r0
}

// MockNetworkHost_GetHostsConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetHostsConfig'
type MockNetworkHost_GetHostsConfig_Call struct {
	*mock.Call
}

// GetHostsConfig is a helper method to define mock.On call
func (_e *MockNetworkHost_Expecter) GetHostsConfig() *MockNetworkHost_GetHostsConfig_Call {
	return &MockNetworkHost_GetHostsConfig_Call{Call: _e.mock.On("GetHostsConfig")}
}

func (_c *MockNetworkHost_GetHostsConfig_Call) Run(run func()) *MockNetworkHost_GetHostsConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockNetworkHost_GetHostsConfig_Call) Return(hostsConfig *txeh.HostsConfig) *MockNetworkHost_GetHostsConfig_Call {
	_c.Call.Return(hostsConfig)
	return _c
}

func (_c *MockNetworkHost_GetHostsConfig_Call) RunAndReturn(run func() *txeh.HostsConfig) *MockNetworkHost_GetHostsConfig_Call {
	_c.Call.Return(run)
	return _c
}

// GetOutboundIP provides a mock function for the type MockNetworkHost
func (_mock *MockNetworkHost) GetOutboundIP() (net.IP, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetOutboundIP")
	}

	var r0 net.IP
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (net.IP, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() net.IP); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(net.IP)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockNetworkHost_GetOutboundIP_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOutboundIP'
type MockNetworkHost_GetOutboundIP_Call struct {
	*mock.Call
}

// GetOutboundIP is a helper method to define mock.On call
func (_e *MockNetworkHost_Expecter) GetOutboundIP() *MockNetworkHost_GetOutboundIP_Call {
	return &MockNetworkHost_GetOutboundIP_Call{Call: _e.mock.On("GetOutboundIP")}
}

func (_c *MockNetworkHost_GetOutboundIP_Call) Run(run func()) *MockNetworkHost_GetOutboundIP_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockNetworkHost_GetOutboundIP_Call) Return(iP net.IP, err error) *MockNetworkHost_GetOutboundIP_Call {
	_c.Call.Return(iP, err)
	return _c
}

func (_c *MockNetworkHost_GetOutboundIP_Call) RunAndReturn(run func() (net.IP, error)) *MockNetworkHost_GetOutboundIP_Call {
	_c.Call.Return(run)
	return _c
}

// IsHostMapped provides a mock function for the type MockNetworkHost
func (_mock *MockNetworkHost) IsHostMapped(ctx context.Context, ip net.IP, domainName string) (bool, []net.IP) {
	ret := _mock.Called(ctx, ip, domainName)

	if len(ret) == 0 {
		panic("no return value specified for IsHostMapped")
	}

	var r0 bool
	var r1 []net.IP
	if returnFunc, ok := ret.Get(0).(func(context.Context, net.IP, string) (bool, []net.IP)); ok {
		return returnFunc(ctx, ip, domainName)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, net.IP, string) bool); ok {
		r0 = returnFunc(ctx, ip, domainName)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, net.IP, string) []net.IP); ok {
		r1 = returnFunc(ctx, ip, domainName)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]net.IP)
		}
	}
	return r0, r1
}

// MockNetworkHost_IsHostMapped_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsHostMapped'
type MockNetworkHost_IsHostMapped_Call struct {
	*mock.Call
}

// IsHostMapped is a helper method to define mock.On call
//   - ctx context.Context
//   - ip net.IP
//   - domainName string
func (_e *MockNetworkHost_Expecter) IsHostMapped(ctx interface{}, ip interface{}, domainName interface{}) *MockNetworkHost_IsHostMapped_Call {
	return &MockNetworkHost_IsHostMapped_Call{Call: _e.mock.On("IsHostMapped", ctx, ip, domainName)}
}

func (_c *MockNetworkHost_IsHostMapped_Call) Run(run func(ctx context.Context, ip net.IP, domainName string)) *MockNetworkHost_IsHostMapped_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 net.IP
		if args[1] != nil {
			arg1 = args[1].(net.IP)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockNetworkHost_IsHostMapped_Call) Return(b bool, iPs []net.IP) *MockNetworkHost_IsHostMapped_Call {
	_c.Call.Return(b, iPs)
	return _c
}

func (_c *MockNetworkHost_IsHostMapped_Call) RunAndReturn(run func(ctx context.Context, ip net.IP, domainName string) (bool, []net.IP)) *MockNetworkHost_IsHostMapped_Call {
	_c.Call.Return(run)
	return _c
}

// Listen provides a mock function for the type MockNetworkHost
func (_mock *MockNetworkHost) Listen(ctx context.Context, network string, address string) (net.Listener, error) {
	ret := _mock.Called(ctx, network, address)

	if len(ret) == 0 {
		panic("no return value specified for Listen")
	}

	var r0 net.Listener
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (net.Listener, error)); ok {
		return returnFunc(ctx, network, address)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) net.Listener); ok {
		r0 = returnFunc(ctx, network, address)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(net.Listener)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, network, address)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockNetworkHost_Listen_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Listen'
type MockNetworkHost_Listen_Call struct {
	*mock.Call
}

// Listen is a helper method to define mock.On call
//   - ctx context.Context
//   - network string
//   - address string
func (_e *MockNetworkHost_Expecter) Listen(ctx interface{}, network interface{}, address interface{}) *MockNetworkHost_Listen_Call {
	return &MockNetworkHost_Listen_Call{Call: _e.mock.On("Listen", ctx, network, address)}
}

func (_c *MockNetworkHost_Listen_Call) Run(run func(ctx context.Context, network string, address string)) *MockNetworkHost_Listen_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockNetworkHost_Listen_Call) Return(listener net.Listener, err error) *MockNetworkHost_Listen_Call {
	_c.Call.Return(listener, err)
	return _c
}

func (_c *MockNetworkHost_Listen_Call) RunAndReturn(run func(ctx context.Context, network string, address string) (net.Listener, error)) *MockNetworkHost_Listen_Call {
	_c.Call.Return(run)
	return _c
}
