// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package host

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockProcessState creates a new instance of MockProcessState. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProcessState(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProcessState {
	mock := &MockProcessState{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockProcessState is an autogenerated mock type for the ProcessState type
type MockProcessState struct {
	mock.Mock
}

type MockProcessState_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProcessState) EXPECT() *MockProcessState_Expecter {
	return &MockProcessState_Expecter{mock: &_m.Mock}
}

// ExitCode provides a mock function for the type MockProcessState
func (_mock *MockProcessState) ExitCode() int {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ExitCode")
	}

	var r0 int
	if returnFunc, ok := ret.Get(0).(func() int); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(int)
	}
	return r0
}

// MockProcessState_ExitCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExitCode'
type MockProcessState_ExitCode_Call struct {
	*mock.Call
}

// ExitCode is a helper method to define mock.On call
func (_e *MockProcessState_Expecter) ExitCode() *MockProcessState_ExitCode_Call {
	return &MockProcessState_ExitCode_Call{Call: _e.mock.On("ExitCode")}
}

func (_c *MockProcessState_ExitCode_Call) Run(run func()) *MockProcessState_ExitCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockProcessState_ExitCode_Call) Return(n int) *MockProcessState_ExitCode_Call {
	_c.Call.Return(n)
	return _c
}

func (_c *MockProcessState_ExitCode_Call) RunAndReturn(run func() int) *MockProcessState_ExitCode_Call {
	_c.Call.Return(run)
	return _c
}

// Exited provides a mock function for the type MockProcessState
func (_mock *MockProcessState) Exited() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Exited")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockProcessState_Exited_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exited'
type MockProcessState_Exited_Call struct {
	*mock.Call
}

// Exited is a helper method to define mock.On call
func (_e *MockProcessState_Expecter) Exited() *MockProcessState_Exited_Call {
	return &MockProcessState_Exited_Call{Call: _e.mock.On("Exited")}
}

func (_c *MockProcessState_Exited_Call) Run(run func()) *MockProcessState_Exited_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockProcessState_Exited_Call) Return(b bool) *MockProcessState_Exited_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockProcessState_Exited_Call) RunAndReturn(run func() bool) *MockProcessState_Exited_Call {
	_c.Call.Return(run)
	return _c
}

// String provides a mock function for the type MockProcessState
func (_mock *MockProcessState) String() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for String")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockProcessState_String_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'String'
type MockProcessState_String_Call struct {
	*mock.Call
}

// String is a helper method to define mock.On call
func (_e *MockProcessState_Expecter) String() *MockProcessState_String_Call {
	return &MockProcessState_String_Call{Call: _e.mock.On("String")}
}

func (_c *MockProcessState_String_Call) Run(run func()) *MockProcessState_String_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockProcessState_String_Call) Return(s string) *MockProcessState_String_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockProcessState_String_Call) RunAndReturn(run func() string) *MockProcessState_String_Call {
	_c.Call.Return(run)
	return _c
}

// Success provides a mock function for the type MockProcessState
func (_mock *MockProcessState) Success() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Success")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockProcessState_Success_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Success'
type MockProcessState_Success_Call struct {
	*mock.Call
}

// Success is a helper method to define mock.On call
func (_e *MockProcessState_Expecter) Success() *MockProcessState_Success_Call {
	return &MockProcessState_Success_Call{Call: _e.mock.On("Success")}
}

func (_c *MockProcessState_Success_Call) Run(run func()) *MockProcessState_Success_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockProcessState_Success_Call) Return(b bool) *MockProcessState_Success_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockProcessState_Success_Call) RunAndReturn(run func() bool) *MockProcessState_Success_Call {
	_c.Call.Return(run)
	return _c
}
