// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package host

import (
	"os"

	"github.com/kaweezle/iknite/pkg/host"
	mock "github.com/stretchr/testify/mock"
)

// NewMockProcess creates a new instance of MockProcess. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProcess(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProcess {
	mock := &MockProcess{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockProcess is an autogenerated mock type for the Process type
type MockProcess struct {
	mock.Mock
}

type MockProcess_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProcess) EXPECT() *MockProcess_Expecter {
	return &MockProcess_Expecter{mock: &_m.Mock}
}

// Pid provides a mock function for the type MockProcess
func (_mock *MockProcess) Pid() int {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Pid")
	}

	var r0 int
	if returnFunc, ok := ret.Get(0).(func() int); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(int)
	}
	return r0
}

// MockProcess_Pid_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Pid'
type MockProcess_Pid_Call struct {
	*mock.Call
}

// Pid is a helper method to define mock.On call
func (_e *MockProcess_Expecter) Pid() *MockProcess_Pid_Call {
	return &MockProcess_Pid_Call{Call: _e.mock.On("Pid")}
}

func (_c *MockProcess_Pid_Call) Run(run func()) *MockProcess_Pid_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockProcess_Pid_Call) Return(n int) *MockProcess_Pid_Call {
	_c.Call.Return(n)
	return _c
}

func (_c *MockProcess_Pid_Call) RunAndReturn(run func() int) *MockProcess_Pid_Call {
	_c.Call.Return(run)
	return _c
}

// Signal provides a mock function for the type MockProcess
func (_mock *MockProcess) Signal(signal os.Signal) error {
	ret := _mock.Called(signal)

	if len(ret) == 0 {
		panic("no return value specified for Signal")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(os.Signal) error); ok {
		r0 = returnFunc(signal)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockProcess_Signal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Signal'
type MockProcess_Signal_Call struct {
	*mock.Call
}

// Signal is a helper method to define mock.On call
//   - signal os.Signal
func (_e *MockProcess_Expecter) Signal(signal interface{}) *MockProcess_Signal_Call {
	return &MockProcess_Signal_Call{Call: _e.mock.On("Signal", signal)}
}

func (_c *MockProcess_Signal_Call) Run(run func(signal os.Signal)) *MockProcess_Signal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 os.Signal
		if args[0] != nil {
			arg0 = args[0].(os.Signal)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockProcess_Signal_Call) Return(err error) *MockProcess_Signal_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockProcess_Signal_Call) RunAndReturn(run func(signal os.Signal) error) *MockProcess_Signal_Call {
	_c.Call.Return(run)
	return _c
}

// State provides a mock function for the type MockProcess
func (_mock *MockProcess) State() host.ProcessState {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for State")
	}

	var r0 host.ProcessState
	if returnFunc, ok := ret.Get(0).(func() host.ProcessState); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(host.ProcessState)
		}
	}
	return r0
}

// MockProcess_State_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'State'
type MockProcess_State_Call struct {
	*mock.Call
}

// State is a helper method to define mock.On call
func (_e *MockProcess_Expecter) State() *MockProcess_State_Call {
	return &MockProcess_State_Call{Call: _e.mock.On("State")}
}

func (_c *MockProcess_State_Call) Run(run func()) *MockProcess_State_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockProcess_State_Call) Return(processState host.ProcessState) *MockProcess_State_Call {
	_c.Call.Return(processState)
	return _c
}

func (_c *MockProcess_State_Call) RunAndReturn(run func() host.ProcessState) *MockProcess_State_Call {
	_c.Call.Return(run)
	return _c
}

// Wait provides a mock function for the type MockProcess
func (_mock *MockProcess) Wait() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Wait")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockProcess_Wait_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Wait'
type MockProcess_Wait_Call struct {
	*mock.Call
}

// Wait is a helper method to define mock.On call
func (_e *MockProcess_Expecter) Wait() *MockProcess_Wait_Call {
	return &MockProcess_Wait_Call{Call: _e.mock.On("Wait")}
}

func (_c *MockProcess_Wait_Call) Run(run func()) *MockProcess_Wait_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockProcess_Wait_Call) Return(err error) *MockProcess_Wait_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockProcess_Wait_Call) RunAndReturn(run func() error) *MockProcess_Wait_Call {
	_c.Call.Return(run)
	return _c
}
