// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package host

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockSystem creates a new instance of MockSystem. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSystem(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSystem {
	mock := &MockSystem{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSystem is an autogenerated mock type for the System type
type MockSystem struct {
	mock.Mock
}

type MockSystem_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSystem) EXPECT() *MockSystem_Expecter {
	return &MockSystem_Expecter{mock: &_m.Mock}
}

// Unmount provides a mock function for the type MockSystem
func (_mock *MockSystem) Unmount(path string) error {
	ret := _mock.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for Unmount")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(path)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSystem_Unmount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Unmount'
type MockSystem_Unmount_Call struct {
	*mock.Call
}

// Unmount is a helper method to define mock.On call
//   - path string
func (_e *MockSystem_Expecter) Unmount(path interface{}) *MockSystem_Unmount_Call {
	return &MockSystem_Unmount_Call{Call: _e.mock.On("Unmount", path)}
}

func (_c *MockSystem_Unmount_Call) Run(run func(path string)) *MockSystem_Unmount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSystem_Unmount_Call) Return(err error) *MockSystem_Unmount_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSystem_Unmount_Call) RunAndReturn(run func(path string) error) *MockSystem_Unmount_Call {
	_c.Call.Return(run)
	return _c
}
