// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package host

import (
	"context"
	"io"
	"os"
	"path/filepath"

	"github.com/bitfield/script"
	"github.com/kaweezle/iknite/pkg/host"
	"github.com/spf13/afero"
	mock "github.com/stretchr/testify/mock"
)

// NewMockUserHost creates a new instance of MockUserHost. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserHost(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserHost {
	mock := &MockUserHost{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUserHost is an autogenerated mock type for the UserHost type
type MockUserHost struct {
	mock.Mock
}

type MockUserHost_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserHost) EXPECT() *MockUserHost_Expecter {
	return &MockUserHost_Expecter{mock: &_m.Mock}
}

// Abs provides a mock function for the type MockUserHost
func (_mock *MockUserHost) Abs(path string) (string, error) {
	ret := _mock.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for Abs")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (string, error)); ok {
		return returnFunc(path)
	}
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(path)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(path)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserHost_Abs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Abs'
type MockUserHost_Abs_Call struct {
	*mock.Call
}

// Abs is a helper method to define mock.On call
//   - path string
func (_e *MockUserHost_Expecter) Abs(path interface{}) *MockUserHost_Abs_Call {
	return &MockUserHost_Abs_Call{Call: _e.mock.On("Abs", path)}
}

func (_c *MockUserHost_Abs_Call) Run(run func(path string)) *MockUserHost_Abs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockUserHost_Abs_Call) Return(s string, err error) *MockUserHost_Abs_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockUserHost_Abs_Call) RunAndReturn(run func(path string) (string, error)) *MockUserHost_Abs_Call {
	_c.Call.Return(run)
	return _c
}

// Chmod provides a mock function for the type MockUserHost
func (_mock *MockUserHost) Chmod(path string, mode os.FileMode) error {
	ret := _mock.Called(path, mode)

	if len(ret) == 0 {
		panic("no return value specified for Chmod")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, os.FileMode) error); ok {
		r0 = returnFunc(path, mode)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserHost_Chmod_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Chmod'
type MockUserHost_Chmod_Call struct {
	*mock.Call
}

// Chmod is a helper method to define mock.On call
//   - path string
//   - mode os.FileMode
func (_e *MockUserHost_Expecter) Chmod(path interface{}, mode interface{}) *MockUserHost_Chmod_Call {
	return &MockUserHost_Chmod_Call{Call: _e.mock.On("Chmod", path, mode)}
}

func (_c *MockUserHost_Chmod_Call) Run(run func(path string, mode os.FileMode)) *MockUserHost_Chmod_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 os.FileMode
		if args[1] != nil {
			arg1 = args[1].(os.FileMode)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserHost_Chmod_Call) Return(err error) *MockUserHost_Chmod_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserHost_Chmod_Call) RunAndReturn(run func(path string, mode os.FileMode) error) *MockUserHost_Chmod_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type MockUserHost
func (_mock *MockUserHost) Create(path string) (afero.File, error) {
	ret := _mock.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 afero.File
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (afero.File, error)); ok {
		return returnFunc(path)
	}
	if returnFunc, ok := ret.Get(0).(func(string) afero.File); ok {
		r0 = returnFunc(path)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(afero.File)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(path)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserHost_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockUserHost_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - path string
func (_e *MockUserHost_Expecter) Create(path interface{}) *MockUserHost_Create_Call {
	return &MockUserHost_Create_Call{Call: _e.mock.On("Create", path)}
}

func (_c *MockUserHost_Create_Call) Run(run func(path string)) *MockUserHost_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockUserHost_Create_Call) Return(file afero.File, err error) *MockUserHost_Create_Call {
	_c.Call.Return(file, err)
	return _c
}

func (_c *MockUserHost_Create_Call) RunAndReturn(run func(path string) (afero.File, error)) *MockUserHost_Create_Call {
	_c.Call.Return(run)
	return _c
}

// DirExists provides a mock function for the type MockUserHost
func (_mock *MockUserHost) DirExists(path string) (bool, error) {
	ret := _mock.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for DirExists")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (bool, error)); ok {
		return returnFunc(path)
	}
	if returnFunc, ok := ret.Get(0).(func(string) bool); ok {
		r0 = returnFunc(path)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(path)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserHost_DirExists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DirExists'
type MockUserHost_DirExists_Call struct {
	*mock.Call
}

// DirExists is a helper method to define mock.On call
//   - path string
func (_e *MockUserHost_Expecter) DirExists(path interface{}) *MockUserHost_DirExists_Call {
	return &MockUserHost_DirExists_Call{Call: _e.mock.On("DirExists", path)}
}

func (_c *MockUserHost_DirExists_Call) Run(run func(path string)) *MockUserHost_DirExists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockUserHost_DirExists_Call) Return(b bool, err error) *MockUserHost_DirExists_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockUserHost_DirExists_Call) RunAndReturn(run func(path string) (bool, error)) *MockUserHost_DirExists_Call {
	_c.Call.Return(run)
	return _c
}

// EvalSymlinks provides a mock function for the type MockUserHost
func (_mock *MockUserHost) EvalSymlinks(path string) (string, error) {
	ret := _mock.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for EvalSymlinks")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (string, error)); ok {
		return returnFunc(path)
	}
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(path)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(path)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserHost_EvalSymlinks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EvalSymlinks'
type MockUserHost_EvalSymlinks_Call struct {
	*mock.Call
}

// EvalSymlinks is a helper method to define mock.On call
//   - path string
func (_e *MockUserHost_Expecter) EvalSymlinks(path interface{}) *MockUserHost_EvalSymlinks_Call {
	return &MockUserHost_EvalSymlinks_Call{Call: _e.mock.On("EvalSymlinks", path)}
}

func (_c *MockUserHost_EvalSymlinks_Call) Run(run func(path string)) *MockUserHost_EvalSymlinks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockUserHost_EvalSymlinks_Call) Return(s string, err error) *MockUserHost_EvalSymlinks_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockUserHost_EvalSymlinks_Call) RunAndReturn(run func(path string) (string, error)) *MockUserHost_EvalSymlinks_Call {
	_c.Call.Return(run)
	return _c
}

// ExecForEach provides a mock function for the type MockUserHost
func (_mock *MockUserHost) ExecForEach(stdin *script.Pipe, cmd string) *script.Pipe {
	ret := _mock.Called(stdin, cmd)

	if len(ret) == 0 {
		panic("no return value specified for ExecForEach")
	}

	var r0 *script.Pipe
	if returnFunc, ok := ret.Get(0).(func(*script.Pipe, string) *script.Pipe); ok {
		r0 = returnFunc(stdin, cmd)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*script.Pipe)
		}
	}
	return r0
}

// MockUserHost_ExecForEach_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExecForEach'
type MockUserHost_ExecForEach_Call struct {
	*mock.Call
}

// ExecForEach is a helper method to define mock.On call
//   - stdin *script.Pipe
//   - cmd string
func (_e *MockUserHost_Expecter) ExecForEach(stdin interface{}, cmd interface{}) *MockUserHost_ExecForEach_Call {
	return &MockUserHost_ExecForEach_Call{Call: _e.mock.On("ExecForEach", stdin, cmd)}
}

func (_c *MockUserHost_ExecForEach_Call) Run(run func(stdin *script.Pipe, cmd string)) *MockUserHost_ExecForEach_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *script.Pipe
		if args[0] != nil {
			arg0 = args[0].(*script.Pipe)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserHost_ExecForEach_Call) Return(pipe *script.Pipe) *MockUserHost_ExecForEach_Call {
	_c.Call.Return(pipe)
	return _c
}

func (_c *MockUserHost_ExecForEach_Call) RunAndReturn(run func(stdin *script.Pipe, cmd string) *script.Pipe) *MockUserHost_ExecForEach_Call {
	_c.Call.Return(run)
	return _c
}

// ExecPipe provides a mock function for the type MockUserHost
func (_mock *MockUserHost) ExecPipe(stdin *script.Pipe, cmd string) *script.Pipe {
	ret := _mock.Called(stdin, cmd)

	if len(ret) == 0 {
		panic("no return value specified for ExecPipe")
	}

	var r0 *script.Pipe
	if returnFunc, ok := ret.Get(0).(func(*script.Pipe, string) *script.Pipe); ok {
		r0 = returnFunc(stdin, cmd)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*script.Pipe)
		}
	}
	return r0
}

// MockUserHost_ExecPipe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExecPipe'
type MockUserHost_ExecPipe_Call struct {
	*mock.Call
}

// ExecPipe is a helper method to define mock.On call
//   - stdin *script.Pipe
//   - cmd string
func (_e *MockUserHost_Expecter) ExecPipe(stdin interface{}, cmd interface{}) *MockUserHost_ExecPipe_Call {
	return &MockUserHost_ExecPipe_Call{Call: _e.mock.On("ExecPipe", stdin, cmd)}
}

func (_c *MockUserHost_ExecPipe_Call) Run(run func(stdin *script.Pipe, cmd string)) *MockUserHost_ExecPipe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *script.Pipe
		if args[0] != nil {
			arg0 = args[0].(*script.Pipe)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserHost_ExecPipe_Call) Return(pipe *script.Pipe) *MockUserHost_ExecPipe_Call {
	_c.Call.Return(pipe)
	return _c
}

func (_c *MockUserHost_ExecPipe_Call) RunAndReturn(run func(stdin *script.Pipe, cmd string) *script.Pipe) *MockUserHost_ExecPipe_Call {
	_c.Call.Return(run)
	return _c
}

// Exists provides a mock function for the type MockUserHost
func (_mock *MockUserHost) Exists(path string) (bool, error) {
	ret := _mock.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for Exists")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (bool, error)); ok {
		return returnFunc(path)
	}
	if returnFunc, ok := ret.Get(0).(func(string) bool); ok {
		r0 = returnFunc(path)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(path)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserHost_Exists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exists'
type MockUserHost_Exists_Call struct {
	*mock.Call
}

// Exists is a helper method to define mock.On call
//   - path string
func (_e *MockUserHost_Expecter) Exists(path interface{}) *MockUserHost_Exists_Call {
	return &MockUserHost_Exists_Call{Call: _e.mock.On("Exists", path)}
}

func (_c *MockUserHost_Exists_Call) Run(run func(path string)) *MockUserHost_Exists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockUserHost_Exists_Call) Return(b bool, err error) *MockUserHost_Exists_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockUserHost_Exists_Call) RunAndReturn(run func(path string) (bool, error)) *MockUserHost_Exists_Call {
	_c.Call.Return(run)
	return _c
}

// FindProcess provides a mock function for the type MockUserHost
func (_mock *MockUserHost) FindProcess(pid int) (host.Process, error) {
	ret := _mock.Called(pid)

	if len(ret) == 0 {
		panic("no return value specified for FindProcess")
	}

	var r0 host.Process
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(int) (host.Process, error)); ok {
		return returnFunc(pid)
	}
	if returnFunc, ok := ret.Get(0).(func(int) host.Process); ok {
		r0 = returnFunc(pid)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(host.Process)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(int) error); ok {
		r1 = returnFunc(pid)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserHost_FindProcess_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindProcess'
type MockUserHost_FindProcess_Call struct {
	*mock.Call
}

// FindProcess is a helper method to define mock.On call
//   - pid int
func (_e *MockUserHost_Expecter) FindProcess(pid interface{}) *MockUserHost_FindProcess_Call {
	return &MockUserHost_FindProcess_Call{Call: _e.mock.On("FindProcess", pid)}
}

func (_c *MockUserHost_FindProcess_Call) Run(run func(pid int)) *MockUserHost_FindProcess_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockUserHost_FindProcess_Call) Return(process host.Process, err error) *MockUserHost_FindProcess_Call {
	_c.Call.Return(process, err)
	return _c
}

func (_c *MockUserHost_FindProcess_Call) RunAndReturn(run func(pid int) (host.Process, error)) *MockUserHost_FindProcess_Call {
	_c.Call.Return(run)
	return _c
}

// GOOS provides a mock function for the type MockUserHost
func (_mock *MockUserHost) GOOS() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GOOS")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockUserHost_GOOS_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GOOS'
type MockUserHost_GOOS_Call struct {
	*mock.Call
}

// GOOS is a helper method to define mock.On call
func (_e *MockUserHost_Expecter) GOOS() *MockUserHost_GOOS_Call {
	return &MockUserHost_GOOS_Call{Call: _e.mock.On("GOOS")}
}

func (_c *MockUserHost_GOOS_Call) Run(run func()) *MockUserHost_GOOS_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockUserHost_GOOS_Call) Return(s string) *MockUserHost_GOOS_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockUserHost_GOOS_Call) RunAndReturn(run func() string) *MockUserHost_GOOS_Call {
	_c.Call.Return(run)
	return _c
}

// Getenv provides a mock function for the type MockUserHost
func (_mock *MockUserHost) Getenv(key string) string {
	ret := _mock.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for Getenv")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(key)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockUserHost_Getenv_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Getenv'
type MockUserHost_Getenv_Call struct {
	*mock.Call
}

// Getenv is a helper method to define mock.On call
//   - key string
func (_e *MockUserHost_Expecter) Getenv(key interface{}) *MockUserHost_Getenv_Call {
	return &MockUserHost_Getenv_Call{Call: _e.mock.On("Getenv", key)}
}

func (_c *MockUserHost_Getenv_Call) Run(run func(key string)) *MockUserHost_Getenv_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockUserHost_Getenv_Call) Return(s string) *MockUserHost_Getenv_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockUserHost_Getenv_Call) RunAndReturn(run func(key string) string) *MockUserHost_Getenv_Call {
	_c.Call.Return(run)
	return _c
}

// Glob provides a mock function for the type MockUserHost
func (_mock *MockUserHost) Glob(pattern string) ([]string, error) {
	ret := _mock.Called(pattern)

	if len(ret) == 0 {
		panic("no return value specified for Glob")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) ([]string, error)); ok {
		return returnFunc(pattern)
	}
	if returnFunc, ok := ret.Get(0).(func(string) []string); ok {
		r0 = returnFunc(pattern)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(pattern)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserHost_Glob_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Glob'
type MockUserHost_Glob_Call struct {
	*mock.Call
}

// Glob is a helper method to define mock.On call
//   - pattern string
func (_e *MockUserHost_Expecter) Glob(pattern interface{}) *MockUserHost_Glob_Call {
	return &MockUserHost_Glob_Call{Call: _e.mock.On("Glob", pattern)}
}

func (_c *MockUserHost_Glob_Call) Run(run func(pattern string)) *MockUserHost_Glob_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockUserHost_Glob_Call) Return(matches []string, err error) *MockUserHost_Glob_Call {
	_c.Call.Return(matches, err)
	return _c
}

func (_c *MockUserHost_Glob_Call) RunAndReturn(run func(pattern string) ([]string, error)) *MockUserHost_Glob_Call {
	_c.Call.Return(run)
	return _c
}

// JoinPath provides a mock function for the type MockUserHost
func (_mock *MockUserHost) JoinPath(elem ...string) string {
	var tmpRet mock.Arguments
	if len(elem) > 0 {
		tmpRet = _mock.Called(elem)
	} else {
		tmpRet = _mock.Called()
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for JoinPath")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func(...string) string); ok {
		r0 = returnFunc(elem...)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockUserHost_JoinPath_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'JoinPath'
type MockUserHost_JoinPath_Call struct {
	*mock.Call
}

// JoinPath is a helper method to define mock.On call
//   - elem ...string
func (_e *MockUserHost_Expecter) JoinPath(elem ...interface{}) *MockUserHost_JoinPath_Call {
	return &MockUserHost_JoinPath_Call{Call: _e.mock.On("JoinPath",
		append([]interface{}{}, elem...)...)}
}

func (_c *MockUserHost_JoinPath_Call) Run(run func(elem ...string)) *MockUserHost_JoinPath_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []string
		var variadicArgs []string
		if len(args) > 0 {
			variadicArgs = args[0].([]string)
		}
		arg0 = variadicArgs
		run(
			arg0...,
		)
	})
	return _c
}

func (_c *MockUserHost_JoinPath_Call) Return(s string) *MockUserHost_JoinPath_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockUserHost_JoinPath_Call) RunAndReturn(run func(elem ...string) string) *MockUserHost_JoinPath_Call {
	_c.Call.Return(run)
	return _c
}

// LookupEnv provides a mock function for the type MockUserHost
func (_mock *MockUserHost) LookupEnv(key string) (string, bool) {
	ret := _mock.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for LookupEnv")
	}

	var r0 string
	var r1 bool
	if returnFunc, ok := ret.Get(0).(func(string) (string, bool)); ok {
		return returnFunc(key)
	}
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(key)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string) bool); ok {
		r1 = returnFunc(key)
	} else {
		r1 = ret.Get(1).(bool)
	}
	return r0, r1
}

// MockUserHost_LookupEnv_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LookupEnv'
type MockUserHost_LookupEnv_Call struct {
	*mock.Call
}

// LookupEnv is a helper method to define mock.On call
//   - key string
func (_e *MockUserHost_Expecter) LookupEnv(key interface{}) *MockUserHost_LookupEnv_Call {
	return &MockUserHost_LookupEnv_Call{Call: _e.mock.On("LookupEnv", key)}
}

func (_c *MockUserHost_LookupEnv_Call) Run(run func(key string)) *MockUserHost_LookupEnv_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockUserHost_LookupEnv_Call) Return(s string, b bool) *MockUserHost_LookupEnv_Call {
	_c.Call.Return(s, b)
	return _c
}

func (_c *MockUserHost_LookupEnv_Call) RunAndReturn(run func(key string) (string, bool)) *MockUserHost_LookupEnv_Call {
	_c.Call.Return(run)
	return _c
}

// MkdirAll provides a mock function for the type MockUserHost
func (_mock *MockUserHost) MkdirAll(path string, perm os.FileMode) error {
	ret := _mock.Called(path, perm)

	if len(ret) == 0 {
		panic("no return value specified for MkdirAll")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, os.FileMode) error); ok {
		r0 = returnFunc(path, perm)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserHost_MkdirAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MkdirAll'
type MockUserHost_MkdirAll_Call struct {
	*mock.Call
}

// MkdirAll is a helper method to define mock.On call
//   - path string
//   - perm os.FileMode
func (_e *MockUserHost_Expecter) MkdirAll(path interface{}, perm interface{}) *MockUserHost_MkdirAll_Call {
	return &MockUserHost_MkdirAll_Call{Call: _e.mock.On("MkdirAll", path, perm)}
}

func (_c *MockUserHost_MkdirAll_Call) Run(run func(path string, perm os.FileMode)) *MockUserHost_MkdirAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 os.FileMode
		if args[1] != nil {
			arg1 = args[1].(os.FileMode)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserHost_MkdirAll_Call) Return(err error) *MockUserHost_MkdirAll_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserHost_MkdirAll_Call) RunAndReturn(run func(path string, perm os.FileMode) error) *MockUserHost_MkdirAll_Call {
	_c.Call.Return(run)
	return _c
}

// Open provides a mock function for the type MockUserHost
func (_mock *MockUserHost) Open(path string) (afero.File, error) {
	ret := _mock.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for Open")
	}

	var r0 afero.File
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (afero.File, error)); ok {
		return returnFunc(path)
	}
	if returnFunc, ok := ret.Get(0).(func(string) afero.File); ok {
		r0 = returnFunc(path)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(afero.File)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(path)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserHost_Open_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Open'
type MockUserHost_Open_Call struct {
	*mock.Call
}

// Open is a helper method to define mock.On call
//   - path string
func (_e *MockUserHost_Expecter) Open(path interface{}) *MockUserHost_Open_Call {
	return &MockUserHost_Open_Call{Call: _e.mock.On("Open", path)}
}

func (_c *MockUserHost_Open_Call) Run(run func(path string)) *MockUserHost_Open_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockUserHost_Open_Call) Return(file afero.File, err error) *MockUserHost_Open_Call {
	_c.Call.Return(file, err)
	return _c
}

func (_c *MockUserHost_Open_Call) RunAndReturn(run func(path string) (afero.File, error)) *MockUserHost_Open_Call {
	_c.Call.Return(run)
	return _c
}

// OpenFile provides a mock function for the type MockUserHost
func (_mock *MockUserHost) OpenFile(path string, flag int, perm os.FileMode) (afero.File, error) {
	ret := _mock.Called(path, flag, perm)

	if len(ret) == 0 {
		panic("no return value specified for OpenFile")
	}

	var r0 afero.File
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, int, os.FileMode) (afero.File, error)); ok {
		return returnFunc(path, flag, perm)
	}
	if returnFunc, ok := ret.Get(0).(func(string, int, os.FileMode) afero.File); ok {
		r0 = returnFunc(path, flag, perm)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(afero.File)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, int, os.FileMode) error); ok {
		r1 = returnFunc(path, flag, perm)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserHost_OpenFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OpenFile'
type MockUserHost_OpenFile_Call struct {
	*mock.Call
}

// OpenFile is a helper method to define mock.On call
//   - path string
//   - flag int
//   - perm os.FileMode
func (_e *MockUserHost_Expecter) OpenFile(path interface{}, flag interface{}, perm interface{}) *MockUserHost_OpenFile_Call {
	return &MockUserHost_OpenFile_Call{Call: _e.mock.On("OpenFile", path, flag, perm)}
}

func (_c *MockUserHost_OpenFile_Call) Run(run func(path string, flag int, perm os.FileMode)) *MockUserHost_OpenFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 os.FileMode
		if args[2] != nil {
			arg2 = args[2].(os.FileMode)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUserHost_OpenFile_Call) Return(file afero.File, err error) *MockUserHost_OpenFile_Call {
	_c.Call.Return(file, err)
	return _c
}

func (_c *MockUserHost_OpenFile_Call) RunAndReturn(run func(path string, flag int, perm os.FileMode) (afero.File, error)) *MockUserHost_OpenFile_Call {
	_c.Call.Return(run)
	return _c
}

// Pipe provides a mock function for the type MockUserHost
func (_mock *MockUserHost) Pipe(path string) *script.Pipe {
	ret := _mock.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for Pipe")
	}

	var r0 *script.Pipe
	if returnFunc, ok := ret.Get(0).(func(string) *script.Pipe); ok {
		r0 = returnFunc(path)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*script.Pipe)
		}
	}
	return r0
}

// MockUserHost_Pipe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Pipe'
type MockUserHost_Pipe_Call struct {
	*mock.Call
}

// Pipe is a helper method to define mock.On call
//   - path string
func (_e *MockUserHost_Expecter) Pipe(path interface{}) *MockUserHost_Pipe_Call {
	return &MockUserHost_Pipe_Call{Call: _e.mock.On("Pipe", path)}
}

func (_c *MockUserHost_Pipe_Call) Run(run func(path string)) *MockUserHost_Pipe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockUserHost_Pipe_Call) Return(pipe *script.Pipe) *MockUserHost_Pipe_Call {
	_c.Call.Return(pipe)
	return _c
}

func (_c *MockUserHost_Pipe_Call) RunAndReturn(run func(path string) *script.Pipe) *MockUserHost_Pipe_Call {
	_c.Call.Return(run)
	return _c
}

// PipeRun provides a mock function for the type MockUserHost
func (_mock *MockUserHost) PipeRun(stdin io.Reader, combined bool, cmd string, arguments ...string) ([]byte, error) {
	var tmpRet mock.Arguments
	if len(arguments) > 0 {
		tmpRet = _mock.Called(stdin, combined, cmd, arguments)
	} else {
		tmpRet = _mock.Called(stdin, combined, cmd)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for PipeRun")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(io.Reader, bool, string, ...string) ([]byte, error)); ok {
		return returnFunc(stdin, combined, cmd, arguments...)
	}
	if returnFunc, ok := ret.Get(0).(func(io.Reader, bool, string, ...string) []byte); ok {
		r0 = returnFunc(stdin, combined, cmd, arguments...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(io.Reader, bool, string, ...string) error); ok {
		r1 = returnFunc(stdin, combined, cmd, arguments...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserHost_PipeRun_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PipeRun'
type MockUserHost_PipeRun_Call struct {
	*mock.Call
}

// PipeRun is a helper method to define mock.On call
//   - stdin io.Reader
//   - combined bool
//   - cmd string
//   - arguments ...string
func (_e *MockUserHost_Expecter) PipeRun(stdin interface{}, combined interface{}, cmd interface{}, arguments ...interface{}) *MockUserHost_PipeRun_Call {
	return &MockUserHost_PipeRun_Call{Call: _e.mock.On("PipeRun",
		append([]interface{}{stdin, combined, cmd}, arguments...)...)}
}

func (_c *MockUserHost_PipeRun_Call) Run(run func(stdin io.Reader, combined bool, cmd string, arguments ...string)) *MockUserHost_PipeRun_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 io.Reader
		if args[0] != nil {
			arg0 = args[0].(io.Reader)
		}
		var arg1 bool
		if args[1] != nil {
			arg1 = args[1].(bool)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 []string
		var variadicArgs []string
		if len(args) > 3 {
			variadicArgs = args[3].([]string)
		}
		arg3 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3...,
		)
	})
	return _c
}

func (_c *MockUserHost_PipeRun_Call) Return(bytes []byte, err error) *MockUserHost_PipeRun_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockUserHost_PipeRun_Call) RunAndReturn(run func(stdin io.Reader, combined bool, cmd string, arguments ...string) ([]byte, error)) *MockUserHost_PipeRun_Call {
	_c.Call.Return(run)
	return _c
}

// ReadDir provides a mock function for the type MockUserHost
func (_mock *MockUserHost) ReadDir(dirname string) ([]os.FileInfo, error) {
	ret := _mock.Called(dirname)

	if len(ret) == 0 {
		panic("no return value specified for ReadDir")
	}

	var r0 []os.FileInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) ([]os.FileInfo, error)); ok {
		return returnFunc(dirname)
	}
	if returnFunc, ok := ret.Get(0).(func(string) []os.FileInfo); ok {
		r0 = returnFunc(dirname)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]os.FileInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(dirname)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserHost_ReadDir_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadDir'
type MockUserHost_ReadDir_Call struct {
	*mock.Call
}

// ReadDir is a helper method to define mock.On call
//   - dirname string
func (_e *MockUserHost_Expecter) ReadDir(dirname interface{}) *MockUserHost_ReadDir_Call {
	return &MockUserHost_ReadDir_Call{Call: _e.mock.On("ReadDir", dirname)}
}

func (_c *MockUserHost_ReadDir_Call) Run(run func(dirname string)) *MockUserHost_ReadDir_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockUserHost_ReadDir_Call) Return(vs []os.FileInfo, err error) *MockUserHost_ReadDir_Call {
	_c.Call.Return(vs, err)
	return _c
}

func (_c *MockUserHost_ReadDir_Call) RunAndReturn(run func(dirname string) ([]os.FileInfo, error)) *MockUserHost_ReadDir_Call {
	_c.Call.Return(run)
	return _c
}

// ReadFile provides a mock function for the type MockUserHost
func (_mock *MockUserHost) ReadFile(path string) ([]byte, error) {
	ret := _mock.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for ReadFile")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) ([]byte, error)); ok {
		return returnFunc(path)
	}
	if returnFunc, ok := ret.Get(0).(func(string) []byte); ok {
		r0 = returnFunc(path)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(path)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserHost_ReadFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadFile'
type MockUserHost_ReadFile_Call struct {
	*mock.Call
}

// ReadFile is a helper method to define mock.On call
//   - path string
func (_e *MockUserHost_Expecter) ReadFile(path interface{}) *MockUserHost_ReadFile_Call {
	return &MockUserHost_ReadFile_Call{Call: _e.mock.On("ReadFile", path)}
}

func (_c *MockUserHost_ReadFile_Call) Run(run func(path string)) *MockUserHost_ReadFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockUserHost_ReadFile_Call) Return(bytes []byte, err error) *MockUserHost_ReadFile_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockUserHost_ReadFile_Call) RunAndReturn(run func(path string) ([]byte, error)) *MockUserHost_ReadFile_Call {
	_c.Call.Return(run)
	return _c
}

// Remove provides a mock function for the type MockUserHost
func (_mock *MockUserHost) Remove(path string) error {
	ret := _mock.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for Remove")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(path)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserHost_Remove_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Remove'
type MockUserHost_Remove_Call struct {
	*mock.Call
}

// Remove is a helper method to define mock.On call
//   - path string
func (_e *MockUserHost_Expecter) Remove(path interface{}) *MockUserHost_Remove_Call {
	return &MockUserHost_Remove_Call{Call: _e.mock.On("Remove", path)}
}

func (_c *MockUserHost_Remove_Call) Run(run func(path string)) *MockUserHost_Remove_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockUserHost_Remove_Call) Return(err error) *MockUserHost_Remove_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserHost_Remove_Call) RunAndReturn(run func(path string) error) *MockUserHost_Remove_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveAll provides a mock function for the type MockUserHost
func (_mock *MockUserHost) RemoveAll(path string) error {
	ret := _mock.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for RemoveAll")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(path)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserHost_RemoveAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveAll'
type MockUserHost_RemoveAll_Call struct {
	*mock.Call
}

// RemoveAll is a helper method to define mock.On call
//   - path string
func (_e *MockUserHost_Expecter) RemoveAll(path interface{}) *MockUserHost_RemoveAll_Call {
	return &MockUserHost_RemoveAll_Call{Call: _e.mock.On("RemoveAll", path)}
}

func (_c *MockUserHost_RemoveAll_Call) Run(run func(path string)) *MockUserHost_RemoveAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockUserHost_RemoveAll_Call) Return(err error) *MockUserHost_RemoveAll_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserHost_RemoveAll_Call) RunAndReturn(run func(path string) error) *MockUserHost_RemoveAll_Call {
	_c.Call.Return(run)
	return _c
}

// Rename provides a mock function for the type MockUserHost
func (_mock *MockUserHost) Rename(oldPath string, newPath string) error {
	ret := _mock.Called(oldPath, newPath)

	if len(ret) == 0 {
		panic("no return value specified for Rename")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = returnFunc(oldPath, newPath)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserHost_Rename_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Rename'
type MockUserHost_Rename_Call struct {
	*mock.Call
}

// Rename is a helper method to define mock.On call
//   - oldPath string
//   - newPath string
func (_e *MockUserHost_Expecter) Rename(oldPath interface{}, newPath interface{}) *MockUserHost_Rename_Call {
	return &MockUserHost_Rename_Call{Call: _e.mock.On("Rename", oldPath, newPath)}
}

func (_c *MockUserHost_Rename_Call) Run(run func(oldPath string, newPath string)) *MockUserHost_Rename_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserHost_Rename_Call) Return(err error) *MockUserHost_Rename_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserHost_Rename_Call) RunAndReturn(run func(oldPath string, newPath string) error) *MockUserHost_Rename_Call {
	_c.Call.Return(run)
	return _c
}

// Run provides a mock function for the type MockUserHost
func (_mock *MockUserHost) Run(combined bool, cmd string, arguments ...string) ([]byte, error) {
	var tmpRet mock.Arguments
	if len(arguments) > 0 {
		tmpRet = _mock.Called(combined, cmd, arguments)
	} else {
		tmpRet = _mock.Called(combined, cmd)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Run")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(bool, string, ...string) ([]byte, error)); ok {
		return returnFunc(combined, cmd, arguments...)
	}
	if returnFunc, ok := ret.Get(0).(func(bool, string, ...string) []byte); ok {
		r0 = returnFunc(combined, cmd, arguments...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(bool, string, ...string) error); ok {
		r1 = returnFunc(combined, cmd, arguments...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserHost_Run_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Run'
type MockUserHost_Run_Call struct {
	*mock.Call
}

// Run is a helper method to define mock.On call
//   - combined bool
//   - cmd string
//   - arguments ...string
func (_e *MockUserHost_Expecter) Run(combined interface{}, cmd interface{}, arguments ...interface{}) *MockUserHost_Run_Call {
	return &MockUserHost_Run_Call{Call: _e.mock.On("Run",
		append([]interface{}{combined, cmd}, arguments...)...)}
}

func (_c *MockUserHost_Run_Call) Run(run func(combined bool, cmd string, arguments ...string)) *MockUserHost_Run_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 bool
		if args[0] != nil {
			arg0 = args[0].(bool)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []string
		var variadicArgs []string
		if len(args) > 2 {
			variadicArgs = args[2].([]string)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockUserHost_Run_Call) Return(bytes []byte, err error) *MockUserHost_Run_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockUserHost_Run_Call) RunAndReturn(run func(combined bool, cmd string, arguments ...string) ([]byte, error)) *MockUserHost_Run_Call {
	_c.Call.Return(run)
	return _c
}

// RunCommand provides a mock function for the type MockUserHost
func (_mock *MockUserHost) RunCommand(ctx context.Context, options *host.CommandOptions) error {
	ret := _mock.Called(ctx, options)

	if len(ret) == 0 {
		panic("no return value specified for RunCommand")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *host.CommandOptions) error); ok {
		r0 = returnFunc(ctx, options)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserHost_RunCommand_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RunCommand'
type MockUserHost_RunCommand_Call struct {
	*mock.Call
}

// RunCommand is a helper method to define mock.On call
//   - ctx context.Context
//   - options *host.CommandOptions
func (_e *MockUserHost_Expecter) RunCommand(ctx interface{}, options interface{}) *MockUserHost_RunCommand_Call {
	return &MockUserHost_RunCommand_Call{Call: _e.mock.On("RunCommand", ctx, options)}
}

func (_c *MockUserHost_RunCommand_Call) Run(run func(ctx context.Context, options *host.CommandOptions)) *MockUserHost_RunCommand_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *host.CommandOptions
		if args[1] != nil {
			arg1 = args[1].(*host.CommandOptions)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserHost_RunCommand_Call) Return(err error) *MockUserHost_RunCommand_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserHost_RunCommand_Call) RunAndReturn(run func(ctx context.Context, options *host.CommandOptions) error) *MockUserHost_RunCommand_Call {
	_c.Call.Return(run)
	return _c
}

// Setenv provides a mock function for the type MockUserHost
func (_mock *MockUserHost) Setenv(key string, value string) error {
	ret := _mock.Called(key, value)

	if len(ret) == 0 {
		panic("no return value specified for Setenv")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = returnFunc(key, value)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserHost_Setenv_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Setenv'
type MockUserHost_Setenv_Call struct {
	*mock.Call
}

// Setenv is a helper method to define mock.On call
//   - key string
//   - value string
func (_e *MockUserHost_Expecter) Setenv(key interface{}, value interface{}) *MockUserHost_Setenv_Call {
	return &MockUserHost_Setenv_Call{Call: _e.mock.On("Setenv", key, value)}
}

func (_c *MockUserHost_Setenv_Call) Run(run func(key string, value string)) *MockUserHost_Setenv_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserHost_Setenv_Call) Return(err error) *MockUserHost_Setenv_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserHost_Setenv_Call) RunAndReturn(run func(key string, value string) error) *MockUserHost_Setenv_Call {
	_c.Call.Return(run)
	return _c
}

// StartCommand provides a mock function for the type MockUserHost
func (_mock *MockUserHost) StartCommand(ctx context.Context, options *host.CommandOptions) (host.Process, error) {
	ret := _mock.Called(ctx, options)

	if len(ret) == 0 {
		panic("no return value specified for StartCommand")
	}

	var r0 host.Process
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *host.CommandOptions) (host.Process, error)); ok {
		return returnFunc(ctx, options)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *host.CommandOptions) host.Process); ok {
		r0 = returnFunc(ctx, options)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(host.Process)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *host.CommandOptions) error); ok {
		r1 = returnFunc(ctx, options)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserHost_StartCommand_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StartCommand'
type MockUserHost_StartCommand_Call struct {
	*mock.Call
}

// StartCommand is a helper method to define mock.On call
//   - ctx context.Context
//   - options *host.CommandOptions
func (_e *MockUserHost_Expecter) StartCommand(ctx interface{}, options interface{}) *MockUserHost_StartCommand_Call {
	return &MockUserHost_StartCommand_Call{Call: _e.mock.On("StartCommand", ctx, options)}
}

func (_c *MockUserHost_StartCommand_Call) Run(run func(ctx context.Context, options *host.CommandOptions)) *MockUserHost_StartCommand_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *host.CommandOptions
		if args[1] != nil {
			arg1 = args[1].(*host.CommandOptions)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserHost_StartCommand_Call) Return(process host.Process, err error) *MockUserHost_StartCommand_Call {
	_c.Call.Return(process, err)
	return _c
}

func (_c *MockUserHost_StartCommand_Call) RunAndReturn(run func(ctx context.Context, options *host.CommandOptions) (host.Process, error)) *MockUserHost_StartCommand_Call {
	_c.Call.Return(run)
	return _c
}

// Stat provides a mock function for the type MockUserHost
func (_mock *MockUserHost) Stat(path string) (os.FileInfo, error) {
	ret := _mock.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for Stat")
	}

	var r0 os.FileInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (os.FileInfo, error)); ok {
		return returnFunc(path)
	}
	if returnFunc, ok := ret.Get(0).(func(string) os.FileInfo); ok {
		r0 = returnFunc(path)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(os.FileInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(path)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserHost_Stat_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stat'
type MockUserHost_Stat_Call struct {
	*mock.Call
}

// Stat is a helper method to define mock.On call
//   - path string
func (_e *MockUserHost_Expecter) Stat(path interface{}) *MockUserHost_Stat_Call {
	return &MockUserHost_Stat_Call{Call: _e.mock.On("Stat", path)}
}

func (_c *MockUserHost_Stat_Call) Run(run func(path string)) *MockUserHost_Stat_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockUserHost_Stat_Call) Return(v os.FileInfo, err error) *MockUserHost_Stat_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockUserHost_Stat_Call) RunAndReturn(run func(path string) (os.FileInfo, error)) *MockUserHost_Stat_Call {
	_c.Call.Return(run)
	return _c
}

// Symlink provides a mock function for the type MockUserHost
func (_mock *MockUserHost) Symlink(oldName string, newName string) error {
	ret := _mock.Called(oldName, newName)

	if len(ret) == 0 {
		panic("no return value specified for Symlink")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = returnFunc(oldName, newName)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserHost_Symlink_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Symlink'
type MockUserHost_Symlink_Call struct {
	*mock.Call
}

// Symlink is a helper method to define mock.On call
//   - oldName string
//   - newName string
func (_e *MockUserHost_Expecter) Symlink(oldName interface{}, newName interface{}) *MockUserHost_Symlink_Call {
	return &MockUserHost_Symlink_Call{Call: _e.mock.On("Symlink", oldName, newName)}
}

func (_c *MockUserHost_Symlink_Call) Run(run func(oldName string, newName string)) *MockUserHost_Symlink_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserHost_Symlink_Call) Return(err error) *MockUserHost_Symlink_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserHost_Symlink_Call) RunAndReturn(run func(oldName string, newName string) error) *MockUserHost_Symlink_Call {
	_c.Call.Return(run)
	return _c
}

// UserConfigDir provides a mock function for the type MockUserHost
func (_mock *MockUserHost) UserConfigDir() (string, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for UserConfigDir")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (string, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserHost_UserConfigDir_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UserConfigDir'
type MockUserHost_UserConfigDir_Call struct {
	*mock.Call
}

// UserConfigDir is a helper method to define mock.On call
func (_e *MockUserHost_Expecter) UserConfigDir() *MockUserHost_UserConfigDir_Call {
	return &MockUserHost_UserConfigDir_Call{Call: _e.mock.On("UserConfigDir")}
}

func (_c *MockUserHost_UserConfigDir_Call) Run(run func()) *MockUserHost_UserConfigDir_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockUserHost_UserConfigDir_Call) Return(s string, err error) *MockUserHost_UserConfigDir_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockUserHost_UserConfigDir_Call) RunAndReturn(run func() (string, error)) *MockUserHost_UserConfigDir_Call {
	_c.Call.Return(run)
	return _c
}

// UserHomeDir provides a mock function for the type MockUserHost
func (_mock *MockUserHost) UserHomeDir() (string, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for UserHomeDir")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (string, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserHost_UserHomeDir_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UserHomeDir'
type MockUserHost_UserHomeDir_Call struct {
	*mock.Call
}

// UserHomeDir is a helper method to define mock.On call
func (_e *MockUserHost_Expecter) UserHomeDir() *MockUserHost_UserHomeDir_Call {
	return &MockUserHost_UserHomeDir_Call{Call: _e.mock.On("UserHomeDir")}
}

func (_c *MockUserHost_UserHomeDir_Call) Run(run func()) *MockUserHost_UserHomeDir_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockUserHost_UserHomeDir_Call) Return(s string, err error) *MockUserHost_UserHomeDir_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockUserHost_UserHomeDir_Call) RunAndReturn(run func() (string, error)) *MockUserHost_UserHomeDir_Call {
	_c.Call.Return(run)
	return _c
}

// Walk provides a mock function for the type MockUserHost
func (_mock *MockUserHost) Walk(root string, walkFn filepath.WalkFunc) error {
	ret := _mock.Called(root, walkFn)

	if len(ret) == 0 {
		panic("no return value specified for Walk")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, filepath.WalkFunc) error); ok {
		r0 = returnFunc(root, walkFn)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserHost_Walk_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Walk'
type MockUserHost_Walk_Call struct {
	*mock.Call
}

// Walk is a helper method to define mock.On call
//   - root string
//   - walkFn filepath.WalkFunc
func (_e *MockUserHost_Expecter) Walk(root interface{}, walkFn interface{}) *MockUserHost_Walk_Call {
	return &MockUserHost_Walk_Call{Call: _e.mock.On("Walk", root, walkFn)}
}

func (_c *MockUserHost_Walk_Call) Run(run func(root string, walkFn filepath.WalkFunc)) *MockUserHost_Walk_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 filepath.WalkFunc
		if args[1] != nil {
			arg1 = args[1].(filepath.WalkFunc)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserHost_Walk_Call) Return(err error) *MockUserHost_Walk_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserHost_Walk_Call) RunAndReturn(run func(root string, walkFn filepath.WalkFunc) error) *MockUserHost_Walk_Call {
	_c.Call.Return(run)
	return _c
}

// WriteFile provides a mock function for the type MockUserHost
func (_mock *MockUserHost) WriteFile(path string, data []byte, perm os.FileMode) error {
	ret := _mock.Called(path, data, perm)

	if len(ret) == 0 {
		panic("no return value specified for WriteFile")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, []byte, os.FileMode) error); ok {
		r0 = returnFunc(path, data, perm)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserHost_WriteFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WriteFile'
type MockUserHost_WriteFile_Call struct {
	*mock.Call
}

// WriteFile is a helper method to define mock.On call
//   - path string
//   - data []byte
//   - perm os.FileMode
func (_e *MockUserHost_Expecter) WriteFile(path interface{}, data interface{}, perm interface{}) *MockUserHost_WriteFile_Call {
	return &MockUserHost_WriteFile_Call{Call: _e.mock.On("WriteFile", path, data, perm)}
}

func (_c *MockUserHost_WriteFile_Call) Run(run func(path string, data []byte, perm os.FileMode)) *MockUserHost_WriteFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []byte
		if args[1] != nil {
			arg1 = args[1].([]byte)
		}
		var arg2 os.FileMode
		if args[2] != nil {
			arg2 = args[2].(os.FileMode)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUserHost_WriteFile_Call) Return(err error) *MockUserHost_WriteFile_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserHost_WriteFile_Call) RunAndReturn(run func(path string, data []byte, perm os.FileMode) error) *MockUserHost_WriteFile_Call {
	_c.Call.Return(run)
	return _c
}

// WritePipe provides a mock function for the type MockUserHost
func (_mock *MockUserHost) WritePipe(path string, pipe *script.Pipe, flag int, perm os.FileMode) (int64, error) {
	ret := _mock.Called(path, pipe, flag, perm)

	if len(ret) == 0 {
		panic("no return value specified for WritePipe")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, *script.Pipe, int, os.FileMode) (int64, error)); ok {
		return returnFunc(path, pipe, flag, perm)
	}
	if returnFunc, ok := ret.Get(0).(func(string, *script.Pipe, int, os.FileMode) int64); ok {
		r0 = returnFunc(path, pipe, flag, perm)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(string, *script.Pipe, int, os.FileMode) error); ok {
		r1 = returnFunc(path, pipe, flag, perm)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserHost_WritePipe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WritePipe'
type MockUserHost_WritePipe_Call struct {
	*mock.Call
}

// WritePipe is a helper method to define mock.On call
//   - path string
//   - pipe *script.Pipe
//   - flag int
//   - perm os.FileMode
func (_e *MockUserHost_Expecter) WritePipe(path interface{}, pipe interface{}, flag interface{}, perm interface{}) *MockUserHost_WritePipe_Call {
	return &MockUserHost_WritePipe_Call{Call: _e.mock.On("WritePipe", path, pipe, flag, perm)}
}

func (_c *MockUserHost_WritePipe_Call) Run(run func(path string, pipe *script.Pipe, flag int, perm os.FileMode)) *MockUserHost_WritePipe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 *script.Pipe
		if args[1] != nil {
			arg1 = args[1].(*script.Pipe)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 os.FileMode
		if args[3] != nil {
			arg3 = args[3].(os.FileMode)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockUserHost_WritePipe_Call) Return(n int64, err error) *MockUserHost_WritePipe_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockUserHost_WritePipe_Call) RunAndReturn(run func(path string, pipe *script.Pipe, flag int, perm os.FileMode) (int64, error)) *MockUserHost_WritePipe_Call {
	_c.Call.Return(run)
	return _c
}
