# cSpell: words gomod
version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      "go-modules":
        patterns:
          - "*" # Group all Go modules dependencies together
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      "github-actions":
        patterns:
          - "*" # Group all GitHub Actions dependencies together
  - package-ecosystem: "docker"
    directories:
      - /packaging/rootfs/base
      - /hack/cicontainer
      - /hack/devcontainer
    schedule:
      interval: "daily"
    groups:
      "docker":
        patterns:
          - "*" # Group all Docker dependencies together
  - package-ecosystem: "opentofu"
    directories:
      - "/deploy/iac/modules/*"
    schedule:
      interval: "daily"
    groups:
      "opentofu":
        patterns:
          - "*" # Group all OpenTofu dependencies together
