# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
# cSpell: disable
env:
  - KUBERNETES_VERSION=1.26.0
before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - "386"
      - amd64
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X
        main.date={{ .CommitDate }} -X main.builtBy=pterm -X
        k8s.KubernetesVersion={{ .Env.KUBERNETES_VERSION }}
    binary: iknite
    id: iknite
archives:
  - name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
checksum:
  name_template: SHA256SUMS
snapshot:
  name_template: "{{ incpatch .Version }}-devel"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs"
      - "^test"
      - "^ci"
      - "^refactor"
      - Merge pull request
      - Merge branch
      - go mod tidy
nfpms:
  - formats: [apk]
    license: Apache 2.0
    package_name: iknite
    file_name_template: >-
      {{ .PackageName }}-
      {{- .Version }}.
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
      {{- if .Mips }}_{{ .Mips }}{{ end }}
    maintainer: Kaweezle <kaweezle-devel@kaweezle.com>
    description: Start Kubernetes in Alpine Linux
    homepage: https://github.com/kaweezle/iknite
    dependencies:
      - openrc
      - ip6tables
      - containerd
      - kubelet
      - kubeadm
      - kubectl
      - cni-plugins
      - cni-plugin-flannel
      - flannel
      - git
      - util-linux-misc
    bindir: /sbin
    contents:
      - src: apk/crictl.sh
        dst: /etc/profile.d/crictl.sh
      - src: apk/iknite.d/kustomization.yaml
        dst: /etc/iknite.d/kustomization.yaml
      - src: apk/iknite.d/base/kustomization.yaml
        dst: /etc/iknite.d/base/kustomization.yaml
      - src: apk/iknite.d/base/metallb-addresspool.yaml
        dst: /etc/iknite.d/base/metallb-addresspool.yaml
      - src: apk/init.d/iknite-mdns
        dst: /etc/init.d/iknite-mdns
      - src: apk/init.d/iknite-init
        dst: /etc/init.d/iknite-init
      - src: apk/init.d/iknite-config
        dst: /etc/init.d/iknite-config
      - src: apk/conf.d/iknite-init
        dst: /etc/conf.d/iknite-init
      - src: apk/conf.d/iknite-config
        dst: /etc/conf.d/iknite-config
      - src: apk/iknite-killall.sh
        dst: /sbin/iknite-killall.sh
      - src: apk/flannel/10-flannel.conflist
        dst: /etc/cni/net.d/10-flannel.conflist
      - src: apk/flannel/subnet.env
        dst: /lib/iknite/flannel/subnet.env
    apk:
      signature:
        key_file: gpg_key.asc
        key_name: kaweezle-devel@kaweezle.com-c9d89864.rsa.pub
release:
  extra_files:
    - glob: ./kaweezle-devel@kaweezle.com-c9d89864.rsa.pub
