# cSpell: disable
# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
version: 2
env:
  - KUBERNETES_VERSION={{ if index .Env "KUBERNETES_VERSION"  }}{{ .Env.KUBERNETES_VERSION }}{{ else }}1.34.3{{ end }}
before:
  hooks:
    - go mod tidy
builds:
  - main: ./cmd/iknite/iknite.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - "386"
      - amd64
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X
        main.date={{ .CommitDate }} -X main.builtBy=pterm -X
        github.com/kaweezle/iknite/pkg/apis/iknite/v1alpha1.KubernetesVersionDefault={{ .Env.KUBERNETES_VERSION }}
    binary: iknite
    id: iknite
archives:
  - name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
checksum:
  name_template: SHA256SUMS
snapshot:
  version_template: "{{ incpatch .Version }}-devel"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs"
      - "^test"
      - "^ci"
      - "^refactor"
      - Merge pull request
      - Merge branch
      - go mod tidy
nfpms:
  - formats: [apk]
    license: Apache 2.0
    package_name: iknite
    file_name_template: >-
      {{ .PackageName }}-
      {{- .Version }}.
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
      {{- if .Mips }}_{{ .Mips }}{{ end }}
    maintainer: Kaweezle <kaweezle-devel@kaweezle.com>
    description: Start Kubernetes in Alpine Linux
    homepage: https://github.com/kaweezle/iknite
    dependencies:
      - openrc
      - ip6tables
      - containerd
      - kubelet
      - kubeadm
      - kubectl
      - cni-plugins
      - cni-plugin-flannel
      - git
      - openssh
      - util-linux-misc
      - buildkit
      - buildctl
      - nerdctl
    bindir: /sbin
    contents:
      - src: apk/crictl.yaml
        dst: /etc/crictl.yaml
      - src: apk/iknite.d/kustomization.yaml
        dst: /etc/iknite.d/kustomization.yaml
      - src: apk/iknite.d/base/kustomization.yaml
        dst: /etc/iknite.d/base/kustomization.yaml
      - src: apk/iknite.d/base/kube-vip-addresspool.yaml
        dst: /etc/iknite.d/base/kube-vip-addresspool.yaml
      - src: apk/iknite.d/base/kube-flannel.yaml
        dst: /etc/iknite.d/base/kube-flannel.yaml
      - src: apk/iknite.d/base/coredns.yaml
        dst: /etc/iknite.d/base/coredns.yaml
      - src: apk/init.d/iknite
        dst: /etc/init.d/iknite
      - src: apk/conf.d/iknite
        dst: /etc/conf.d/iknite
      - src: apk/flannel/10-flannel.conflist
        dst: /etc/cni/net.d/10-flannel.conflist
      - src: apk/flannel/subnet.env
        dst: /lib/iknite/flannel/subnet.env
      - src: apk/buildkit/buildkitd.toml
        dst: /etc/buildkit/buildkitd.toml
    apk:
      signature:
        key_file: kaweezle-devel@kaweezle.com-c9d89864.rsa
        key_name: kaweezle-devel@kaweezle.com-c9d89864.rsa.pub
release:
  extra_files:
    - glob: ./kaweezle-devel@kaweezle.com-c9d89864.rsa.pub
