# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
env:
  - KUBERNETES_VERSION=1.23.1
before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - 386
      - amd64
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X
        main.date={{ .CommitDate }} -X main.builtBy=pterm -X
        k8s.KUBERNETES_VERSION={{ .Env.KUBERNETES_VERSION }}
    binary: iknite
archives:
  - name_template:
      "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    replacements:
      linux: Linux
      386: i386
      amd64: x86_64
checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"
snapshot:
  name_template: "{{ incpatch .Version }}-devel"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs"
      - "^test"
      - "^ci"
      - "^refactor"
      - Merge pull request
      - Merge branch
      - go mod tidy
nfpms:
  - formats: [apk]
    license: Apache 2.0
    package_name: iknite
    maintainer: Antoine Martin <antoine@openance.com>
    description: Start Kubernetes in Alpine Linux
    homepage: https://github.com/kaweezle/iknite
    dependencies:
      - cri-o
      - kubelet
      - kubeadm
      - kubectl
      - kubelet-openrc
      - cri-o-contrib-cni
    bindir: /sbin
