# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
env:
  - KUBERNETES_VERSION=1.24.3
before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - "386"
      - amd64
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X
        main.date={{ .CommitDate }} -X main.builtBy=pterm -X
        k8s.KubernetesVersion={{ .Env.KUBERNETES_VERSION }}
    binary: iknite
    id: iknite
archives:
  - name_template:
      "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    replacements:
      linux: Linux
      386: i386
      amd64: x86_64
checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"
snapshot:
  name_template: "{{ incpatch .Version }}-devel"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs"
      - "^test"
      - "^ci"
      - "^refactor"
      - Merge pull request
      - Merge branch
      - go mod tidy
nfpms:
  - formats: [apk]
    license: Apache 2.0
    package_name: iknite
    file_name_template:
      "{{ .PackageName }}-{{ .Version }}.{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{
      end }}{{ if .Mips }}_{{ .Mips }}{{ end }}"
    replacements:
      amd64: x86_64
      "386": x86
    maintainer: Kaweezle <kaweezle-devel@kaweezle.com>
    description: Start Kubernetes in Alpine Linux
    homepage: https://github.com/kaweezle/iknite
    dependencies:
      - openrc
      - ip6tables
      - cri-o
      - kubelet
      - kubeadm
      - kubectl
      - cri-o-contrib-cni
      - git
      - util-linux-misc
    bindir: /sbin
    contents:
      - src: apk/crictl.sh
        dst: /etc/profile.d/crictl.sh
      - src: apk/iknite.d/kustomization.yaml
        dst: /etc/iknite.d/kustomization.yaml
      - src: apk/iknite.d/base/kustomization.yaml
        dst: /etc/iknite.d/base/kustomization.yaml
      - src: apk/iknite.d/base/metallb-generator.yaml
        dst: /etc/iknite.d/base/metallb-generator.yaml
      - src: apk/iknite.d/base/plugins/metallb-config.sh
        dst: /etc/iknite.d/base/plugins/metallb-config.sh
    apk:
      signature:
        key_file: gpg_key.asc
        key_name: kaweezle-devel@kaweezle.com-c9d89864.rsa.pub
release:
  extra_files:
    - glob: ./kaweezle-devel@kaweezle.com-c9d89864.rsa.pub
