creation_rules:
  - path_regex: .*\.sops\.yaml
    encrypted_regex: "^data$"
    age: >-
      age1fs48f8rw9gj49ss5fapsy8euqln0dtrc5yg35fuq7c930jtkveps2swvt6,
      ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFRLqR8KKijMLsNZT92cc461KB9veSEQcGH5WHYkqOfG id_ed25519
stores:
  json:
    indent: 2
  json_binary:
    indent: 2
  yaml:
    indent: 2
