
apiVersion: v1
kind: Service
metadata:
  annotations:
    kube-vip.io/ignore: "true"
  name: argocd-gateway-test
  namespace: argocd
spec:
  allocateLoadBalancerNodePorts: false
  ports:
  - name: listener-80
    port: 80
    protocol: TCP
    targetPort: 80
  - name: listener-443
    port: 443
    protocol: TCP
    targetPort: 443
  selector:
    app.kubernetes.io/instance: argocd-gateway
    app.kubernetes.io/name: argocd-gateway
    gateway.networking.k8s.io/gateway-name: argocd-gateway
  type: LoadBalancer
  externalIPs:
  - 10.196.248.109
