apiVersion: autocloud.config.kaweezle.com/v1alpha1
kind: PlatformValues
metadata:
  name: iknite-values
data:
  domain_suffix: iknite.app
  project:
    name: Iknite
    slug: iknite
    email: antoine@mrtn.fr
    github:
      organization: kaweezle
      repo: iknite
      team: admin
      repoURL: git@github.com:kaweezle/iknite.git
      targetRevision: main
      basePath: deploy/k8s/argocd/e2e
  argocd:
    domain_prefix: argocd-e2e
    repo_server:
      image_name: ghcr.io/kaweezle/argocd-helmfile
      image_tag: v3.3.2-1.3.2-1
    base_path: deploy/k8s/argocd/e2e
    bootstrap_application: appstage-00-bootstrap
  cloudflare:
    account_id: a54f6b2557d54a9bff5eef36482b7fe6
  iac:
    state_bucket: kwzltfstate
    storage_provider: cloudflare
