apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-server
  namespace: argocd
  annotations:
    autocloud/local-application: "true"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  ignoreDifferences:
    - group: argoproj.io
      jsonPointers:
        - /status
      kind: Application
  project: default
  source:
    path: deploy/k8s/argocd/common/argocd-server
    repoURL: git@github.com:kaweezle/iknite.git
    targetRevision: feature/argocd-reorganization
    plugin:
      # Helmfile environment variables
      env:
        # We have resources in multiple namespaces
        - name: HELMFILE_USE_CONTEXT_NAMESPACE
          value: "true"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      # Needed in ArgoCD v3.3 https://argo-cd.readthedocs.io/en/stable/operator-manual/upgrading/3.2-3.3/#breaking-changes
      - ServerSideApply=true
