---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: metallb
  name: metallb-admin
  namespace: metallb-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: metallb-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: metallb-admin
  namespace: metallb-system
---
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app: metallb
  name: create-address-pools
  namespace: metallb-system
spec:
  ttlSecondsAfterFinished: 100
  backoffLimit: 3
  template:
    spec:
      serviceAccountName: metallb-admin
      automountServiceAccountToken: true
      restartPolicy: OnFailure
      containers:
      - name: create-address-pools
        image: boxboat/kubectl:1.25.0
        imagePullPolicy: IfNotPresent
        command:
        - /bin/sh
        - -c
        - |
            set -xe
            kubectl rollout status deployment/controller -n metallb-system
            ip=$(kubectl get nodes -o jsonpath='{range .items[*]}{range .status.addresses[*]}{.address}{"\n"}{end}{end}' | head -1)
            sleep 3
            cat - <<EOF | kubectl apply -f -
            apiVersion: metallb.io/v1beta1
            kind: IPAddressPool
            metadata:
                name: node-ip-pool
                namespace: metallb-system
            spec:
                addresses:
                - $ip/32
            ---
            apiVersion: metallb.io/v1beta1
            kind: L2Advertisement
            metadata:
                name: advertisement
                namespace: metallb-system
            EOF
