/*
Copyright © 2021 Antoine Martin <antoine@openance.com>

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

	http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
package cmd

// cSpell: words clientcmd sirupsen

import (
	"context"
	"fmt"
	"os"
	"path/filepath"

	"github.com/spf13/cobra"
	"k8s.io/client-go/rest"

	"github.com/kaweezle/iknite/pkg/k8s"
)

// ikniteConfigFlag is the flag name for the iknite client config path.
const ikniteConfigFlag = "config"

// defaultIkniteConf returns the default path for the iknite client config file:
// $HOME/.kube/iknite.conf.
func defaultIkniteConf() string {
	home, err := os.UserHomeDir()
	if err != nil {
		return ""
	}
	return filepath.Join(home, ".kube", "iknite.conf")
}

// NewInfoStatusCmd returns the "info status" subcommand. It retrieves the
// cluster status from the running iknite HTTPS server using the mTLS client
// configuration written to /etc/kubernetes/iknite.conf during initialization.
func NewInfoStatusCmd() *cobra.Command {
	var configPath string

	statusCmd := &cobra.Command{
		Use:   "status",
		Short: "Retrieves the cluster status from the iknite status server",
		Long: `Retrieves the cluster status from the iknite HTTPS status server.

The command uses a kubeconfig-style file that is generated by iknite during
cluster initialization at /etc/kubernetes/iknite.conf. Copy that file to
$HOME/.kube/iknite.conf (or point --config at it) to use this command from
a remote host.`,
		RunE: func(_ *cobra.Command, _ []string) error {
			return performInfoStatus(configPath)
		},
	}

	statusCmd.Flags().StringVar(
		&configPath,
		ikniteConfigFlag,
		defaultIkniteConf(),
		"Path to the iknite client configuration file (default: $HOME/.kube/iknite.conf)",
	)

	return statusCmd
}

// performInfoStatus loads the iknite client configuration from configPath,
// builds an mTLS HTTP client from the embedded credentials, and prints the
// JSON response from the /status endpoint.
func performInfoStatus(configPath string) error {
	kubeConfig, err := k8s.LoadFromFile(configPath)
	if err != nil {
		return fmt.Errorf("failed to load iknite config from %s: %w", configPath, err)
	}

	var restClient rest.Interface
	if restClient, err = kubeConfig.NewRESTClient(); err != nil {
		return fmt.Errorf("failed to create REST client: %w", err)
	}

	req := restClient.Get().AbsPath("/status")
	body, err := req.DoRaw(context.Background())
	if err != nil {
		return fmt.Errorf("error while getting iknite status %s: %w", req.URL().String(), err)
	}

	fmt.Println(string(body)) //nolint:forbidigo // printing is expected here
	return nil
}
