/*
Copyright © 2021 Antoine Martin <antoine@openance.com>

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

	http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
package cmd

// cSpell: words clientcmd

import (
	"context"
	"crypto/tls"
	"crypto/x509"
	"fmt"
	"io"
	"net/http"
	"os"
	"path/filepath"
	"time"

	log "github.com/sirupsen/logrus"
	"github.com/spf13/cobra"
	"k8s.io/client-go/tools/clientcmd"
)

// ikniteConfigFlag is the flag name for the iknite client config path.
const ikniteConfigFlag = "config"

// defaultIkniteConf returns the default path for the iknite client config file:
// $HOME/.kube/iknite.conf.
func defaultIkniteConf() string {
	home, err := os.UserHomeDir()
	if err != nil {
		return ""
	}
	return filepath.Join(home, ".kube", "iknite.conf")
}

// NewInfoStatusCmd returns the "info status" subcommand. It retrieves the
// cluster status from the running iknite HTTPS server using the mTLS client
// configuration written to /etc/kubernetes/iknite.conf during initialisation.
func NewInfoStatusCmd() *cobra.Command {
	var configPath string

	statusCmd := &cobra.Command{
		Use:   "status",
		Short: "Retrieves the cluster status from the iknite status server",
		Long: `Retrieves the cluster status from the iknite HTTPS status server.

The command uses a kubeconfig-style file that is generated by iknite during
cluster initialisation at /etc/kubernetes/iknite.conf. Copy that file to
$HOME/.kube/iknite.conf (or point --config at it) to use this command from
a remote host.`,
		RunE: func(_ *cobra.Command, _ []string) error {
			return performInfoStatus(configPath)
		},
	}

	statusCmd.Flags().StringVar(
		&configPath,
		ikniteConfigFlag,
		defaultIkniteConf(),
		"Path to the iknite client configuration file (default: $HOME/.kube/iknite.conf)",
	)

	return statusCmd
}

// performInfoStatus loads the iknite client configuration from configPath,
// builds an mTLS HTTP client from the embedded credentials, and prints the
// JSON response from the /status endpoint.
func performInfoStatus(configPath string) error {
	kubeConfig, err := clientcmd.LoadFromFile(configPath)
	if err != nil {
		return fmt.Errorf("failed to load iknite config from %s: %w", configPath, err)
	}

	currentContext := kubeConfig.Contexts[kubeConfig.CurrentContext]
	if currentContext == nil {
		return fmt.Errorf("no current context in %s", configPath)
	}

	cluster := kubeConfig.Clusters[currentContext.Cluster]
	if cluster == nil {
		return fmt.Errorf("cluster %q not found in %s", currentContext.Cluster, configPath)
	}

	authInfo := kubeConfig.AuthInfos[currentContext.AuthInfo]
	if authInfo == nil {
		return fmt.Errorf("user %q not found in %s", currentContext.AuthInfo, configPath)
	}

	caPool := x509.NewCertPool()
	if !caPool.AppendCertsFromPEM(cluster.CertificateAuthorityData) {
		return fmt.Errorf("failed to parse CA cert from %s", configPath)
	}

	clientCert, err := tls.X509KeyPair(authInfo.ClientCertificateData, authInfo.ClientKeyData)
	if err != nil {
		return fmt.Errorf("failed to parse client credentials from %s: %w", configPath, err)
	}

	tlsConfig := &tls.Config{
		Certificates: []tls.Certificate{clientCert},
		RootCAs:      caPool,
		MinVersion:   tls.VersionTLS12,
	}
	httpClient := &http.Client{
		Transport: &http.Transport{TLSClientConfig: tlsConfig},
		Timeout:   10 * time.Second,
	}

	url := cluster.Server + "/status"
	req, err := http.NewRequestWithContext(context.Background(), http.MethodGet, url, nil)
	if err != nil {
		return fmt.Errorf("failed to create request: %w", err)
	}

	resp, err := httpClient.Do(req)
	if err != nil {
		return fmt.Errorf("failed to contact iknite status server at %s: %w", url, err)
	}
	defer func() {
		if closeErr := resp.Body.Close(); closeErr != nil {
			log.WithError(closeErr).Debug("failed to close iknite status response body")
		}
	}()

	if resp.StatusCode != http.StatusOK {
		return fmt.Errorf("iknite status server returned %s", resp.Status)
	}

	body, err := io.ReadAll(resp.Body)
	if err != nil {
		return fmt.Errorf("failed to read response from iknite status server: %w", err)
	}

	fmt.Println(string(body)) //nolint:forbidigo // printing is expected here
	return nil
}
