// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package checkers

import (
	"time"

	"github.com/kaweezle/iknite/pkg/apis/iknite/v1alpha1"
	"github.com/kaweezle/iknite/pkg/host"
	"github.com/kaweezle/iknite/pkg/utils"
	mock "github.com/stretchr/testify/mock"
)

// NewMockCheckWorkloadData creates a new instance of MockCheckWorkloadData. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCheckWorkloadData(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCheckWorkloadData {
	mock := &MockCheckWorkloadData{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCheckWorkloadData is an autogenerated mock type for the CheckWorkloadData type
type MockCheckWorkloadData struct {
	mock.Mock
}

type MockCheckWorkloadData_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCheckWorkloadData) EXPECT() *MockCheckWorkloadData_Expecter {
	return &MockCheckWorkloadData_Expecter{mock: &_m.Mock}
}

// ApiAdvertiseAddress provides a mock function for the type MockCheckWorkloadData
func (_mock *MockCheckWorkloadData) ApiAdvertiseAddress() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ApiAdvertiseAddress")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockCheckWorkloadData_ApiAdvertiseAddress_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ApiAdvertiseAddress'
type MockCheckWorkloadData_ApiAdvertiseAddress_Call struct {
	*mock.Call
}

// ApiAdvertiseAddress is a helper method to define mock.On call
func (_e *MockCheckWorkloadData_Expecter) ApiAdvertiseAddress() *MockCheckWorkloadData_ApiAdvertiseAddress_Call {
	return &MockCheckWorkloadData_ApiAdvertiseAddress_Call{Call: _e.mock.On("ApiAdvertiseAddress")}
}

func (_c *MockCheckWorkloadData_ApiAdvertiseAddress_Call) Run(run func()) *MockCheckWorkloadData_ApiAdvertiseAddress_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCheckWorkloadData_ApiAdvertiseAddress_Call) Return(s string) *MockCheckWorkloadData_ApiAdvertiseAddress_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockCheckWorkloadData_ApiAdvertiseAddress_Call) RunAndReturn(run func() string) *MockCheckWorkloadData_ApiAdvertiseAddress_Call {
	_c.Call.Return(run)
	return _c
}

// Duration provides a mock function for the type MockCheckWorkloadData
func (_mock *MockCheckWorkloadData) Duration() time.Duration {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Duration")
	}

	var r0 time.Duration
	if returnFunc, ok := ret.Get(0).(func() time.Duration); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(time.Duration)
	}
	return r0
}

// MockCheckWorkloadData_Duration_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Duration'
type MockCheckWorkloadData_Duration_Call struct {
	*mock.Call
}

// Duration is a helper method to define mock.On call
func (_e *MockCheckWorkloadData_Expecter) Duration() *MockCheckWorkloadData_Duration_Call {
	return &MockCheckWorkloadData_Duration_Call{Call: _e.mock.On("Duration")}
}

func (_c *MockCheckWorkloadData_Duration_Call) Run(run func()) *MockCheckWorkloadData_Duration_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCheckWorkloadData_Duration_Call) Return(duration time.Duration) *MockCheckWorkloadData_Duration_Call {
	_c.Call.Return(duration)
	return _c
}

func (_c *MockCheckWorkloadData_Duration_Call) RunAndReturn(run func() time.Duration) *MockCheckWorkloadData_Duration_Call {
	_c.Call.Return(run)
	return _c
}

// Host provides a mock function for the type MockCheckWorkloadData
func (_mock *MockCheckWorkloadData) Host() host.Host {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Host")
	}

	var r0 host.Host
	if returnFunc, ok := ret.Get(0).(func() host.Host); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(host.Host)
		}
	}
	return r0
}

// MockCheckWorkloadData_Host_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Host'
type MockCheckWorkloadData_Host_Call struct {
	*mock.Call
}

// Host is a helper method to define mock.On call
func (_e *MockCheckWorkloadData_Expecter) Host() *MockCheckWorkloadData_Host_Call {
	return &MockCheckWorkloadData_Host_Call{Call: _e.mock.On("Host")}
}

func (_c *MockCheckWorkloadData_Host_Call) Run(run func()) *MockCheckWorkloadData_Host_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCheckWorkloadData_Host_Call) Return(host1 host.Host) *MockCheckWorkloadData_Host_Call {
	_c.Call.Return(host1)
	return _c
}

func (_c *MockCheckWorkloadData_Host_Call) RunAndReturn(run func() host.Host) *MockCheckWorkloadData_Host_Call {
	_c.Call.Return(run)
	return _c
}

// IkniteClusterSpec provides a mock function for the type MockCheckWorkloadData
func (_mock *MockCheckWorkloadData) IkniteClusterSpec() *v1alpha1.IkniteClusterSpec {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for IkniteClusterSpec")
	}

	var r0 *v1alpha1.IkniteClusterSpec
	if returnFunc, ok := ret.Get(0).(func() *v1alpha1.IkniteClusterSpec); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1alpha1.IkniteClusterSpec)
		}
	}
	return r0
}

// MockCheckWorkloadData_IkniteClusterSpec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IkniteClusterSpec'
type MockCheckWorkloadData_IkniteClusterSpec_Call struct {
	*mock.Call
}

// IkniteClusterSpec is a helper method to define mock.On call
func (_e *MockCheckWorkloadData_Expecter) IkniteClusterSpec() *MockCheckWorkloadData_IkniteClusterSpec_Call {
	return &MockCheckWorkloadData_IkniteClusterSpec_Call{Call: _e.mock.On("IkniteClusterSpec")}
}

func (_c *MockCheckWorkloadData_IkniteClusterSpec_Call) Run(run func()) *MockCheckWorkloadData_IkniteClusterSpec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCheckWorkloadData_IkniteClusterSpec_Call) Return(ikniteClusterSpec *v1alpha1.IkniteClusterSpec) *MockCheckWorkloadData_IkniteClusterSpec_Call {
	_c.Call.Return(ikniteClusterSpec)
	return _c
}

func (_c *MockCheckWorkloadData_IkniteClusterSpec_Call) RunAndReturn(run func() *v1alpha1.IkniteClusterSpec) *MockCheckWorkloadData_IkniteClusterSpec_Call {
	_c.Call.Return(run)
	return _c
}

// IsOk provides a mock function for the type MockCheckWorkloadData
func (_mock *MockCheckWorkloadData) IsOk() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsOk")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockCheckWorkloadData_IsOk_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsOk'
type MockCheckWorkloadData_IsOk_Call struct {
	*mock.Call
}

// IsOk is a helper method to define mock.On call
func (_e *MockCheckWorkloadData_Expecter) IsOk() *MockCheckWorkloadData_IsOk_Call {
	return &MockCheckWorkloadData_IsOk_Call{Call: _e.mock.On("IsOk")}
}

func (_c *MockCheckWorkloadData_IsOk_Call) Run(run func()) *MockCheckWorkloadData_IsOk_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCheckWorkloadData_IsOk_Call) Return(b bool) *MockCheckWorkloadData_IsOk_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockCheckWorkloadData_IsOk_Call) RunAndReturn(run func() bool) *MockCheckWorkloadData_IsOk_Call {
	_c.Call.Return(run)
	return _c
}

// Iteration provides a mock function for the type MockCheckWorkloadData
func (_mock *MockCheckWorkloadData) Iteration() int {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Iteration")
	}

	var r0 int
	if returnFunc, ok := ret.Get(0).(func() int); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(int)
	}
	return r0
}

// MockCheckWorkloadData_Iteration_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Iteration'
type MockCheckWorkloadData_Iteration_Call struct {
	*mock.Call
}

// Iteration is a helper method to define mock.On call
func (_e *MockCheckWorkloadData_Expecter) Iteration() *MockCheckWorkloadData_Iteration_Call {
	return &MockCheckWorkloadData_Iteration_Call{Call: _e.mock.On("Iteration")}
}

func (_c *MockCheckWorkloadData_Iteration_Call) Run(run func()) *MockCheckWorkloadData_Iteration_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCheckWorkloadData_Iteration_Call) Return(n int) *MockCheckWorkloadData_Iteration_Call {
	_c.Call.Return(n)
	return _c
}

func (_c *MockCheckWorkloadData_Iteration_Call) RunAndReturn(run func() int) *MockCheckWorkloadData_Iteration_Call {
	_c.Call.Return(run)
	return _c
}

// ManifestDir provides a mock function for the type MockCheckWorkloadData
func (_mock *MockCheckWorkloadData) ManifestDir() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ManifestDir")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockCheckWorkloadData_ManifestDir_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ManifestDir'
type MockCheckWorkloadData_ManifestDir_Call struct {
	*mock.Call
}

// ManifestDir is a helper method to define mock.On call
func (_e *MockCheckWorkloadData_Expecter) ManifestDir() *MockCheckWorkloadData_ManifestDir_Call {
	return &MockCheckWorkloadData_ManifestDir_Call{Call: _e.mock.On("ManifestDir")}
}

func (_c *MockCheckWorkloadData_ManifestDir_Call) Run(run func()) *MockCheckWorkloadData_ManifestDir_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCheckWorkloadData_ManifestDir_Call) Return(s string) *MockCheckWorkloadData_ManifestDir_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockCheckWorkloadData_ManifestDir_Call) RunAndReturn(run func() string) *MockCheckWorkloadData_ManifestDir_Call {
	_c.Call.Return(run)
	return _c
}

// NotReadyWorkloads provides a mock function for the type MockCheckWorkloadData
func (_mock *MockCheckWorkloadData) NotReadyWorkloads() []*v1alpha1.WorkloadState {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for NotReadyWorkloads")
	}

	var r0 []*v1alpha1.WorkloadState
	if returnFunc, ok := ret.Get(0).(func() []*v1alpha1.WorkloadState); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*v1alpha1.WorkloadState)
		}
	}
	return r0
}

// MockCheckWorkloadData_NotReadyWorkloads_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NotReadyWorkloads'
type MockCheckWorkloadData_NotReadyWorkloads_Call struct {
	*mock.Call
}

// NotReadyWorkloads is a helper method to define mock.On call
func (_e *MockCheckWorkloadData_Expecter) NotReadyWorkloads() *MockCheckWorkloadData_NotReadyWorkloads_Call {
	return &MockCheckWorkloadData_NotReadyWorkloads_Call{Call: _e.mock.On("NotReadyWorkloads")}
}

func (_c *MockCheckWorkloadData_NotReadyWorkloads_Call) Run(run func()) *MockCheckWorkloadData_NotReadyWorkloads_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCheckWorkloadData_NotReadyWorkloads_Call) Return(workloadStates []*v1alpha1.WorkloadState) *MockCheckWorkloadData_NotReadyWorkloads_Call {
	_c.Call.Return(workloadStates)
	return _c
}

func (_c *MockCheckWorkloadData_NotReadyWorkloads_Call) RunAndReturn(run func() []*v1alpha1.WorkloadState) *MockCheckWorkloadData_NotReadyWorkloads_Call {
	_c.Call.Return(run)
	return _c
}

// OkIterations provides a mock function for the type MockCheckWorkloadData
func (_mock *MockCheckWorkloadData) OkIterations() int {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for OkIterations")
	}

	var r0 int
	if returnFunc, ok := ret.Get(0).(func() int); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(int)
	}
	return r0
}

// MockCheckWorkloadData_OkIterations_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OkIterations'
type MockCheckWorkloadData_OkIterations_Call struct {
	*mock.Call
}

// OkIterations is a helper method to define mock.On call
func (_e *MockCheckWorkloadData_Expecter) OkIterations() *MockCheckWorkloadData_OkIterations_Call {
	return &MockCheckWorkloadData_OkIterations_Call{Call: _e.mock.On("OkIterations")}
}

func (_c *MockCheckWorkloadData_OkIterations_Call) Run(run func()) *MockCheckWorkloadData_OkIterations_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCheckWorkloadData_OkIterations_Call) Return(n int) *MockCheckWorkloadData_OkIterations_Call {
	_c.Call.Return(n)
	return _c
}

func (_c *MockCheckWorkloadData_OkIterations_Call) RunAndReturn(run func() int) *MockCheckWorkloadData_OkIterations_Call {
	_c.Call.Return(run)
	return _c
}

// ReadyWorkloads provides a mock function for the type MockCheckWorkloadData
func (_mock *MockCheckWorkloadData) ReadyWorkloads() []*v1alpha1.WorkloadState {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ReadyWorkloads")
	}

	var r0 []*v1alpha1.WorkloadState
	if returnFunc, ok := ret.Get(0).(func() []*v1alpha1.WorkloadState); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*v1alpha1.WorkloadState)
		}
	}
	return r0
}

// MockCheckWorkloadData_ReadyWorkloads_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadyWorkloads'
type MockCheckWorkloadData_ReadyWorkloads_Call struct {
	*mock.Call
}

// ReadyWorkloads is a helper method to define mock.On call
func (_e *MockCheckWorkloadData_Expecter) ReadyWorkloads() *MockCheckWorkloadData_ReadyWorkloads_Call {
	return &MockCheckWorkloadData_ReadyWorkloads_Call{Call: _e.mock.On("ReadyWorkloads")}
}

func (_c *MockCheckWorkloadData_ReadyWorkloads_Call) Run(run func()) *MockCheckWorkloadData_ReadyWorkloads_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCheckWorkloadData_ReadyWorkloads_Call) Return(workloadStates []*v1alpha1.WorkloadState) *MockCheckWorkloadData_ReadyWorkloads_Call {
	_c.Call.Return(workloadStates)
	return _c
}

func (_c *MockCheckWorkloadData_ReadyWorkloads_Call) RunAndReturn(run func() []*v1alpha1.WorkloadState) *MockCheckWorkloadData_ReadyWorkloads_Call {
	_c.Call.Return(run)
	return _c
}

// SetIteration provides a mock function for the type MockCheckWorkloadData
func (_mock *MockCheckWorkloadData) SetIteration(n int) {
	_mock.Called(n)
	return
}

// MockCheckWorkloadData_SetIteration_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetIteration'
type MockCheckWorkloadData_SetIteration_Call struct {
	*mock.Call
}

// SetIteration is a helper method to define mock.On call
//   - n int
func (_e *MockCheckWorkloadData_Expecter) SetIteration(n interface{}) *MockCheckWorkloadData_SetIteration_Call {
	return &MockCheckWorkloadData_SetIteration_Call{Call: _e.mock.On("SetIteration", n)}
}

func (_c *MockCheckWorkloadData_SetIteration_Call) Run(run func(n int)) *MockCheckWorkloadData_SetIteration_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCheckWorkloadData_SetIteration_Call) Return() *MockCheckWorkloadData_SetIteration_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockCheckWorkloadData_SetIteration_Call) RunAndReturn(run func(n int)) *MockCheckWorkloadData_SetIteration_Call {
	_c.Run(run)
	return _c
}

// SetNotReadyWorkloads provides a mock function for the type MockCheckWorkloadData
func (_mock *MockCheckWorkloadData) SetNotReadyWorkloads(workloadStates []*v1alpha1.WorkloadState) {
	_mock.Called(workloadStates)
	return
}

// MockCheckWorkloadData_SetNotReadyWorkloads_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetNotReadyWorkloads'
type MockCheckWorkloadData_SetNotReadyWorkloads_Call struct {
	*mock.Call
}

// SetNotReadyWorkloads is a helper method to define mock.On call
//   - workloadStates []*v1alpha1.WorkloadState
func (_e *MockCheckWorkloadData_Expecter) SetNotReadyWorkloads(workloadStates interface{}) *MockCheckWorkloadData_SetNotReadyWorkloads_Call {
	return &MockCheckWorkloadData_SetNotReadyWorkloads_Call{Call: _e.mock.On("SetNotReadyWorkloads", workloadStates)}
}

func (_c *MockCheckWorkloadData_SetNotReadyWorkloads_Call) Run(run func(workloadStates []*v1alpha1.WorkloadState)) *MockCheckWorkloadData_SetNotReadyWorkloads_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []*v1alpha1.WorkloadState
		if args[0] != nil {
			arg0 = args[0].([]*v1alpha1.WorkloadState)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCheckWorkloadData_SetNotReadyWorkloads_Call) Return() *MockCheckWorkloadData_SetNotReadyWorkloads_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockCheckWorkloadData_SetNotReadyWorkloads_Call) RunAndReturn(run func(workloadStates []*v1alpha1.WorkloadState)) *MockCheckWorkloadData_SetNotReadyWorkloads_Call {
	_c.Run(run)
	return _c
}

// SetOk provides a mock function for the type MockCheckWorkloadData
func (_mock *MockCheckWorkloadData) SetOk(b bool) {
	_mock.Called(b)
	return
}

// MockCheckWorkloadData_SetOk_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetOk'
type MockCheckWorkloadData_SetOk_Call struct {
	*mock.Call
}

// SetOk is a helper method to define mock.On call
//   - b bool
func (_e *MockCheckWorkloadData_Expecter) SetOk(b interface{}) *MockCheckWorkloadData_SetOk_Call {
	return &MockCheckWorkloadData_SetOk_Call{Call: _e.mock.On("SetOk", b)}
}

func (_c *MockCheckWorkloadData_SetOk_Call) Run(run func(b bool)) *MockCheckWorkloadData_SetOk_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 bool
		if args[0] != nil {
			arg0 = args[0].(bool)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCheckWorkloadData_SetOk_Call) Return() *MockCheckWorkloadData_SetOk_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockCheckWorkloadData_SetOk_Call) RunAndReturn(run func(b bool)) *MockCheckWorkloadData_SetOk_Call {
	_c.Run(run)
	return _c
}

// SetOkIterations provides a mock function for the type MockCheckWorkloadData
func (_mock *MockCheckWorkloadData) SetOkIterations(n int) {
	_mock.Called(n)
	return
}

// MockCheckWorkloadData_SetOkIterations_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetOkIterations'
type MockCheckWorkloadData_SetOkIterations_Call struct {
	*mock.Call
}

// SetOkIterations is a helper method to define mock.On call
//   - n int
func (_e *MockCheckWorkloadData_Expecter) SetOkIterations(n interface{}) *MockCheckWorkloadData_SetOkIterations_Call {
	return &MockCheckWorkloadData_SetOkIterations_Call{Call: _e.mock.On("SetOkIterations", n)}
}

func (_c *MockCheckWorkloadData_SetOkIterations_Call) Run(run func(n int)) *MockCheckWorkloadData_SetOkIterations_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCheckWorkloadData_SetOkIterations_Call) Return() *MockCheckWorkloadData_SetOkIterations_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockCheckWorkloadData_SetOkIterations_Call) RunAndReturn(run func(n int)) *MockCheckWorkloadData_SetOkIterations_Call {
	_c.Run(run)
	return _c
}

// SetReadyWorkloads provides a mock function for the type MockCheckWorkloadData
func (_mock *MockCheckWorkloadData) SetReadyWorkloads(workloadStates []*v1alpha1.WorkloadState) {
	_mock.Called(workloadStates)
	return
}

// MockCheckWorkloadData_SetReadyWorkloads_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetReadyWorkloads'
type MockCheckWorkloadData_SetReadyWorkloads_Call struct {
	*mock.Call
}

// SetReadyWorkloads is a helper method to define mock.On call
//   - workloadStates []*v1alpha1.WorkloadState
func (_e *MockCheckWorkloadData_Expecter) SetReadyWorkloads(workloadStates interface{}) *MockCheckWorkloadData_SetReadyWorkloads_Call {
	return &MockCheckWorkloadData_SetReadyWorkloads_Call{Call: _e.mock.On("SetReadyWorkloads", workloadStates)}
}

func (_c *MockCheckWorkloadData_SetReadyWorkloads_Call) Run(run func(workloadStates []*v1alpha1.WorkloadState)) *MockCheckWorkloadData_SetReadyWorkloads_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []*v1alpha1.WorkloadState
		if args[0] != nil {
			arg0 = args[0].([]*v1alpha1.WorkloadState)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCheckWorkloadData_SetReadyWorkloads_Call) Return() *MockCheckWorkloadData_SetReadyWorkloads_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockCheckWorkloadData_SetReadyWorkloads_Call) RunAndReturn(run func(workloadStates []*v1alpha1.WorkloadState)) *MockCheckWorkloadData_SetReadyWorkloads_Call {
	_c.Run(run)
	return _c
}

// SetWorkloadCount provides a mock function for the type MockCheckWorkloadData
func (_mock *MockCheckWorkloadData) SetWorkloadCount(n int) {
	_mock.Called(n)
	return
}

// MockCheckWorkloadData_SetWorkloadCount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetWorkloadCount'
type MockCheckWorkloadData_SetWorkloadCount_Call struct {
	*mock.Call
}

// SetWorkloadCount is a helper method to define mock.On call
//   - n int
func (_e *MockCheckWorkloadData_Expecter) SetWorkloadCount(n interface{}) *MockCheckWorkloadData_SetWorkloadCount_Call {
	return &MockCheckWorkloadData_SetWorkloadCount_Call{Call: _e.mock.On("SetWorkloadCount", n)}
}

func (_c *MockCheckWorkloadData_SetWorkloadCount_Call) Run(run func(n int)) *MockCheckWorkloadData_SetWorkloadCount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCheckWorkloadData_SetWorkloadCount_Call) Return() *MockCheckWorkloadData_SetWorkloadCount_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockCheckWorkloadData_SetWorkloadCount_Call) RunAndReturn(run func(n int)) *MockCheckWorkloadData_SetWorkloadCount_Call {
	_c.Run(run)
	return _c
}

// Start provides a mock function for the type MockCheckWorkloadData
func (_mock *MockCheckWorkloadData) Start() {
	_mock.Called()
	return
}

// MockCheckWorkloadData_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type MockCheckWorkloadData_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
func (_e *MockCheckWorkloadData_Expecter) Start() *MockCheckWorkloadData_Start_Call {
	return &MockCheckWorkloadData_Start_Call{Call: _e.mock.On("Start")}
}

func (_c *MockCheckWorkloadData_Start_Call) Run(run func()) *MockCheckWorkloadData_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCheckWorkloadData_Start_Call) Return() *MockCheckWorkloadData_Start_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockCheckWorkloadData_Start_Call) RunAndReturn(run func()) *MockCheckWorkloadData_Start_Call {
	_c.Run(run)
	return _c
}

// WaitOptions provides a mock function for the type MockCheckWorkloadData
func (_mock *MockCheckWorkloadData) WaitOptions() *utils.WaitOptions {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for WaitOptions")
	}

	var r0 *utils.WaitOptions
	if returnFunc, ok := ret.Get(0).(func() *utils.WaitOptions); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*utils.WaitOptions)
		}
	}
	return r0
}

// MockCheckWorkloadData_WaitOptions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WaitOptions'
type MockCheckWorkloadData_WaitOptions_Call struct {
	*mock.Call
}

// WaitOptions is a helper method to define mock.On call
func (_e *MockCheckWorkloadData_Expecter) WaitOptions() *MockCheckWorkloadData_WaitOptions_Call {
	return &MockCheckWorkloadData_WaitOptions_Call{Call: _e.mock.On("WaitOptions")}
}

func (_c *MockCheckWorkloadData_WaitOptions_Call) Run(run func()) *MockCheckWorkloadData_WaitOptions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCheckWorkloadData_WaitOptions_Call) Return(waitOptions *utils.WaitOptions) *MockCheckWorkloadData_WaitOptions_Call {
	_c.Call.Return(waitOptions)
	return _c
}

func (_c *MockCheckWorkloadData_WaitOptions_Call) RunAndReturn(run func() *utils.WaitOptions) *MockCheckWorkloadData_WaitOptions_Call {
	_c.Call.Return(run)
	return _c
}

// WorkloadCount provides a mock function for the type MockCheckWorkloadData
func (_mock *MockCheckWorkloadData) WorkloadCount() int {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for WorkloadCount")
	}

	var r0 int
	if returnFunc, ok := ret.Get(0).(func() int); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(int)
	}
	return r0
}

// MockCheckWorkloadData_WorkloadCount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WorkloadCount'
type MockCheckWorkloadData_WorkloadCount_Call struct {
	*mock.Call
}

// WorkloadCount is a helper method to define mock.On call
func (_e *MockCheckWorkloadData_Expecter) WorkloadCount() *MockCheckWorkloadData_WorkloadCount_Call {
	return &MockCheckWorkloadData_WorkloadCount_Call{Call: _e.mock.On("WorkloadCount")}
}

func (_c *MockCheckWorkloadData_WorkloadCount_Call) Run(run func()) *MockCheckWorkloadData_WorkloadCount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCheckWorkloadData_WorkloadCount_Call) Return(n int) *MockCheckWorkloadData_WorkloadCount_Call {
	_c.Call.Return(n)
	return _c
}

func (_c *MockCheckWorkloadData_WorkloadCount_Call) RunAndReturn(run func() int) *MockCheckWorkloadData_WorkloadCount_Call {
	_c.Call.Return(run)
	return _c
}
