// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package checkers

import (
	"log/slog"

	"github.com/kaweezle/iknite/pkg/host"
	mock "github.com/stretchr/testify/mock"
)

// NewMockServiceCheckData creates a new instance of MockServiceCheckData. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockServiceCheckData(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockServiceCheckData {
	mock := &MockServiceCheckData{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockServiceCheckData is an autogenerated mock type for the serviceCheckData type
type MockServiceCheckData struct {
	mock.Mock
}

type MockServiceCheckData_Expecter struct {
	mock *mock.Mock
}

func (_m *MockServiceCheckData) EXPECT() *MockServiceCheckData_Expecter {
	return &MockServiceCheckData_Expecter{mock: &_m.Mock}
}

// Host provides a mock function for the type MockServiceCheckData
func (_mock *MockServiceCheckData) Host() host.Host {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Host")
	}

	var r0 host.Host
	if returnFunc, ok := ret.Get(0).(func() host.Host); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(host.Host)
		}
	}
	return r0
}

// MockServiceCheckData_Host_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Host'
type MockServiceCheckData_Host_Call struct {
	*mock.Call
}

// Host is a helper method to define mock.On call
func (_e *MockServiceCheckData_Expecter) Host() *MockServiceCheckData_Host_Call {
	return &MockServiceCheckData_Host_Call{Call: _e.mock.On("Host")}
}

func (_c *MockServiceCheckData_Host_Call) Run(run func()) *MockServiceCheckData_Host_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockServiceCheckData_Host_Call) Return(host1 host.Host) *MockServiceCheckData_Host_Call {
	_c.Call.Return(host1)
	return _c
}

func (_c *MockServiceCheckData_Host_Call) RunAndReturn(run func() host.Host) *MockServiceCheckData_Host_Call {
	_c.Call.Return(run)
	return _c
}

// Logger provides a mock function for the type MockServiceCheckData
func (_mock *MockServiceCheckData) Logger() *slog.Logger {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Logger")
	}

	var r0 *slog.Logger
	if returnFunc, ok := ret.Get(0).(func() *slog.Logger); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*slog.Logger)
		}
	}
	return r0
}

// MockServiceCheckData_Logger_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Logger'
type MockServiceCheckData_Logger_Call struct {
	*mock.Call
}

// Logger is a helper method to define mock.On call
func (_e *MockServiceCheckData_Expecter) Logger() *MockServiceCheckData_Logger_Call {
	return &MockServiceCheckData_Logger_Call{Call: _e.mock.On("Logger")}
}

func (_c *MockServiceCheckData_Logger_Call) Run(run func()) *MockServiceCheckData_Logger_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockServiceCheckData_Logger_Call) Return(logger *slog.Logger) *MockServiceCheckData_Logger_Call {
	_c.Call.Return(logger)
	return _c
}

func (_c *MockServiceCheckData_Logger_Call) RunAndReturn(run func() *slog.Logger) *MockServiceCheckData_Logger_Call {
	_c.Call.Return(run)
	return _c
}
