// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package reset

import (
	"log/slog"

	"github.com/kaweezle/iknite/pkg/host"
	mock "github.com/stretchr/testify/mock"
)

// NewMockCleanupServiceData creates a new instance of MockCleanupServiceData. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCleanupServiceData(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCleanupServiceData {
	mock := &MockCleanupServiceData{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCleanupServiceData is an autogenerated mock type for the cleanupServiceData type
type MockCleanupServiceData struct {
	mock.Mock
}

type MockCleanupServiceData_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCleanupServiceData) EXPECT() *MockCleanupServiceData_Expecter {
	return &MockCleanupServiceData_Expecter{mock: &_m.Mock}
}

// DryRun provides a mock function for the type MockCleanupServiceData
func (_mock *MockCleanupServiceData) DryRun() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for DryRun")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockCleanupServiceData_DryRun_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DryRun'
type MockCleanupServiceData_DryRun_Call struct {
	*mock.Call
}

// DryRun is a helper method to define mock.On call
func (_e *MockCleanupServiceData_Expecter) DryRun() *MockCleanupServiceData_DryRun_Call {
	return &MockCleanupServiceData_DryRun_Call{Call: _e.mock.On("DryRun")}
}

func (_c *MockCleanupServiceData_DryRun_Call) Run(run func()) *MockCleanupServiceData_DryRun_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCleanupServiceData_DryRun_Call) Return(b bool) *MockCleanupServiceData_DryRun_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockCleanupServiceData_DryRun_Call) RunAndReturn(run func() bool) *MockCleanupServiceData_DryRun_Call {
	_c.Call.Return(run)
	return _c
}

// Host provides a mock function for the type MockCleanupServiceData
func (_mock *MockCleanupServiceData) Host() host.Host {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Host")
	}

	var r0 host.Host
	if returnFunc, ok := ret.Get(0).(func() host.Host); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(host.Host)
		}
	}
	return r0
}

// MockCleanupServiceData_Host_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Host'
type MockCleanupServiceData_Host_Call struct {
	*mock.Call
}

// Host is a helper method to define mock.On call
func (_e *MockCleanupServiceData_Expecter) Host() *MockCleanupServiceData_Host_Call {
	return &MockCleanupServiceData_Host_Call{Call: _e.mock.On("Host")}
}

func (_c *MockCleanupServiceData_Host_Call) Run(run func()) *MockCleanupServiceData_Host_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCleanupServiceData_Host_Call) Return(host1 host.Host) *MockCleanupServiceData_Host_Call {
	_c.Call.Return(host1)
	return _c
}

func (_c *MockCleanupServiceData_Host_Call) RunAndReturn(run func() host.Host) *MockCleanupServiceData_Host_Call {
	_c.Call.Return(run)
	return _c
}

// Logger provides a mock function for the type MockCleanupServiceData
func (_mock *MockCleanupServiceData) Logger() *slog.Logger {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Logger")
	}

	var r0 *slog.Logger
	if returnFunc, ok := ret.Get(0).(func() *slog.Logger); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*slog.Logger)
		}
	}
	return r0
}

// MockCleanupServiceData_Logger_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Logger'
type MockCleanupServiceData_Logger_Call struct {
	*mock.Call
}

// Logger is a helper method to define mock.On call
func (_e *MockCleanupServiceData_Expecter) Logger() *MockCleanupServiceData_Logger_Call {
	return &MockCleanupServiceData_Logger_Call{Call: _e.mock.On("Logger")}
}

func (_c *MockCleanupServiceData_Logger_Call) Run(run func()) *MockCleanupServiceData_Logger_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCleanupServiceData_Logger_Call) Return(logger *slog.Logger) *MockCleanupServiceData_Logger_Call {
	_c.Call.Return(logger)
	return _c
}

func (_c *MockCleanupServiceData_Logger_Call) RunAndReturn(run func() *slog.Logger) *MockCleanupServiceData_Logger_Call {
	_c.Call.Return(run)
	return _c
}
