apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd

resources:
  - namespace.yaml
  - https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml

patches:
  - patch: |-
      - op: add
        path: /spec/template/spec/containers/0/command/-
        value: --insecure
    target:
      kind: Deployment
      name: argocd-server
  - patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: "chatwork/argocd-helmfile:latest"
      - op: add
        path: /spec/template/spec/containers/0/securityContext/runAsUser
        value: 999
    target:
      kind: Deployment
      name: argocd-repo-server
  - path: configuration.yaml
