// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package init

import (
	"context"

	"github.com/kaweezle/iknite/pkg/apis/iknite/v1alpha1"
	"github.com/kaweezle/iknite/pkg/host"
	"github.com/kaweezle/iknite/pkg/utils"
	mock "github.com/stretchr/testify/mock"
)

// newMockkustomizeData creates a new instance of mockkustomizeData. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockkustomizeData(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockkustomizeData {
	mock := &mockkustomizeData{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockkustomizeData is an autogenerated mock type for the kustomizeData type
type mockkustomizeData struct {
	mock.Mock
}

type mockkustomizeData_Expecter struct {
	mock *mock.Mock
}

func (_m *mockkustomizeData) EXPECT() *mockkustomizeData_Expecter {
	return &mockkustomizeData_Expecter{mock: &_m.Mock}
}

// Context provides a mock function for the type mockkustomizeData
func (_mock *mockkustomizeData) Context() context.Context {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Context")
	}

	var r0 context.Context
	if returnFunc, ok := ret.Get(0).(func() context.Context); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(context.Context)
		}
	}
	return r0
}

// mockkustomizeData_Context_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Context'
type mockkustomizeData_Context_Call struct {
	*mock.Call
}

// Context is a helper method to define mock.On call
func (_e *mockkustomizeData_Expecter) Context() *mockkustomizeData_Context_Call {
	return &mockkustomizeData_Context_Call{Call: _e.mock.On("Context")}
}

func (_c *mockkustomizeData_Context_Call) Run(run func()) *mockkustomizeData_Context_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockkustomizeData_Context_Call) Return(context1 context.Context) *mockkustomizeData_Context_Call {
	_c.Call.Return(context1)
	return _c
}

func (_c *mockkustomizeData_Context_Call) RunAndReturn(run func() context.Context) *mockkustomizeData_Context_Call {
	_c.Call.Return(run)
	return _c
}

// Host provides a mock function for the type mockkustomizeData
func (_mock *mockkustomizeData) Host() host.Host {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Host")
	}

	var r0 host.Host
	if returnFunc, ok := ret.Get(0).(func() host.Host); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(host.Host)
		}
	}
	return r0
}

// mockkustomizeData_Host_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Host'
type mockkustomizeData_Host_Call struct {
	*mock.Call
}

// Host is a helper method to define mock.On call
func (_e *mockkustomizeData_Expecter) Host() *mockkustomizeData_Host_Call {
	return &mockkustomizeData_Host_Call{Call: _e.mock.On("Host")}
}

func (_c *mockkustomizeData_Host_Call) Run(run func()) *mockkustomizeData_Host_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockkustomizeData_Host_Call) Return(host1 host.Host) *mockkustomizeData_Host_Call {
	_c.Call.Return(host1)
	return _c
}

func (_c *mockkustomizeData_Host_Call) RunAndReturn(run func() host.Host) *mockkustomizeData_Host_Call {
	_c.Call.Return(run)
	return _c
}

// IkniteCluster provides a mock function for the type mockkustomizeData
func (_mock *mockkustomizeData) IkniteCluster() *v1alpha1.IkniteCluster {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for IkniteCluster")
	}

	var r0 *v1alpha1.IkniteCluster
	if returnFunc, ok := ret.Get(0).(func() *v1alpha1.IkniteCluster); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1alpha1.IkniteCluster)
		}
	}
	return r0
}

// mockkustomizeData_IkniteCluster_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IkniteCluster'
type mockkustomizeData_IkniteCluster_Call struct {
	*mock.Call
}

// IkniteCluster is a helper method to define mock.On call
func (_e *mockkustomizeData_Expecter) IkniteCluster() *mockkustomizeData_IkniteCluster_Call {
	return &mockkustomizeData_IkniteCluster_Call{Call: _e.mock.On("IkniteCluster")}
}

func (_c *mockkustomizeData_IkniteCluster_Call) Run(run func()) *mockkustomizeData_IkniteCluster_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockkustomizeData_IkniteCluster_Call) Return(ikniteCluster *v1alpha1.IkniteCluster) *mockkustomizeData_IkniteCluster_Call {
	_c.Call.Return(ikniteCluster)
	return _c
}

func (_c *mockkustomizeData_IkniteCluster_Call) RunAndReturn(run func() *v1alpha1.IkniteCluster) *mockkustomizeData_IkniteCluster_Call {
	_c.Call.Return(run)
	return _c
}

// KustomizeOptions provides a mock function for the type mockkustomizeData
func (_mock *mockkustomizeData) KustomizeOptions() *utils.KustomizeOptions {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for KustomizeOptions")
	}

	var r0 *utils.KustomizeOptions
	if returnFunc, ok := ret.Get(0).(func() *utils.KustomizeOptions); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*utils.KustomizeOptions)
		}
	}
	return r0
}

// mockkustomizeData_KustomizeOptions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'KustomizeOptions'
type mockkustomizeData_KustomizeOptions_Call struct {
	*mock.Call
}

// KustomizeOptions is a helper method to define mock.On call
func (_e *mockkustomizeData_Expecter) KustomizeOptions() *mockkustomizeData_KustomizeOptions_Call {
	return &mockkustomizeData_KustomizeOptions_Call{Call: _e.mock.On("KustomizeOptions")}
}

func (_c *mockkustomizeData_KustomizeOptions_Call) Run(run func()) *mockkustomizeData_KustomizeOptions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockkustomizeData_KustomizeOptions_Call) Return(kustomizeOptions *utils.KustomizeOptions) *mockkustomizeData_KustomizeOptions_Call {
	_c.Call.Return(kustomizeOptions)
	return _c
}

func (_c *mockkustomizeData_KustomizeOptions_Call) RunAndReturn(run func() *utils.KustomizeOptions) *mockkustomizeData_KustomizeOptions_Call {
	_c.Call.Return(run)
	return _c
}
