// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package init

import (
	"github.com/kaweezle/iknite/pkg/apis/iknite/v1alpha1"
	"github.com/pion/mdns"
	mock "github.com/stretchr/testify/mock"
)

// newMockmdnsData creates a new instance of mockmdnsData. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockmdnsData(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockmdnsData {
	mock := &mockmdnsData{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockmdnsData is an autogenerated mock type for the mdnsData type
type mockmdnsData struct {
	mock.Mock
}

type mockmdnsData_Expecter struct {
	mock *mock.Mock
}

func (_m *mockmdnsData) EXPECT() *mockmdnsData_Expecter {
	return &mockmdnsData_Expecter{mock: &_m.Mock}
}

// IkniteCluster provides a mock function for the type mockmdnsData
func (_mock *mockmdnsData) IkniteCluster() *v1alpha1.IkniteCluster {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for IkniteCluster")
	}

	var r0 *v1alpha1.IkniteCluster
	if returnFunc, ok := ret.Get(0).(func() *v1alpha1.IkniteCluster); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1alpha1.IkniteCluster)
		}
	}
	return r0
}

// mockmdnsData_IkniteCluster_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IkniteCluster'
type mockmdnsData_IkniteCluster_Call struct {
	*mock.Call
}

// IkniteCluster is a helper method to define mock.On call
func (_e *mockmdnsData_Expecter) IkniteCluster() *mockmdnsData_IkniteCluster_Call {
	return &mockmdnsData_IkniteCluster_Call{Call: _e.mock.On("IkniteCluster")}
}

func (_c *mockmdnsData_IkniteCluster_Call) Run(run func()) *mockmdnsData_IkniteCluster_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockmdnsData_IkniteCluster_Call) Return(ikniteCluster *v1alpha1.IkniteCluster) *mockmdnsData_IkniteCluster_Call {
	_c.Call.Return(ikniteCluster)
	return _c
}

func (_c *mockmdnsData_IkniteCluster_Call) RunAndReturn(run func() *v1alpha1.IkniteCluster) *mockmdnsData_IkniteCluster_Call {
	_c.Call.Return(run)
	return _c
}

// MDnsConn provides a mock function for the type mockmdnsData
func (_mock *mockmdnsData) MDnsConn() *mdns.Conn {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for MDnsConn")
	}

	var r0 *mdns.Conn
	if returnFunc, ok := ret.Get(0).(func() *mdns.Conn); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*mdns.Conn)
		}
	}
	return r0
}

// mockmdnsData_MDnsConn_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MDnsConn'
type mockmdnsData_MDnsConn_Call struct {
	*mock.Call
}

// MDnsConn is a helper method to define mock.On call
func (_e *mockmdnsData_Expecter) MDnsConn() *mockmdnsData_MDnsConn_Call {
	return &mockmdnsData_MDnsConn_Call{Call: _e.mock.On("MDnsConn")}
}

func (_c *mockmdnsData_MDnsConn_Call) Run(run func()) *mockmdnsData_MDnsConn_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockmdnsData_MDnsConn_Call) Return(conn *mdns.Conn) *mockmdnsData_MDnsConn_Call {
	_c.Call.Return(conn)
	return _c
}

func (_c *mockmdnsData_MDnsConn_Call) RunAndReturn(run func() *mdns.Conn) *mockmdnsData_MDnsConn_Call {
	_c.Call.Return(run)
	return _c
}

// SetMDnsConn provides a mock function for the type mockmdnsData
func (_mock *mockmdnsData) SetMDnsConn(conn *mdns.Conn) {
	_mock.Called(conn)
	return
}

// mockmdnsData_SetMDnsConn_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetMDnsConn'
type mockmdnsData_SetMDnsConn_Call struct {
	*mock.Call
}

// SetMDnsConn is a helper method to define mock.On call
//   - conn *mdns.Conn
func (_e *mockmdnsData_Expecter) SetMDnsConn(conn interface{}) *mockmdnsData_SetMDnsConn_Call {
	return &mockmdnsData_SetMDnsConn_Call{Call: _e.mock.On("SetMDnsConn", conn)}
}

func (_c *mockmdnsData_SetMDnsConn_Call) Run(run func(conn *mdns.Conn)) *mockmdnsData_SetMDnsConn_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *mdns.Conn
		if args[0] != nil {
			arg0 = args[0].(*mdns.Conn)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mockmdnsData_SetMDnsConn_Call) Return() *mockmdnsData_SetMDnsConn_Call {
	_c.Call.Return()
	return _c
}

func (_c *mockmdnsData_SetMDnsConn_Call) RunAndReturn(run func(conn *mdns.Conn)) *mockmdnsData_SetMDnsConn_Call {
	_c.Run(run)
	return _c
}
