// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

type BackendImage struct {
	ID          string
	CreatedAt   string
	UpdatedAt   string
	Backend     string
	ImageID     string
	ExternalID  string
	Placeholder int64
}

type Cluster struct {
	ID             string
	CreatedAt      string
	UpdatedAt      string
	Name           string
	Backend        string
	ImageID        string
	BackendImageID string
	Workspace      string
	Ref            string
}

type Image struct {
	ID        string
	CreatedAt string
	UpdatedAt string
	VersionID string
	Name      string
}

type ImageArtifact struct {
	ID        string
	CreatedAt string
	UpdatedAt string
	ImageID   string
	Path      string
	Digest    string
	Type      string
	Size      int64
}

type ImageSource struct {
	ID        string
	CreatedAt string
	UpdatedAt string
	Kind      string
	Location  string
}

type ImageVersion struct {
	ID                string
	CreatedAt         string
	UpdatedAt         string
	SourceID          string
	Tag               string
	ManifestDigest    string
	ManifestMediaType string
	Manifest          []byte
}
