---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app: kube-vip
  name: kube-vip:node-lister
rules:
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - get
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app: kube-vip
  name: kube-vip-address-pool-admin
  namespace: kube-system
rules:
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: kube-vip
  name: kube-vip-address-pool-admin
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app: kube-vip
  name: kube-vip-address-pool-admin
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kube-vip-address-pool-admin
subjects:
  - kind: ServiceAccount
    name: kube-vip-address-pool-admin
    namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app: kube-vip
  name: kube-vip-address-pool-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kube-vip:node-lister
subjects:
  - kind: ServiceAccount
    name: kube-vip-address-pool-admin
    namespace: kube-system
---
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app: kube-vip
  name: create-address-pools
  namespace: kube-system
spec:
  ttlSecondsAfterFinished: 100
  backoffLimit: 3
  template:
    spec:
      serviceAccountName: kube-vip-address-pool-admin
      automountServiceAccountToken: true
      restartPolicy: OnFailure
      containers:
        - name: create-address-pools
          image: docker.io/alpine/kubectl:1.34.2
          imagePullPolicy: IfNotPresent
          command:
            - /bin/sh
            - -c
            - |
              set -xe
              kubectl rollout status deployment/kube-vip-cloud-provider -n kube-system
              ip=$(kubectl get nodes -o jsonpath='{range .items[*]}{range .status.addresses[*]}{.address}{"\n"}{end}{end}' | head -1)
              sleep 3
              kubectl create configmap -n kube-system kubevip --from-literal cidr-global=$ip/32 -o yaml --dry-run=client | kubectl apply -f -
