// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package genericclioptions

import (
	mock "github.com/stretchr/testify/mock"
	"k8s.io/apimachinery/pkg/api/meta"
	"k8s.io/client-go/discovery"
	"k8s.io/client-go/rest"
	"k8s.io/client-go/tools/clientcmd"
)

// NewMockRESTClientGetter creates a new instance of MockRESTClientGetter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRESTClientGetter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRESTClientGetter {
	mock := &MockRESTClientGetter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRESTClientGetter is an autogenerated mock type for the RESTClientGetter type
type MockRESTClientGetter struct {
	mock.Mock
}

type MockRESTClientGetter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRESTClientGetter) EXPECT() *MockRESTClientGetter_Expecter {
	return &MockRESTClientGetter_Expecter{mock: &_m.Mock}
}

// ToDiscoveryClient provides a mock function for the type MockRESTClientGetter
func (_mock *MockRESTClientGetter) ToDiscoveryClient() (discovery.CachedDiscoveryInterface, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ToDiscoveryClient")
	}

	var r0 discovery.CachedDiscoveryInterface
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (discovery.CachedDiscoveryInterface, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() discovery.CachedDiscoveryInterface); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(discovery.CachedDiscoveryInterface)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRESTClientGetter_ToDiscoveryClient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ToDiscoveryClient'
type MockRESTClientGetter_ToDiscoveryClient_Call struct {
	*mock.Call
}

// ToDiscoveryClient is a helper method to define mock.On call
func (_e *MockRESTClientGetter_Expecter) ToDiscoveryClient() *MockRESTClientGetter_ToDiscoveryClient_Call {
	return &MockRESTClientGetter_ToDiscoveryClient_Call{Call: _e.mock.On("ToDiscoveryClient")}
}

func (_c *MockRESTClientGetter_ToDiscoveryClient_Call) Run(run func()) *MockRESTClientGetter_ToDiscoveryClient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRESTClientGetter_ToDiscoveryClient_Call) Return(cachedDiscoveryInterface discovery.CachedDiscoveryInterface, err error) *MockRESTClientGetter_ToDiscoveryClient_Call {
	_c.Call.Return(cachedDiscoveryInterface, err)
	return _c
}

func (_c *MockRESTClientGetter_ToDiscoveryClient_Call) RunAndReturn(run func() (discovery.CachedDiscoveryInterface, error)) *MockRESTClientGetter_ToDiscoveryClient_Call {
	_c.Call.Return(run)
	return _c
}

// ToRESTConfig provides a mock function for the type MockRESTClientGetter
func (_mock *MockRESTClientGetter) ToRESTConfig() (*rest.Config, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ToRESTConfig")
	}

	var r0 *rest.Config
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (*rest.Config, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() *rest.Config); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*rest.Config)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRESTClientGetter_ToRESTConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ToRESTConfig'
type MockRESTClientGetter_ToRESTConfig_Call struct {
	*mock.Call
}

// ToRESTConfig is a helper method to define mock.On call
func (_e *MockRESTClientGetter_Expecter) ToRESTConfig() *MockRESTClientGetter_ToRESTConfig_Call {
	return &MockRESTClientGetter_ToRESTConfig_Call{Call: _e.mock.On("ToRESTConfig")}
}

func (_c *MockRESTClientGetter_ToRESTConfig_Call) Run(run func()) *MockRESTClientGetter_ToRESTConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRESTClientGetter_ToRESTConfig_Call) Return(config *rest.Config, err error) *MockRESTClientGetter_ToRESTConfig_Call {
	_c.Call.Return(config, err)
	return _c
}

func (_c *MockRESTClientGetter_ToRESTConfig_Call) RunAndReturn(run func() (*rest.Config, error)) *MockRESTClientGetter_ToRESTConfig_Call {
	_c.Call.Return(run)
	return _c
}

// ToRESTMapper provides a mock function for the type MockRESTClientGetter
func (_mock *MockRESTClientGetter) ToRESTMapper() (meta.RESTMapper, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ToRESTMapper")
	}

	var r0 meta.RESTMapper
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (meta.RESTMapper, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() meta.RESTMapper); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(meta.RESTMapper)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRESTClientGetter_ToRESTMapper_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ToRESTMapper'
type MockRESTClientGetter_ToRESTMapper_Call struct {
	*mock.Call
}

// ToRESTMapper is a helper method to define mock.On call
func (_e *MockRESTClientGetter_Expecter) ToRESTMapper() *MockRESTClientGetter_ToRESTMapper_Call {
	return &MockRESTClientGetter_ToRESTMapper_Call{Call: _e.mock.On("ToRESTMapper")}
}

func (_c *MockRESTClientGetter_ToRESTMapper_Call) Run(run func()) *MockRESTClientGetter_ToRESTMapper_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRESTClientGetter_ToRESTMapper_Call) Return(rESTMapper meta.RESTMapper, err error) *MockRESTClientGetter_ToRESTMapper_Call {
	_c.Call.Return(rESTMapper, err)
	return _c
}

func (_c *MockRESTClientGetter_ToRESTMapper_Call) RunAndReturn(run func() (meta.RESTMapper, error)) *MockRESTClientGetter_ToRESTMapper_Call {
	_c.Call.Return(run)
	return _c
}

// ToRawKubeConfigLoader provides a mock function for the type MockRESTClientGetter
func (_mock *MockRESTClientGetter) ToRawKubeConfigLoader() clientcmd.ClientConfig {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ToRawKubeConfigLoader")
	}

	var r0 clientcmd.ClientConfig
	if returnFunc, ok := ret.Get(0).(func() clientcmd.ClientConfig); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(clientcmd.ClientConfig)
		}
	}
	return r0
}

// MockRESTClientGetter_ToRawKubeConfigLoader_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ToRawKubeConfigLoader'
type MockRESTClientGetter_ToRawKubeConfigLoader_Call struct {
	*mock.Call
}

// ToRawKubeConfigLoader is a helper method to define mock.On call
func (_e *MockRESTClientGetter_Expecter) ToRawKubeConfigLoader() *MockRESTClientGetter_ToRawKubeConfigLoader_Call {
	return &MockRESTClientGetter_ToRawKubeConfigLoader_Call{Call: _e.mock.On("ToRawKubeConfigLoader")}
}

func (_c *MockRESTClientGetter_ToRawKubeConfigLoader_Call) Run(run func()) *MockRESTClientGetter_ToRawKubeConfigLoader_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRESTClientGetter_ToRawKubeConfigLoader_Call) Return(clientConfig clientcmd.ClientConfig) *MockRESTClientGetter_ToRawKubeConfigLoader_Call {
	_c.Call.Return(clientConfig)
	return _c
}

func (_c *MockRESTClientGetter_ToRawKubeConfigLoader_Call) RunAndReturn(run func() clientcmd.ClientConfig) *MockRESTClientGetter_ToRawKubeConfigLoader_Call {
	_c.Call.Return(run)
	return _c
}
