// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package discovery

import (
	"github.com/google/gnostic-models/openapiv2"
	mock "github.com/stretchr/testify/mock"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/version"
	"k8s.io/client-go/discovery"
	"k8s.io/client-go/openapi"
	"k8s.io/client-go/rest"
)

// NewMockCachedDiscoveryInterface creates a new instance of MockCachedDiscoveryInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCachedDiscoveryInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCachedDiscoveryInterface {
	mock := &MockCachedDiscoveryInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCachedDiscoveryInterface is an autogenerated mock type for the CachedDiscoveryInterface type
type MockCachedDiscoveryInterface struct {
	mock.Mock
}

type MockCachedDiscoveryInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCachedDiscoveryInterface) EXPECT() *MockCachedDiscoveryInterface_Expecter {
	return &MockCachedDiscoveryInterface_Expecter{mock: &_m.Mock}
}

// Fresh provides a mock function for the type MockCachedDiscoveryInterface
func (_mock *MockCachedDiscoveryInterface) Fresh() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Fresh")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockCachedDiscoveryInterface_Fresh_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Fresh'
type MockCachedDiscoveryInterface_Fresh_Call struct {
	*mock.Call
}

// Fresh is a helper method to define mock.On call
func (_e *MockCachedDiscoveryInterface_Expecter) Fresh() *MockCachedDiscoveryInterface_Fresh_Call {
	return &MockCachedDiscoveryInterface_Fresh_Call{Call: _e.mock.On("Fresh")}
}

func (_c *MockCachedDiscoveryInterface_Fresh_Call) Run(run func()) *MockCachedDiscoveryInterface_Fresh_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCachedDiscoveryInterface_Fresh_Call) Return(b bool) *MockCachedDiscoveryInterface_Fresh_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockCachedDiscoveryInterface_Fresh_Call) RunAndReturn(run func() bool) *MockCachedDiscoveryInterface_Fresh_Call {
	_c.Call.Return(run)
	return _c
}

// Invalidate provides a mock function for the type MockCachedDiscoveryInterface
func (_mock *MockCachedDiscoveryInterface) Invalidate() {
	_mock.Called()
	return
}

// MockCachedDiscoveryInterface_Invalidate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Invalidate'
type MockCachedDiscoveryInterface_Invalidate_Call struct {
	*mock.Call
}

// Invalidate is a helper method to define mock.On call
func (_e *MockCachedDiscoveryInterface_Expecter) Invalidate() *MockCachedDiscoveryInterface_Invalidate_Call {
	return &MockCachedDiscoveryInterface_Invalidate_Call{Call: _e.mock.On("Invalidate")}
}

func (_c *MockCachedDiscoveryInterface_Invalidate_Call) Run(run func()) *MockCachedDiscoveryInterface_Invalidate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCachedDiscoveryInterface_Invalidate_Call) Return() *MockCachedDiscoveryInterface_Invalidate_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockCachedDiscoveryInterface_Invalidate_Call) RunAndReturn(run func()) *MockCachedDiscoveryInterface_Invalidate_Call {
	_c.Run(run)
	return _c
}

// OpenAPISchema provides a mock function for the type MockCachedDiscoveryInterface
func (_mock *MockCachedDiscoveryInterface) OpenAPISchema() (*openapi_v2.Document, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for OpenAPISchema")
	}

	var r0 *openapi_v2.Document
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (*openapi_v2.Document, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() *openapi_v2.Document); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*openapi_v2.Document)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCachedDiscoveryInterface_OpenAPISchema_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OpenAPISchema'
type MockCachedDiscoveryInterface_OpenAPISchema_Call struct {
	*mock.Call
}

// OpenAPISchema is a helper method to define mock.On call
func (_e *MockCachedDiscoveryInterface_Expecter) OpenAPISchema() *MockCachedDiscoveryInterface_OpenAPISchema_Call {
	return &MockCachedDiscoveryInterface_OpenAPISchema_Call{Call: _e.mock.On("OpenAPISchema")}
}

func (_c *MockCachedDiscoveryInterface_OpenAPISchema_Call) Run(run func()) *MockCachedDiscoveryInterface_OpenAPISchema_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCachedDiscoveryInterface_OpenAPISchema_Call) Return(document *openapi_v2.Document, err error) *MockCachedDiscoveryInterface_OpenAPISchema_Call {
	_c.Call.Return(document, err)
	return _c
}

func (_c *MockCachedDiscoveryInterface_OpenAPISchema_Call) RunAndReturn(run func() (*openapi_v2.Document, error)) *MockCachedDiscoveryInterface_OpenAPISchema_Call {
	_c.Call.Return(run)
	return _c
}

// OpenAPIV3 provides a mock function for the type MockCachedDiscoveryInterface
func (_mock *MockCachedDiscoveryInterface) OpenAPIV3() openapi.Client {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for OpenAPIV3")
	}

	var r0 openapi.Client
	if returnFunc, ok := ret.Get(0).(func() openapi.Client); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(openapi.Client)
		}
	}
	return r0
}

// MockCachedDiscoveryInterface_OpenAPIV3_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OpenAPIV3'
type MockCachedDiscoveryInterface_OpenAPIV3_Call struct {
	*mock.Call
}

// OpenAPIV3 is a helper method to define mock.On call
func (_e *MockCachedDiscoveryInterface_Expecter) OpenAPIV3() *MockCachedDiscoveryInterface_OpenAPIV3_Call {
	return &MockCachedDiscoveryInterface_OpenAPIV3_Call{Call: _e.mock.On("OpenAPIV3")}
}

func (_c *MockCachedDiscoveryInterface_OpenAPIV3_Call) Run(run func()) *MockCachedDiscoveryInterface_OpenAPIV3_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCachedDiscoveryInterface_OpenAPIV3_Call) Return(client openapi.Client) *MockCachedDiscoveryInterface_OpenAPIV3_Call {
	_c.Call.Return(client)
	return _c
}

func (_c *MockCachedDiscoveryInterface_OpenAPIV3_Call) RunAndReturn(run func() openapi.Client) *MockCachedDiscoveryInterface_OpenAPIV3_Call {
	_c.Call.Return(run)
	return _c
}

// RESTClient provides a mock function for the type MockCachedDiscoveryInterface
func (_mock *MockCachedDiscoveryInterface) RESTClient() rest.Interface {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for RESTClient")
	}

	var r0 rest.Interface
	if returnFunc, ok := ret.Get(0).(func() rest.Interface); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(rest.Interface)
		}
	}
	return r0
}

// MockCachedDiscoveryInterface_RESTClient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RESTClient'
type MockCachedDiscoveryInterface_RESTClient_Call struct {
	*mock.Call
}

// RESTClient is a helper method to define mock.On call
func (_e *MockCachedDiscoveryInterface_Expecter) RESTClient() *MockCachedDiscoveryInterface_RESTClient_Call {
	return &MockCachedDiscoveryInterface_RESTClient_Call{Call: _e.mock.On("RESTClient")}
}

func (_c *MockCachedDiscoveryInterface_RESTClient_Call) Run(run func()) *MockCachedDiscoveryInterface_RESTClient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCachedDiscoveryInterface_RESTClient_Call) Return(interfaceParam rest.Interface) *MockCachedDiscoveryInterface_RESTClient_Call {
	_c.Call.Return(interfaceParam)
	return _c
}

func (_c *MockCachedDiscoveryInterface_RESTClient_Call) RunAndReturn(run func() rest.Interface) *MockCachedDiscoveryInterface_RESTClient_Call {
	_c.Call.Return(run)
	return _c
}

// ServerGroups provides a mock function for the type MockCachedDiscoveryInterface
func (_mock *MockCachedDiscoveryInterface) ServerGroups() (*v1.APIGroupList, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ServerGroups")
	}

	var r0 *v1.APIGroupList
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (*v1.APIGroupList, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() *v1.APIGroupList); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.APIGroupList)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCachedDiscoveryInterface_ServerGroups_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ServerGroups'
type MockCachedDiscoveryInterface_ServerGroups_Call struct {
	*mock.Call
}

// ServerGroups is a helper method to define mock.On call
func (_e *MockCachedDiscoveryInterface_Expecter) ServerGroups() *MockCachedDiscoveryInterface_ServerGroups_Call {
	return &MockCachedDiscoveryInterface_ServerGroups_Call{Call: _e.mock.On("ServerGroups")}
}

func (_c *MockCachedDiscoveryInterface_ServerGroups_Call) Run(run func()) *MockCachedDiscoveryInterface_ServerGroups_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCachedDiscoveryInterface_ServerGroups_Call) Return(aPIGroupList *v1.APIGroupList, err error) *MockCachedDiscoveryInterface_ServerGroups_Call {
	_c.Call.Return(aPIGroupList, err)
	return _c
}

func (_c *MockCachedDiscoveryInterface_ServerGroups_Call) RunAndReturn(run func() (*v1.APIGroupList, error)) *MockCachedDiscoveryInterface_ServerGroups_Call {
	_c.Call.Return(run)
	return _c
}

// ServerGroupsAndResources provides a mock function for the type MockCachedDiscoveryInterface
func (_mock *MockCachedDiscoveryInterface) ServerGroupsAndResources() ([]*v1.APIGroup, []*v1.APIResourceList, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ServerGroupsAndResources")
	}

	var r0 []*v1.APIGroup
	var r1 []*v1.APIResourceList
	var r2 error
	if returnFunc, ok := ret.Get(0).(func() ([]*v1.APIGroup, []*v1.APIResourceList, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []*v1.APIGroup); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*v1.APIGroup)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() []*v1.APIResourceList); ok {
		r1 = returnFunc()
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]*v1.APIResourceList)
		}
	}
	if returnFunc, ok := ret.Get(2).(func() error); ok {
		r2 = returnFunc()
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockCachedDiscoveryInterface_ServerGroupsAndResources_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ServerGroupsAndResources'
type MockCachedDiscoveryInterface_ServerGroupsAndResources_Call struct {
	*mock.Call
}

// ServerGroupsAndResources is a helper method to define mock.On call
func (_e *MockCachedDiscoveryInterface_Expecter) ServerGroupsAndResources() *MockCachedDiscoveryInterface_ServerGroupsAndResources_Call {
	return &MockCachedDiscoveryInterface_ServerGroupsAndResources_Call{Call: _e.mock.On("ServerGroupsAndResources")}
}

func (_c *MockCachedDiscoveryInterface_ServerGroupsAndResources_Call) Run(run func()) *MockCachedDiscoveryInterface_ServerGroupsAndResources_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCachedDiscoveryInterface_ServerGroupsAndResources_Call) Return(aPIGroups []*v1.APIGroup, aPIResourceLists []*v1.APIResourceList, err error) *MockCachedDiscoveryInterface_ServerGroupsAndResources_Call {
	_c.Call.Return(aPIGroups, aPIResourceLists, err)
	return _c
}

func (_c *MockCachedDiscoveryInterface_ServerGroupsAndResources_Call) RunAndReturn(run func() ([]*v1.APIGroup, []*v1.APIResourceList, error)) *MockCachedDiscoveryInterface_ServerGroupsAndResources_Call {
	_c.Call.Return(run)
	return _c
}

// ServerPreferredNamespacedResources provides a mock function for the type MockCachedDiscoveryInterface
func (_mock *MockCachedDiscoveryInterface) ServerPreferredNamespacedResources() ([]*v1.APIResourceList, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ServerPreferredNamespacedResources")
	}

	var r0 []*v1.APIResourceList
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]*v1.APIResourceList, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []*v1.APIResourceList); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*v1.APIResourceList)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCachedDiscoveryInterface_ServerPreferredNamespacedResources_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ServerPreferredNamespacedResources'
type MockCachedDiscoveryInterface_ServerPreferredNamespacedResources_Call struct {
	*mock.Call
}

// ServerPreferredNamespacedResources is a helper method to define mock.On call
func (_e *MockCachedDiscoveryInterface_Expecter) ServerPreferredNamespacedResources() *MockCachedDiscoveryInterface_ServerPreferredNamespacedResources_Call {
	return &MockCachedDiscoveryInterface_ServerPreferredNamespacedResources_Call{Call: _e.mock.On("ServerPreferredNamespacedResources")}
}

func (_c *MockCachedDiscoveryInterface_ServerPreferredNamespacedResources_Call) Run(run func()) *MockCachedDiscoveryInterface_ServerPreferredNamespacedResources_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCachedDiscoveryInterface_ServerPreferredNamespacedResources_Call) Return(aPIResourceLists []*v1.APIResourceList, err error) *MockCachedDiscoveryInterface_ServerPreferredNamespacedResources_Call {
	_c.Call.Return(aPIResourceLists, err)
	return _c
}

func (_c *MockCachedDiscoveryInterface_ServerPreferredNamespacedResources_Call) RunAndReturn(run func() ([]*v1.APIResourceList, error)) *MockCachedDiscoveryInterface_ServerPreferredNamespacedResources_Call {
	_c.Call.Return(run)
	return _c
}

// ServerPreferredResources provides a mock function for the type MockCachedDiscoveryInterface
func (_mock *MockCachedDiscoveryInterface) ServerPreferredResources() ([]*v1.APIResourceList, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ServerPreferredResources")
	}

	var r0 []*v1.APIResourceList
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]*v1.APIResourceList, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []*v1.APIResourceList); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*v1.APIResourceList)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCachedDiscoveryInterface_ServerPreferredResources_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ServerPreferredResources'
type MockCachedDiscoveryInterface_ServerPreferredResources_Call struct {
	*mock.Call
}

// ServerPreferredResources is a helper method to define mock.On call
func (_e *MockCachedDiscoveryInterface_Expecter) ServerPreferredResources() *MockCachedDiscoveryInterface_ServerPreferredResources_Call {
	return &MockCachedDiscoveryInterface_ServerPreferredResources_Call{Call: _e.mock.On("ServerPreferredResources")}
}

func (_c *MockCachedDiscoveryInterface_ServerPreferredResources_Call) Run(run func()) *MockCachedDiscoveryInterface_ServerPreferredResources_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCachedDiscoveryInterface_ServerPreferredResources_Call) Return(aPIResourceLists []*v1.APIResourceList, err error) *MockCachedDiscoveryInterface_ServerPreferredResources_Call {
	_c.Call.Return(aPIResourceLists, err)
	return _c
}

func (_c *MockCachedDiscoveryInterface_ServerPreferredResources_Call) RunAndReturn(run func() ([]*v1.APIResourceList, error)) *MockCachedDiscoveryInterface_ServerPreferredResources_Call {
	_c.Call.Return(run)
	return _c
}

// ServerResourcesForGroupVersion provides a mock function for the type MockCachedDiscoveryInterface
func (_mock *MockCachedDiscoveryInterface) ServerResourcesForGroupVersion(groupVersion string) (*v1.APIResourceList, error) {
	ret := _mock.Called(groupVersion)

	if len(ret) == 0 {
		panic("no return value specified for ServerResourcesForGroupVersion")
	}

	var r0 *v1.APIResourceList
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*v1.APIResourceList, error)); ok {
		return returnFunc(groupVersion)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *v1.APIResourceList); ok {
		r0 = returnFunc(groupVersion)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.APIResourceList)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(groupVersion)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCachedDiscoveryInterface_ServerResourcesForGroupVersion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ServerResourcesForGroupVersion'
type MockCachedDiscoveryInterface_ServerResourcesForGroupVersion_Call struct {
	*mock.Call
}

// ServerResourcesForGroupVersion is a helper method to define mock.On call
//   - groupVersion string
func (_e *MockCachedDiscoveryInterface_Expecter) ServerResourcesForGroupVersion(groupVersion interface{}) *MockCachedDiscoveryInterface_ServerResourcesForGroupVersion_Call {
	return &MockCachedDiscoveryInterface_ServerResourcesForGroupVersion_Call{Call: _e.mock.On("ServerResourcesForGroupVersion", groupVersion)}
}

func (_c *MockCachedDiscoveryInterface_ServerResourcesForGroupVersion_Call) Run(run func(groupVersion string)) *MockCachedDiscoveryInterface_ServerResourcesForGroupVersion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCachedDiscoveryInterface_ServerResourcesForGroupVersion_Call) Return(aPIResourceList *v1.APIResourceList, err error) *MockCachedDiscoveryInterface_ServerResourcesForGroupVersion_Call {
	_c.Call.Return(aPIResourceList, err)
	return _c
}

func (_c *MockCachedDiscoveryInterface_ServerResourcesForGroupVersion_Call) RunAndReturn(run func(groupVersion string) (*v1.APIResourceList, error)) *MockCachedDiscoveryInterface_ServerResourcesForGroupVersion_Call {
	_c.Call.Return(run)
	return _c
}

// ServerVersion provides a mock function for the type MockCachedDiscoveryInterface
func (_mock *MockCachedDiscoveryInterface) ServerVersion() (*version.Info, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ServerVersion")
	}

	var r0 *version.Info
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (*version.Info, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() *version.Info); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*version.Info)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCachedDiscoveryInterface_ServerVersion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ServerVersion'
type MockCachedDiscoveryInterface_ServerVersion_Call struct {
	*mock.Call
}

// ServerVersion is a helper method to define mock.On call
func (_e *MockCachedDiscoveryInterface_Expecter) ServerVersion() *MockCachedDiscoveryInterface_ServerVersion_Call {
	return &MockCachedDiscoveryInterface_ServerVersion_Call{Call: _e.mock.On("ServerVersion")}
}

func (_c *MockCachedDiscoveryInterface_ServerVersion_Call) Run(run func()) *MockCachedDiscoveryInterface_ServerVersion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCachedDiscoveryInterface_ServerVersion_Call) Return(info *version.Info, err error) *MockCachedDiscoveryInterface_ServerVersion_Call {
	_c.Call.Return(info, err)
	return _c
}

func (_c *MockCachedDiscoveryInterface_ServerVersion_Call) RunAndReturn(run func() (*version.Info, error)) *MockCachedDiscoveryInterface_ServerVersion_Call {
	_c.Call.Return(run)
	return _c
}

// WithLegacy provides a mock function for the type MockCachedDiscoveryInterface
func (_mock *MockCachedDiscoveryInterface) WithLegacy() discovery.DiscoveryInterface {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for WithLegacy")
	}

	var r0 discovery.DiscoveryInterface
	if returnFunc, ok := ret.Get(0).(func() discovery.DiscoveryInterface); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(discovery.DiscoveryInterface)
		}
	}
	return r0
}

// MockCachedDiscoveryInterface_WithLegacy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithLegacy'
type MockCachedDiscoveryInterface_WithLegacy_Call struct {
	*mock.Call
}

// WithLegacy is a helper method to define mock.On call
func (_e *MockCachedDiscoveryInterface_Expecter) WithLegacy() *MockCachedDiscoveryInterface_WithLegacy_Call {
	return &MockCachedDiscoveryInterface_WithLegacy_Call{Call: _e.mock.On("WithLegacy")}
}

func (_c *MockCachedDiscoveryInterface_WithLegacy_Call) Run(run func()) *MockCachedDiscoveryInterface_WithLegacy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCachedDiscoveryInterface_WithLegacy_Call) Return(discoveryInterface discovery.DiscoveryInterface) *MockCachedDiscoveryInterface_WithLegacy_Call {
	_c.Call.Return(discoveryInterface)
	return _c
}

func (_c *MockCachedDiscoveryInterface_WithLegacy_Call) RunAndReturn(run func() discovery.DiscoveryInterface) *MockCachedDiscoveryInterface_WithLegacy_Call {
	_c.Call.Return(run)
	return _c
}
