// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package util

import (
	"github.com/sirupsen/logrus"
	"github.com/spf13/viper"
	mock "github.com/stretchr/testify/mock"
)

// NewMockCmdInterface creates a new instance of MockCmdInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCmdInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCmdInterface {
	mock := &MockCmdInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCmdInterface is an autogenerated mock type for the CmdInterface type
type MockCmdInterface struct {
	mock.Mock
}

type MockCmdInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCmdInterface) EXPECT() *MockCmdInterface_Expecter {
	return &MockCmdInterface_Expecter{mock: &_m.Mock}
}

// Logger provides a mock function for the type MockCmdInterface
func (_mock *MockCmdInterface) Logger() logrus.FieldLogger {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Logger")
	}

	var r0 logrus.FieldLogger
	if returnFunc, ok := ret.Get(0).(func() logrus.FieldLogger); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(logrus.FieldLogger)
		}
	}
	return r0
}

// MockCmdInterface_Logger_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Logger'
type MockCmdInterface_Logger_Call struct {
	*mock.Call
}

// Logger is a helper method to define mock.On call
func (_e *MockCmdInterface_Expecter) Logger() *MockCmdInterface_Logger_Call {
	return &MockCmdInterface_Logger_Call{Call: _e.mock.On("Logger")}
}

func (_c *MockCmdInterface_Logger_Call) Run(run func()) *MockCmdInterface_Logger_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCmdInterface_Logger_Call) Return(fieldLogger logrus.FieldLogger) *MockCmdInterface_Logger_Call {
	_c.Call.Return(fieldLogger)
	return _c
}

func (_c *MockCmdInterface_Logger_Call) RunAndReturn(run func() logrus.FieldLogger) *MockCmdInterface_Logger_Call {
	_c.Call.Return(run)
	return _c
}

// Viper provides a mock function for the type MockCmdInterface
func (_mock *MockCmdInterface) Viper() *viper.Viper {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Viper")
	}

	var r0 *viper.Viper
	if returnFunc, ok := ret.Get(0).(func() *viper.Viper); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*viper.Viper)
		}
	}
	return r0
}

// MockCmdInterface_Viper_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Viper'
type MockCmdInterface_Viper_Call struct {
	*mock.Call
}

// Viper is a helper method to define mock.On call
func (_e *MockCmdInterface_Expecter) Viper() *MockCmdInterface_Viper_Call {
	return &MockCmdInterface_Viper_Call{Call: _e.mock.On("Viper")}
}

func (_c *MockCmdInterface_Viper_Call) Run(run func()) *MockCmdInterface_Viper_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCmdInterface_Viper_Call) Return(viper1 *viper.Viper) *MockCmdInterface_Viper_Call {
	_c.Call.Return(viper1)
	return _c
}

func (_c *MockCmdInterface_Viper_Call) RunAndReturn(run func() *viper.Viper) *MockCmdInterface_Viper_Call {
	_c.Call.Return(run)
	return _c
}
