// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package rest

import (
	mock "github.com/stretchr/testify/mock"
	"k8s.io/apimachinery/pkg/runtime/schema"
	"k8s.io/apimachinery/pkg/types"
	"k8s.io/client-go/rest"
	"k8s.io/client-go/util/flowcontrol"
)

// NewMockInterface creates a new instance of MockInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockInterface {
	mock := &MockInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockInterface is an autogenerated mock type for the Interface type
type MockInterface struct {
	mock.Mock
}

type MockInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockInterface) EXPECT() *MockInterface_Expecter {
	return &MockInterface_Expecter{mock: &_m.Mock}
}

// APIVersion provides a mock function for the type MockInterface
func (_mock *MockInterface) APIVersion() schema.GroupVersion {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for APIVersion")
	}

	var r0 schema.GroupVersion
	if returnFunc, ok := ret.Get(0).(func() schema.GroupVersion); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(schema.GroupVersion)
	}
	return r0
}

// MockInterface_APIVersion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'APIVersion'
type MockInterface_APIVersion_Call struct {
	*mock.Call
}

// APIVersion is a helper method to define mock.On call
func (_e *MockInterface_Expecter) APIVersion() *MockInterface_APIVersion_Call {
	return &MockInterface_APIVersion_Call{Call: _e.mock.On("APIVersion")}
}

func (_c *MockInterface_APIVersion_Call) Run(run func()) *MockInterface_APIVersion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockInterface_APIVersion_Call) Return(groupVersion schema.GroupVersion) *MockInterface_APIVersion_Call {
	_c.Call.Return(groupVersion)
	return _c
}

func (_c *MockInterface_APIVersion_Call) RunAndReturn(run func() schema.GroupVersion) *MockInterface_APIVersion_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockInterface
func (_mock *MockInterface) Delete() *rest.Request {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 *rest.Request
	if returnFunc, ok := ret.Get(0).(func() *rest.Request); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*rest.Request)
		}
	}
	return r0
}

// MockInterface_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockInterface_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
func (_e *MockInterface_Expecter) Delete() *MockInterface_Delete_Call {
	return &MockInterface_Delete_Call{Call: _e.mock.On("Delete")}
}

func (_c *MockInterface_Delete_Call) Run(run func()) *MockInterface_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockInterface_Delete_Call) Return(request *rest.Request) *MockInterface_Delete_Call {
	_c.Call.Return(request)
	return _c
}

func (_c *MockInterface_Delete_Call) RunAndReturn(run func() *rest.Request) *MockInterface_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockInterface
func (_mock *MockInterface) Get() *rest.Request {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *rest.Request
	if returnFunc, ok := ret.Get(0).(func() *rest.Request); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*rest.Request)
		}
	}
	return r0
}

// MockInterface_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockInterface_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
func (_e *MockInterface_Expecter) Get() *MockInterface_Get_Call {
	return &MockInterface_Get_Call{Call: _e.mock.On("Get")}
}

func (_c *MockInterface_Get_Call) Run(run func()) *MockInterface_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockInterface_Get_Call) Return(request *rest.Request) *MockInterface_Get_Call {
	_c.Call.Return(request)
	return _c
}

func (_c *MockInterface_Get_Call) RunAndReturn(run func() *rest.Request) *MockInterface_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetRateLimiter provides a mock function for the type MockInterface
func (_mock *MockInterface) GetRateLimiter() flowcontrol.RateLimiter {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetRateLimiter")
	}

	var r0 flowcontrol.RateLimiter
	if returnFunc, ok := ret.Get(0).(func() flowcontrol.RateLimiter); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(flowcontrol.RateLimiter)
		}
	}
	return r0
}

// MockInterface_GetRateLimiter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRateLimiter'
type MockInterface_GetRateLimiter_Call struct {
	*mock.Call
}

// GetRateLimiter is a helper method to define mock.On call
func (_e *MockInterface_Expecter) GetRateLimiter() *MockInterface_GetRateLimiter_Call {
	return &MockInterface_GetRateLimiter_Call{Call: _e.mock.On("GetRateLimiter")}
}

func (_c *MockInterface_GetRateLimiter_Call) Run(run func()) *MockInterface_GetRateLimiter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockInterface_GetRateLimiter_Call) Return(rateLimiter flowcontrol.RateLimiter) *MockInterface_GetRateLimiter_Call {
	_c.Call.Return(rateLimiter)
	return _c
}

func (_c *MockInterface_GetRateLimiter_Call) RunAndReturn(run func() flowcontrol.RateLimiter) *MockInterface_GetRateLimiter_Call {
	_c.Call.Return(run)
	return _c
}

// Patch provides a mock function for the type MockInterface
func (_mock *MockInterface) Patch(pt types.PatchType) *rest.Request {
	ret := _mock.Called(pt)

	if len(ret) == 0 {
		panic("no return value specified for Patch")
	}

	var r0 *rest.Request
	if returnFunc, ok := ret.Get(0).(func(types.PatchType) *rest.Request); ok {
		r0 = returnFunc(pt)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*rest.Request)
		}
	}
	return r0
}

// MockInterface_Patch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Patch'
type MockInterface_Patch_Call struct {
	*mock.Call
}

// Patch is a helper method to define mock.On call
//   - pt types.PatchType
func (_e *MockInterface_Expecter) Patch(pt interface{}) *MockInterface_Patch_Call {
	return &MockInterface_Patch_Call{Call: _e.mock.On("Patch", pt)}
}

func (_c *MockInterface_Patch_Call) Run(run func(pt types.PatchType)) *MockInterface_Patch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 types.PatchType
		if args[0] != nil {
			arg0 = args[0].(types.PatchType)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockInterface_Patch_Call) Return(request *rest.Request) *MockInterface_Patch_Call {
	_c.Call.Return(request)
	return _c
}

func (_c *MockInterface_Patch_Call) RunAndReturn(run func(pt types.PatchType) *rest.Request) *MockInterface_Patch_Call {
	_c.Call.Return(run)
	return _c
}

// Post provides a mock function for the type MockInterface
func (_mock *MockInterface) Post() *rest.Request {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Post")
	}

	var r0 *rest.Request
	if returnFunc, ok := ret.Get(0).(func() *rest.Request); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*rest.Request)
		}
	}
	return r0
}

// MockInterface_Post_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Post'
type MockInterface_Post_Call struct {
	*mock.Call
}

// Post is a helper method to define mock.On call
func (_e *MockInterface_Expecter) Post() *MockInterface_Post_Call {
	return &MockInterface_Post_Call{Call: _e.mock.On("Post")}
}

func (_c *MockInterface_Post_Call) Run(run func()) *MockInterface_Post_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockInterface_Post_Call) Return(request *rest.Request) *MockInterface_Post_Call {
	_c.Call.Return(request)
	return _c
}

func (_c *MockInterface_Post_Call) RunAndReturn(run func() *rest.Request) *MockInterface_Post_Call {
	_c.Call.Return(run)
	return _c
}

// Put provides a mock function for the type MockInterface
func (_mock *MockInterface) Put() *rest.Request {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Put")
	}

	var r0 *rest.Request
	if returnFunc, ok := ret.Get(0).(func() *rest.Request); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*rest.Request)
		}
	}
	return r0
}

// MockInterface_Put_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Put'
type MockInterface_Put_Call struct {
	*mock.Call
}

// Put is a helper method to define mock.On call
func (_e *MockInterface_Expecter) Put() *MockInterface_Put_Call {
	return &MockInterface_Put_Call{Call: _e.mock.On("Put")}
}

func (_c *MockInterface_Put_Call) Run(run func()) *MockInterface_Put_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockInterface_Put_Call) Return(request *rest.Request) *MockInterface_Put_Call {
	_c.Call.Return(request)
	return _c
}

func (_c *MockInterface_Put_Call) RunAndReturn(run func() *rest.Request) *MockInterface_Put_Call {
	_c.Call.Return(run)
	return _c
}

// Verb provides a mock function for the type MockInterface
func (_mock *MockInterface) Verb(verb string) *rest.Request {
	ret := _mock.Called(verb)

	if len(ret) == 0 {
		panic("no return value specified for Verb")
	}

	var r0 *rest.Request
	if returnFunc, ok := ret.Get(0).(func(string) *rest.Request); ok {
		r0 = returnFunc(verb)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*rest.Request)
		}
	}
	return r0
}

// MockInterface_Verb_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Verb'
type MockInterface_Verb_Call struct {
	*mock.Call
}

// Verb is a helper method to define mock.On call
//   - verb string
func (_e *MockInterface_Expecter) Verb(verb interface{}) *MockInterface_Verb_Call {
	return &MockInterface_Verb_Call{Call: _e.mock.On("Verb", verb)}
}

func (_c *MockInterface_Verb_Call) Run(run func(verb string)) *MockInterface_Verb_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockInterface_Verb_Call) Return(request *rest.Request) *MockInterface_Verb_Call {
	_c.Call.Return(request)
	return _c
}

func (_c *MockInterface_Verb_Call) RunAndReturn(run func(verb string) *rest.Request) *MockInterface_Verb_Call {
	_c.Call.Return(run)
	return _c
}
