// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package v1

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	v11 "k8s.io/api/core/v1"
	v10 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/types"
	"k8s.io/apimachinery/pkg/watch"
	"k8s.io/client-go/applyconfigurations/core/v1"
	"k8s.io/client-go/rest"
)

// NewMockServiceInterface creates a new instance of MockServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockServiceInterface {
	mock := &MockServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockServiceInterface is an autogenerated mock type for the ServiceInterface type
type MockServiceInterface struct {
	mock.Mock
}

type MockServiceInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockServiceInterface) EXPECT() *MockServiceInterface_Expecter {
	return &MockServiceInterface_Expecter{mock: &_m.Mock}
}

// Apply provides a mock function for the type MockServiceInterface
func (_mock *MockServiceInterface) Apply(ctx context.Context, service *v1.ServiceApplyConfiguration, opts v10.ApplyOptions) (*v11.Service, error) {
	ret := _mock.Called(ctx, service, opts)

	if len(ret) == 0 {
		panic("no return value specified for Apply")
	}

	var r0 *v11.Service
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1.ServiceApplyConfiguration, v10.ApplyOptions) (*v11.Service, error)); ok {
		return returnFunc(ctx, service, opts)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1.ServiceApplyConfiguration, v10.ApplyOptions) *v11.Service); ok {
		r0 = returnFunc(ctx, service, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v11.Service)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *v1.ServiceApplyConfiguration, v10.ApplyOptions) error); ok {
		r1 = returnFunc(ctx, service, opts)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockServiceInterface_Apply_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Apply'
type MockServiceInterface_Apply_Call struct {
	*mock.Call
}

// Apply is a helper method to define mock.On call
//   - ctx context.Context
//   - service *v1.ServiceApplyConfiguration
//   - opts v10.ApplyOptions
func (_e *MockServiceInterface_Expecter) Apply(ctx interface{}, service interface{}, opts interface{}) *MockServiceInterface_Apply_Call {
	return &MockServiceInterface_Apply_Call{Call: _e.mock.On("Apply", ctx, service, opts)}
}

func (_c *MockServiceInterface_Apply_Call) Run(run func(ctx context.Context, service *v1.ServiceApplyConfiguration, opts v10.ApplyOptions)) *MockServiceInterface_Apply_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *v1.ServiceApplyConfiguration
		if args[1] != nil {
			arg1 = args[1].(*v1.ServiceApplyConfiguration)
		}
		var arg2 v10.ApplyOptions
		if args[2] != nil {
			arg2 = args[2].(v10.ApplyOptions)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockServiceInterface_Apply_Call) Return(result *v11.Service, err error) *MockServiceInterface_Apply_Call {
	_c.Call.Return(result, err)
	return _c
}

func (_c *MockServiceInterface_Apply_Call) RunAndReturn(run func(ctx context.Context, service *v1.ServiceApplyConfiguration, opts v10.ApplyOptions) (*v11.Service, error)) *MockServiceInterface_Apply_Call {
	_c.Call.Return(run)
	return _c
}

// ApplyStatus provides a mock function for the type MockServiceInterface
func (_mock *MockServiceInterface) ApplyStatus(ctx context.Context, service *v1.ServiceApplyConfiguration, opts v10.ApplyOptions) (*v11.Service, error) {
	ret := _mock.Called(ctx, service, opts)

	if len(ret) == 0 {
		panic("no return value specified for ApplyStatus")
	}

	var r0 *v11.Service
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1.ServiceApplyConfiguration, v10.ApplyOptions) (*v11.Service, error)); ok {
		return returnFunc(ctx, service, opts)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1.ServiceApplyConfiguration, v10.ApplyOptions) *v11.Service); ok {
		r0 = returnFunc(ctx, service, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v11.Service)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *v1.ServiceApplyConfiguration, v10.ApplyOptions) error); ok {
		r1 = returnFunc(ctx, service, opts)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockServiceInterface_ApplyStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ApplyStatus'
type MockServiceInterface_ApplyStatus_Call struct {
	*mock.Call
}

// ApplyStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - service *v1.ServiceApplyConfiguration
//   - opts v10.ApplyOptions
func (_e *MockServiceInterface_Expecter) ApplyStatus(ctx interface{}, service interface{}, opts interface{}) *MockServiceInterface_ApplyStatus_Call {
	return &MockServiceInterface_ApplyStatus_Call{Call: _e.mock.On("ApplyStatus", ctx, service, opts)}
}

func (_c *MockServiceInterface_ApplyStatus_Call) Run(run func(ctx context.Context, service *v1.ServiceApplyConfiguration, opts v10.ApplyOptions)) *MockServiceInterface_ApplyStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *v1.ServiceApplyConfiguration
		if args[1] != nil {
			arg1 = args[1].(*v1.ServiceApplyConfiguration)
		}
		var arg2 v10.ApplyOptions
		if args[2] != nil {
			arg2 = args[2].(v10.ApplyOptions)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockServiceInterface_ApplyStatus_Call) Return(result *v11.Service, err error) *MockServiceInterface_ApplyStatus_Call {
	_c.Call.Return(result, err)
	return _c
}

func (_c *MockServiceInterface_ApplyStatus_Call) RunAndReturn(run func(ctx context.Context, service *v1.ServiceApplyConfiguration, opts v10.ApplyOptions) (*v11.Service, error)) *MockServiceInterface_ApplyStatus_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type MockServiceInterface
func (_mock *MockServiceInterface) Create(ctx context.Context, service *v11.Service, opts v10.CreateOptions) (*v11.Service, error) {
	ret := _mock.Called(ctx, service, opts)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *v11.Service
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v11.Service, v10.CreateOptions) (*v11.Service, error)); ok {
		return returnFunc(ctx, service, opts)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v11.Service, v10.CreateOptions) *v11.Service); ok {
		r0 = returnFunc(ctx, service, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v11.Service)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *v11.Service, v10.CreateOptions) error); ok {
		r1 = returnFunc(ctx, service, opts)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockServiceInterface_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockServiceInterface_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - service *v11.Service
//   - opts v10.CreateOptions
func (_e *MockServiceInterface_Expecter) Create(ctx interface{}, service interface{}, opts interface{}) *MockServiceInterface_Create_Call {
	return &MockServiceInterface_Create_Call{Call: _e.mock.On("Create", ctx, service, opts)}
}

func (_c *MockServiceInterface_Create_Call) Run(run func(ctx context.Context, service *v11.Service, opts v10.CreateOptions)) *MockServiceInterface_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *v11.Service
		if args[1] != nil {
			arg1 = args[1].(*v11.Service)
		}
		var arg2 v10.CreateOptions
		if args[2] != nil {
			arg2 = args[2].(v10.CreateOptions)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockServiceInterface_Create_Call) Return(service1 *v11.Service, err error) *MockServiceInterface_Create_Call {
	_c.Call.Return(service1, err)
	return _c
}

func (_c *MockServiceInterface_Create_Call) RunAndReturn(run func(ctx context.Context, service *v11.Service, opts v10.CreateOptions) (*v11.Service, error)) *MockServiceInterface_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockServiceInterface
func (_mock *MockServiceInterface) Delete(ctx context.Context, name string, opts v10.DeleteOptions) error {
	ret := _mock.Called(ctx, name, opts)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, v10.DeleteOptions) error); ok {
		r0 = returnFunc(ctx, name, opts)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockServiceInterface_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockServiceInterface_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - opts v10.DeleteOptions
func (_e *MockServiceInterface_Expecter) Delete(ctx interface{}, name interface{}, opts interface{}) *MockServiceInterface_Delete_Call {
	return &MockServiceInterface_Delete_Call{Call: _e.mock.On("Delete", ctx, name, opts)}
}

func (_c *MockServiceInterface_Delete_Call) Run(run func(ctx context.Context, name string, opts v10.DeleteOptions)) *MockServiceInterface_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 v10.DeleteOptions
		if args[2] != nil {
			arg2 = args[2].(v10.DeleteOptions)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockServiceInterface_Delete_Call) Return(err error) *MockServiceInterface_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockServiceInterface_Delete_Call) RunAndReturn(run func(ctx context.Context, name string, opts v10.DeleteOptions) error) *MockServiceInterface_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockServiceInterface
func (_mock *MockServiceInterface) Get(ctx context.Context, name string, opts v10.GetOptions) (*v11.Service, error) {
	ret := _mock.Called(ctx, name, opts)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *v11.Service
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, v10.GetOptions) (*v11.Service, error)); ok {
		return returnFunc(ctx, name, opts)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, v10.GetOptions) *v11.Service); ok {
		r0 = returnFunc(ctx, name, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v11.Service)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, v10.GetOptions) error); ok {
		r1 = returnFunc(ctx, name, opts)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockServiceInterface_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockServiceInterface_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - opts v10.GetOptions
func (_e *MockServiceInterface_Expecter) Get(ctx interface{}, name interface{}, opts interface{}) *MockServiceInterface_Get_Call {
	return &MockServiceInterface_Get_Call{Call: _e.mock.On("Get", ctx, name, opts)}
}

func (_c *MockServiceInterface_Get_Call) Run(run func(ctx context.Context, name string, opts v10.GetOptions)) *MockServiceInterface_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 v10.GetOptions
		if args[2] != nil {
			arg2 = args[2].(v10.GetOptions)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockServiceInterface_Get_Call) Return(service *v11.Service, err error) *MockServiceInterface_Get_Call {
	_c.Call.Return(service, err)
	return _c
}

func (_c *MockServiceInterface_Get_Call) RunAndReturn(run func(ctx context.Context, name string, opts v10.GetOptions) (*v11.Service, error)) *MockServiceInterface_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockServiceInterface
func (_mock *MockServiceInterface) List(ctx context.Context, opts v10.ListOptions) (*v11.ServiceList, error) {
	ret := _mock.Called(ctx, opts)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 *v11.ServiceList
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, v10.ListOptions) (*v11.ServiceList, error)); ok {
		return returnFunc(ctx, opts)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, v10.ListOptions) *v11.ServiceList); ok {
		r0 = returnFunc(ctx, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v11.ServiceList)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, v10.ListOptions) error); ok {
		r1 = returnFunc(ctx, opts)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockServiceInterface_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockServiceInterface_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - opts v10.ListOptions
func (_e *MockServiceInterface_Expecter) List(ctx interface{}, opts interface{}) *MockServiceInterface_List_Call {
	return &MockServiceInterface_List_Call{Call: _e.mock.On("List", ctx, opts)}
}

func (_c *MockServiceInterface_List_Call) Run(run func(ctx context.Context, opts v10.ListOptions)) *MockServiceInterface_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 v10.ListOptions
		if args[1] != nil {
			arg1 = args[1].(v10.ListOptions)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockServiceInterface_List_Call) Return(serviceList *v11.ServiceList, err error) *MockServiceInterface_List_Call {
	_c.Call.Return(serviceList, err)
	return _c
}

func (_c *MockServiceInterface_List_Call) RunAndReturn(run func(ctx context.Context, opts v10.ListOptions) (*v11.ServiceList, error)) *MockServiceInterface_List_Call {
	_c.Call.Return(run)
	return _c
}

// Patch provides a mock function for the type MockServiceInterface
func (_mock *MockServiceInterface) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v10.PatchOptions, subresources ...string) (*v11.Service, error) {
	var tmpRet mock.Arguments
	if len(subresources) > 0 {
		tmpRet = _mock.Called(ctx, name, pt, data, opts, subresources)
	} else {
		tmpRet = _mock.Called(ctx, name, pt, data, opts)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Patch")
	}

	var r0 *v11.Service
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, types.PatchType, []byte, v10.PatchOptions, ...string) (*v11.Service, error)); ok {
		return returnFunc(ctx, name, pt, data, opts, subresources...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, types.PatchType, []byte, v10.PatchOptions, ...string) *v11.Service); ok {
		r0 = returnFunc(ctx, name, pt, data, opts, subresources...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v11.Service)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, types.PatchType, []byte, v10.PatchOptions, ...string) error); ok {
		r1 = returnFunc(ctx, name, pt, data, opts, subresources...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockServiceInterface_Patch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Patch'
type MockServiceInterface_Patch_Call struct {
	*mock.Call
}

// Patch is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - pt types.PatchType
//   - data []byte
//   - opts v10.PatchOptions
//   - subresources ...string
func (_e *MockServiceInterface_Expecter) Patch(ctx interface{}, name interface{}, pt interface{}, data interface{}, opts interface{}, subresources ...interface{}) *MockServiceInterface_Patch_Call {
	return &MockServiceInterface_Patch_Call{Call: _e.mock.On("Patch",
		append([]interface{}{ctx, name, pt, data, opts}, subresources...)...)}
}

func (_c *MockServiceInterface_Patch_Call) Run(run func(ctx context.Context, name string, pt types.PatchType, data []byte, opts v10.PatchOptions, subresources ...string)) *MockServiceInterface_Patch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 types.PatchType
		if args[2] != nil {
			arg2 = args[2].(types.PatchType)
		}
		var arg3 []byte
		if args[3] != nil {
			arg3 = args[3].([]byte)
		}
		var arg4 v10.PatchOptions
		if args[4] != nil {
			arg4 = args[4].(v10.PatchOptions)
		}
		var arg5 []string
		var variadicArgs []string
		if len(args) > 5 {
			variadicArgs = args[5].([]string)
		}
		arg5 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5...,
		)
	})
	return _c
}

func (_c *MockServiceInterface_Patch_Call) Return(result *v11.Service, err error) *MockServiceInterface_Patch_Call {
	_c.Call.Return(result, err)
	return _c
}

func (_c *MockServiceInterface_Patch_Call) RunAndReturn(run func(ctx context.Context, name string, pt types.PatchType, data []byte, opts v10.PatchOptions, subresources ...string) (*v11.Service, error)) *MockServiceInterface_Patch_Call {
	_c.Call.Return(run)
	return _c
}

// ProxyGet provides a mock function for the type MockServiceInterface
func (_mock *MockServiceInterface) ProxyGet(scheme string, name string, port string, path string, params map[string]string) rest.ResponseWrapper {
	ret := _mock.Called(scheme, name, port, path, params)

	if len(ret) == 0 {
		panic("no return value specified for ProxyGet")
	}

	var r0 rest.ResponseWrapper
	if returnFunc, ok := ret.Get(0).(func(string, string, string, string, map[string]string) rest.ResponseWrapper); ok {
		r0 = returnFunc(scheme, name, port, path, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(rest.ResponseWrapper)
		}
	}
	return r0
}

// MockServiceInterface_ProxyGet_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ProxyGet'
type MockServiceInterface_ProxyGet_Call struct {
	*mock.Call
}

// ProxyGet is a helper method to define mock.On call
//   - scheme string
//   - name string
//   - port string
//   - path string
//   - params map[string]string
func (_e *MockServiceInterface_Expecter) ProxyGet(scheme interface{}, name interface{}, port interface{}, path interface{}, params interface{}) *MockServiceInterface_ProxyGet_Call {
	return &MockServiceInterface_ProxyGet_Call{Call: _e.mock.On("ProxyGet", scheme, name, port, path, params)}
}

func (_c *MockServiceInterface_ProxyGet_Call) Run(run func(scheme string, name string, port string, path string, params map[string]string)) *MockServiceInterface_ProxyGet_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 map[string]string
		if args[4] != nil {
			arg4 = args[4].(map[string]string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockServiceInterface_ProxyGet_Call) Return(responseWrapper rest.ResponseWrapper) *MockServiceInterface_ProxyGet_Call {
	_c.Call.Return(responseWrapper)
	return _c
}

func (_c *MockServiceInterface_ProxyGet_Call) RunAndReturn(run func(scheme string, name string, port string, path string, params map[string]string) rest.ResponseWrapper) *MockServiceInterface_ProxyGet_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockServiceInterface
func (_mock *MockServiceInterface) Update(ctx context.Context, service *v11.Service, opts v10.UpdateOptions) (*v11.Service, error) {
	ret := _mock.Called(ctx, service, opts)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *v11.Service
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v11.Service, v10.UpdateOptions) (*v11.Service, error)); ok {
		return returnFunc(ctx, service, opts)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v11.Service, v10.UpdateOptions) *v11.Service); ok {
		r0 = returnFunc(ctx, service, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v11.Service)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *v11.Service, v10.UpdateOptions) error); ok {
		r1 = returnFunc(ctx, service, opts)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockServiceInterface_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockServiceInterface_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - service *v11.Service
//   - opts v10.UpdateOptions
func (_e *MockServiceInterface_Expecter) Update(ctx interface{}, service interface{}, opts interface{}) *MockServiceInterface_Update_Call {
	return &MockServiceInterface_Update_Call{Call: _e.mock.On("Update", ctx, service, opts)}
}

func (_c *MockServiceInterface_Update_Call) Run(run func(ctx context.Context, service *v11.Service, opts v10.UpdateOptions)) *MockServiceInterface_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *v11.Service
		if args[1] != nil {
			arg1 = args[1].(*v11.Service)
		}
		var arg2 v10.UpdateOptions
		if args[2] != nil {
			arg2 = args[2].(v10.UpdateOptions)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockServiceInterface_Update_Call) Return(service1 *v11.Service, err error) *MockServiceInterface_Update_Call {
	_c.Call.Return(service1, err)
	return _c
}

func (_c *MockServiceInterface_Update_Call) RunAndReturn(run func(ctx context.Context, service *v11.Service, opts v10.UpdateOptions) (*v11.Service, error)) *MockServiceInterface_Update_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateStatus provides a mock function for the type MockServiceInterface
func (_mock *MockServiceInterface) UpdateStatus(ctx context.Context, service *v11.Service, opts v10.UpdateOptions) (*v11.Service, error) {
	ret := _mock.Called(ctx, service, opts)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatus")
	}

	var r0 *v11.Service
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v11.Service, v10.UpdateOptions) (*v11.Service, error)); ok {
		return returnFunc(ctx, service, opts)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v11.Service, v10.UpdateOptions) *v11.Service); ok {
		r0 = returnFunc(ctx, service, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v11.Service)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *v11.Service, v10.UpdateOptions) error); ok {
		r1 = returnFunc(ctx, service, opts)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockServiceInterface_UpdateStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateStatus'
type MockServiceInterface_UpdateStatus_Call struct {
	*mock.Call
}

// UpdateStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - service *v11.Service
//   - opts v10.UpdateOptions
func (_e *MockServiceInterface_Expecter) UpdateStatus(ctx interface{}, service interface{}, opts interface{}) *MockServiceInterface_UpdateStatus_Call {
	return &MockServiceInterface_UpdateStatus_Call{Call: _e.mock.On("UpdateStatus", ctx, service, opts)}
}

func (_c *MockServiceInterface_UpdateStatus_Call) Run(run func(ctx context.Context, service *v11.Service, opts v10.UpdateOptions)) *MockServiceInterface_UpdateStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *v11.Service
		if args[1] != nil {
			arg1 = args[1].(*v11.Service)
		}
		var arg2 v10.UpdateOptions
		if args[2] != nil {
			arg2 = args[2].(v10.UpdateOptions)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockServiceInterface_UpdateStatus_Call) Return(service1 *v11.Service, err error) *MockServiceInterface_UpdateStatus_Call {
	_c.Call.Return(service1, err)
	return _c
}

func (_c *MockServiceInterface_UpdateStatus_Call) RunAndReturn(run func(ctx context.Context, service *v11.Service, opts v10.UpdateOptions) (*v11.Service, error)) *MockServiceInterface_UpdateStatus_Call {
	_c.Call.Return(run)
	return _c
}

// Watch provides a mock function for the type MockServiceInterface
func (_mock *MockServiceInterface) Watch(ctx context.Context, opts v10.ListOptions) (watch.Interface, error) {
	ret := _mock.Called(ctx, opts)

	if len(ret) == 0 {
		panic("no return value specified for Watch")
	}

	var r0 watch.Interface
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, v10.ListOptions) (watch.Interface, error)); ok {
		return returnFunc(ctx, opts)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, v10.ListOptions) watch.Interface); ok {
		r0 = returnFunc(ctx, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(watch.Interface)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, v10.ListOptions) error); ok {
		r1 = returnFunc(ctx, opts)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockServiceInterface_Watch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Watch'
type MockServiceInterface_Watch_Call struct {
	*mock.Call
}

// Watch is a helper method to define mock.On call
//   - ctx context.Context
//   - opts v10.ListOptions
func (_e *MockServiceInterface_Expecter) Watch(ctx interface{}, opts interface{}) *MockServiceInterface_Watch_Call {
	return &MockServiceInterface_Watch_Call{Call: _e.mock.On("Watch", ctx, opts)}
}

func (_c *MockServiceInterface_Watch_Call) Run(run func(ctx context.Context, opts v10.ListOptions)) *MockServiceInterface_Watch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 v10.ListOptions
		if args[1] != nil {
			arg1 = args[1].(v10.ListOptions)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockServiceInterface_Watch_Call) Return(interfaceParam watch.Interface, err error) *MockServiceInterface_Watch_Call {
	_c.Call.Return(interfaceParam, err)
	return _c
}

func (_c *MockServiceInterface_Watch_Call) RunAndReturn(run func(ctx context.Context, opts v10.ListOptions) (watch.Interface, error)) *MockServiceInterface_Watch_Call {
	_c.Call.Return(run)
	return _c
}
