// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package engine

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"k8s.io/apimachinery/pkg/apis/meta/v1/unstructured"
	"k8s.io/apimachinery/pkg/labels"
	"sigs.k8s.io/controller-runtime/pkg/client"
)

// NewMockClusterReader creates a new instance of MockClusterReader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClusterReader(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClusterReader {
	mock := &MockClusterReader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockClusterReader is an autogenerated mock type for the ClusterReader type
type MockClusterReader struct {
	mock.Mock
}

type MockClusterReader_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClusterReader) EXPECT() *MockClusterReader_Expecter {
	return &MockClusterReader_Expecter{mock: &_m.Mock}
}

// Get provides a mock function for the type MockClusterReader
func (_mock *MockClusterReader) Get(ctx context.Context, key client.ObjectKey, obj *unstructured.Unstructured) error {
	ret := _mock.Called(ctx, key, obj)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, client.ObjectKey, *unstructured.Unstructured) error); ok {
		r0 = returnFunc(ctx, key, obj)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClusterReader_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockClusterReader_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - key client.ObjectKey
//   - obj *unstructured.Unstructured
func (_e *MockClusterReader_Expecter) Get(ctx interface{}, key interface{}, obj interface{}) *MockClusterReader_Get_Call {
	return &MockClusterReader_Get_Call{Call: _e.mock.On("Get", ctx, key, obj)}
}

func (_c *MockClusterReader_Get_Call) Run(run func(ctx context.Context, key client.ObjectKey, obj *unstructured.Unstructured)) *MockClusterReader_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 client.ObjectKey
		if args[1] != nil {
			arg1 = args[1].(client.ObjectKey)
		}
		var arg2 *unstructured.Unstructured
		if args[2] != nil {
			arg2 = args[2].(*unstructured.Unstructured)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockClusterReader_Get_Call) Return(err error) *MockClusterReader_Get_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClusterReader_Get_Call) RunAndReturn(run func(ctx context.Context, key client.ObjectKey, obj *unstructured.Unstructured) error) *MockClusterReader_Get_Call {
	_c.Call.Return(run)
	return _c
}

// ListClusterScoped provides a mock function for the type MockClusterReader
func (_mock *MockClusterReader) ListClusterScoped(ctx context.Context, list *unstructured.UnstructuredList, selector labels.Selector) error {
	ret := _mock.Called(ctx, list, selector)

	if len(ret) == 0 {
		panic("no return value specified for ListClusterScoped")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *unstructured.UnstructuredList, labels.Selector) error); ok {
		r0 = returnFunc(ctx, list, selector)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClusterReader_ListClusterScoped_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListClusterScoped'
type MockClusterReader_ListClusterScoped_Call struct {
	*mock.Call
}

// ListClusterScoped is a helper method to define mock.On call
//   - ctx context.Context
//   - list *unstructured.UnstructuredList
//   - selector labels.Selector
func (_e *MockClusterReader_Expecter) ListClusterScoped(ctx interface{}, list interface{}, selector interface{}) *MockClusterReader_ListClusterScoped_Call {
	return &MockClusterReader_ListClusterScoped_Call{Call: _e.mock.On("ListClusterScoped", ctx, list, selector)}
}

func (_c *MockClusterReader_ListClusterScoped_Call) Run(run func(ctx context.Context, list *unstructured.UnstructuredList, selector labels.Selector)) *MockClusterReader_ListClusterScoped_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *unstructured.UnstructuredList
		if args[1] != nil {
			arg1 = args[1].(*unstructured.UnstructuredList)
		}
		var arg2 labels.Selector
		if args[2] != nil {
			arg2 = args[2].(labels.Selector)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockClusterReader_ListClusterScoped_Call) Return(err error) *MockClusterReader_ListClusterScoped_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClusterReader_ListClusterScoped_Call) RunAndReturn(run func(ctx context.Context, list *unstructured.UnstructuredList, selector labels.Selector) error) *MockClusterReader_ListClusterScoped_Call {
	_c.Call.Return(run)
	return _c
}

// ListNamespaceScoped provides a mock function for the type MockClusterReader
func (_mock *MockClusterReader) ListNamespaceScoped(ctx context.Context, list *unstructured.UnstructuredList, namespace string, selector labels.Selector) error {
	ret := _mock.Called(ctx, list, namespace, selector)

	if len(ret) == 0 {
		panic("no return value specified for ListNamespaceScoped")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *unstructured.UnstructuredList, string, labels.Selector) error); ok {
		r0 = returnFunc(ctx, list, namespace, selector)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClusterReader_ListNamespaceScoped_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListNamespaceScoped'
type MockClusterReader_ListNamespaceScoped_Call struct {
	*mock.Call
}

// ListNamespaceScoped is a helper method to define mock.On call
//   - ctx context.Context
//   - list *unstructured.UnstructuredList
//   - namespace string
//   - selector labels.Selector
func (_e *MockClusterReader_Expecter) ListNamespaceScoped(ctx interface{}, list interface{}, namespace interface{}, selector interface{}) *MockClusterReader_ListNamespaceScoped_Call {
	return &MockClusterReader_ListNamespaceScoped_Call{Call: _e.mock.On("ListNamespaceScoped", ctx, list, namespace, selector)}
}

func (_c *MockClusterReader_ListNamespaceScoped_Call) Run(run func(ctx context.Context, list *unstructured.UnstructuredList, namespace string, selector labels.Selector)) *MockClusterReader_ListNamespaceScoped_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *unstructured.UnstructuredList
		if args[1] != nil {
			arg1 = args[1].(*unstructured.UnstructuredList)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 labels.Selector
		if args[3] != nil {
			arg3 = args[3].(labels.Selector)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockClusterReader_ListNamespaceScoped_Call) Return(err error) *MockClusterReader_ListNamespaceScoped_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClusterReader_ListNamespaceScoped_Call) RunAndReturn(run func(ctx context.Context, list *unstructured.UnstructuredList, namespace string, selector labels.Selector) error) *MockClusterReader_ListNamespaceScoped_Call {
	_c.Call.Return(run)
	return _c
}

// Sync provides a mock function for the type MockClusterReader
func (_mock *MockClusterReader) Sync(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Sync")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClusterReader_Sync_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Sync'
type MockClusterReader_Sync_Call struct {
	*mock.Call
}

// Sync is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockClusterReader_Expecter) Sync(ctx interface{}) *MockClusterReader_Sync_Call {
	return &MockClusterReader_Sync_Call{Call: _e.mock.On("Sync", ctx)}
}

func (_c *MockClusterReader_Sync_Call) Run(run func(ctx context.Context)) *MockClusterReader_Sync_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockClusterReader_Sync_Call) Return(err error) *MockClusterReader_Sync_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClusterReader_Sync_Call) RunAndReturn(run func(ctx context.Context) error) *MockClusterReader_Sync_Call {
	_c.Call.Return(run)
	return _c
}
