apiVersion: autocloud.config.kaweezle.com/v1alpha1
kind: PlatformValues
metadata:
  name: iknite-values
data:
  domain_suffix: iknite.app
  project:
    name: Iknite
    label: Iknite
    slug: iknite
    email: antoine@mrtn.fr
    git:
      # The main Git repository for the platform.
      repoURL: git@github.com:kaweezle/iknite.git
      targetRevision: main
      basePath: iknite
  argocd:
    domain: argocd-e2e.iknite.app
    repo_server_image_name: ghcr.io/kaweezle/argocd-helmfile
    repo_server_image_tag: v3.3.2-1.3.2-1
    github:
      base_url: git@github.com:kaweezle
      organization: kaweezle
  bootstrap:
    repo_url: git@github.com:kaweezle/iknite.git
    repo_target_revision: main
    application_path: deploy/k8s/argocd/e2e/appstages/appstage-00-bootstrap/application.yaml
