# cSpell: words covermode coverprofile unittests iknitectl
name: "Iknite: Build and test with Go"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths:
      - "cmd/**"
      - "pkg/**"
      - "go.mod"
      - "go.sum"
      - ".github/workflows/go.yaml"

jobs:
  build:
    name: Build and test
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
          check-latest: true
          cache: true
        id: go

      - name: Build iknite
        run: go build -v ./cmd/iknite/...

      - name: Build iknitectl
        run: go build -v ./cmd/iknitectl/...

      - name: Test
        run: |
          go test -v -race -covermode=atomic -coverprofile=coverage.out -coverpkg ./... ./...
          go run hack/nocov.go coverage.out
          mv coverage.out.nocov coverage.out

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v6
        if: ${{ !cancelled() }}
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: unittests
