# cSpell: disable
name: Release (GoReleaser, Root FS, VM images, APK repo, E2E tests)

on:
  pull_request:
    branches: ["main"]
    types: [labeled, synchronize, opened]
  push:
    tags: ["v*"]

env:
  REGISTRY: ghcr.io

jobs:
  goreleaser-snapshot:
    name: Build and release
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' || contains(github.event.pull_request.labels.*.name, 'e2e') && github.actor != 'dependabot[bot]' }}
    permissions:
      contents: write
      packages: write
    steps:
      -
        name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      -
        name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: ^1
      -
        name: Log in to Container Registry
        uses: docker/login-action@v4
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Cache Docker layers
        uses: actions/cache@v5
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-single-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-single-buildx
      -
        name: Install aqua dependencies
        uses: aquaproj/aqua-installer@11dd79b4e498d471a9385aa9fb7f62bb5f52a73c # v4.0.4
        with:
          aqua_version: v2.56.6
          aqua_opts: "" # Unset `-l` option
        env:
          AQUA_DISABLE_COSIGN: "true"
          AQUA_DISABLE_SLSA: "true"
      -
        name: Install image building dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends qemu-utils qemu-guest-agent genisoimage libarchive-tools
          # Install buildctl
          BUILDKIT_VERSION=0.28.0
          curl -L -o buildkit.tar.gz https://github.com/moby/buildkit/releases/download/v${BUILDKIT_VERSION}/buildkit-v${BUILDKIT_VERSION}.linux-amd64.tar.gz
          tar -xzf buildkit.tar.gz -C /usr/local/bin --strip-components=1 bin/buildctl
          rm buildkit.tar.gz
          buildctl --version
          make info
          helmfile init --force
          helm plugin install https://github.com/mumoshu/helm-x
      -
        name: Import Signature key
        id: import-signing-key
        shell: bash
        run: |
          mkdir -p ~/.config/sops/age
          echo -e "$AGE_PRIVATE_KEY" > ~/.config/sops/age/keys.txt
          chmod 600 ~/.config/sops/age/keys.txt
          make ci-extract-key
        env:
          AGE_PRIVATE_KEY: ${{ secrets.AGE_PRIVATE_KEY }}
      -
        name: Run GoReleaser (iknite and iknitectl packages)
        run: |
          make apk-iknite-build
      -
        name: Build iknite images APK
        run: |
          make apk-images-build
      -
        name: Build incus agent APK
        run: |
          make apk-incus-agent-build
      -
        name: Download karmafun apk
        run: |
          make apk-karmafun-fetch
      -
        name: Build APK repo
        run: |
          make apk-repo-build
      -
        name: Upload APK repo
        run: |
          make apk-repo-publish
      -
        name: Upload All packages artifact
        uses: actions/upload-artifact@v7
        with:
          name: packages
          path: |
            dist/repo/*
      -
        name: Make rootfs
        run: |
          make rootfs
      -
        name: Upload root fs artifact
        uses: actions/upload-artifact@v7
        with:
          name: rootfs
          path: |
            dist/*.rootfs.tar.gz
      -
        name: Make rootfs image
        run: |
          make rootfs-image PUSH_IMAGES=true
          make rootfs-image-incus-attachment
      -
        name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
      -
        name: Build VM images
        run: |
          make vm-images-build
      -
        name: Push VM images to registry
        run: |
          make vm-images-push
      -
        name: Create OpenStack image and test VM deployment
        id: create-and-test-openstack-image
        # if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
        if: github.event_name == 'pull_request'
        run: |
          make e2e VM_STACK=openstack
      -
        name: Push Images to object storage
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
        run: |
          make vm-images-publish
      -
        name: Prepare release files
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
        run: |
          make ci-release-files
      -
        name: Create the GitHub Release (draft)
        uses: softprops/action-gh-release@v2
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
        with:
          draft: true
          generate_release_notes: true
          body_path: RELEASE.md
          files: |
            release/*
