on:
  push:
    branches: [main]

name: Create Git Tag
jobs:
  versioner:
    name: Create a tag if version has changed
    runs-on: ubuntu-latest
    steps:
      - name: Update Version
        uses: antoinemartin/tag-action@main
        env:
          ACCESS_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}
