# cSpell: disable
name: Openstack VM image E2E test

on:
  pull_request:
    branches: ["main"]
    types: [labeled, synchronize, opened]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-vm-image:
    name: Test Iknite VM image on OpenStack
    if: ${{ contains(github.event.pull_request.labels.*.name, 'test-e2e') && github.actor != 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      -
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          fetch-tags: "true"
      -
        name: Retrieve aqua cache
        uses: actions/cache@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # v5.0.3
        with:
          path: ~/.local/share/aquaproj-aqua
          key: v2-aqua-installer-${{runner.os}}-${{runner.arch}}-${{hashFiles('aqua.yaml')}}
          restore-keys: |
            v2-aqua-installer-${{runner.os}}-${{runner.arch}}-
      -
        name: Install aqua dependencies
        uses: aquaproj/aqua-installer@11dd79b4e498d471a9385aa9fb7f62bb5f52a73c # v4.0.4
        with:
          aqua_version: v2.56.6
          aqua_opts: "" # Unset `-l` option
        env:
          AQUA_DISABLE_COSIGN: "true"
          AQUA_DISABLE_SLSA: "true"
      -
        name: Install image building dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends libarchive-tools
          # Install buildctl
          BUILDKIT_VERSION=0.28.0
          curl -L -o buildkit.tar.gz https://github.com/moby/buildkit/releases/download/v${BUILDKIT_VERSION}/buildkit-v${BUILDKIT_VERSION}.linux-amd64.tar.gz
          tar -xzf buildkit.tar.gz -C /usr/local/bin --strip-components=1 bin/buildctl
          buildctl --version
          make print-HAS_WORKING_DOCKER  || true
          make print-BUILDX_BUILDER || true
          make print-BUILDKIT_HOST || true
          docker buildx ls || true
          BUILDKIT_HOST=docker-container://buildx_buildkit_iknite0 buildctl debug workers || true
          make print-HAS_WORKING_ROOTLESS_BUILDCTL || true
          make print-BUILD_CONTAINER_CMD || true
          helmfile init --force
          helm plugin install https://github.com/mumoshu/helm-x
      -
        name: Import Signature key
        id: import-signing-key
        shell: bash
        run: |
          mkdir -p ~/.config/sops/age
          echo -e "$AGE_PRIVATE_KEY" > ~/.config/sops/age/keys.txt
          chmod 600 ~/.config/sops/age/keys.txt
          make extract-key
        env:
          AGE_PRIVATE_KEY: ${{ secrets.AGE_PRIVATE_KEY }}
      -
        name: Checking argocd deployment
        run: |
          cd deploy/k8s/argocd/common/argocd-server
          echo "############################################################"
          echo "Release list..."
          helmfile list --output json | jq .
          echo "############################################################"
          echo "Build checksum..."
          helmfile build --embed-values | grep -v '^#' | grep -v '^filepath: ' | sha256sum
      -
        name: Create OpenStack image and test VM deployment
        id: create-and-test-openstack-image
        run: |
          make e2e-tg-init VM_STACK=openstack
          make e2e-tg-refresh VM_STACK=openstack
          make e2e-tg-apply-vm VM_STACK=openstack
          make e2e-check-argocd VM_STACK=openstack
      -
        name: Clean OpenStack image
        id: clean-openstack-image
        if: ${{ contains(github.event.pull_request.labels.*.name, 'clean-e2e') }}
        run: |
          make e2e-tg-destroy VM_STACK=openstack
